//! Migration Registry Module
//!
//! Provides both global (production) and local (testing) migration registries
//! with a unified `MigrationRegistry` trait interface.
//!
//! # Architecture
//!
//! This module implements a hybrid registry architecture:
//!
//! - **GlobalRegistry**: Production registry using `linkme::distributed_slice` for
//!   compile-time collection of migrations. Supports runtime registration for
//!   dynamic scenarios.
//!
//! - **LocalRegistry**: Test-specific registry using pure runtime registration.
//!   Provides complete isolation between test cases without linkme's global state.
//!
//! - **MigrationRegistry** trait: Unified interface for both implementations,
//!   enabling polymorphic usage in production and test code.
//!
//! # Usage in Production
//!
//! Use the global registry for production code:
//!
//! ```rust,ignore
//! use reinhardt_db::migrations::registry::{global_registry, MigrationRegistry};
//!
//! let registry = global_registry();
//! let all_migrations = registry.all_migrations();
//! let polls_migrations = registry.migrations_for_app("polls");
//! ```
//!
//! Migrations are automatically registered via the `collect_migrations!` macro:
//!
//! ```rust,ignore
//! // Example file structure (migrations.rs in your application)
//! // These modules would be generated by the migration system:
//!
//! pub mod _0001_initial;
//! pub mod _0002_add_fields;
//!
//! // The collect_migrations! macro handles registration:
//! // reinhardt::collect_migrations!(
//! //     app_label = "polls",
//! //     _0001_initial,
//! //     _0002_add_fields,
//! // );
//! ```
//!
//! # Usage in Tests
//!
//! Use local registries for isolated unit tests:
//!
//! ```rust,no_run
//! use reinhardt_db::migrations::registry::{LocalRegistry, MigrationRegistry};
//! # use reinhardt_db::migrations::Migration;
//!
//! #[test]
//! fn test_migration_operations() {
//!     let registry = LocalRegistry::new();
//!
//!     registry.register(Migration {
//!         app_label: "polls".to_string(),
//!         name: "0001_initial".to_string(),
//!         operations: vec![],
//!         dependencies: vec![],
//!     }).unwrap();
//!
//!     let migrations = registry.all_migrations();
//!     assert_eq!(migrations.len(), 1);
//! }
//! ```
//!
//! For convenience, use the `reinhardt-test` fixtures:
//!
//! ```rust,no_run
//! # use reinhardt_db::migrations::registry::LocalRegistry;
//! # use reinhardt_db::migrations::registry::MigrationRegistry;
//! // use reinhardt_test::fixtures::*;
//! // use rstest::*;
//!
//! // #[rstest]
//! fn test_with_fixture(migration_registry: LocalRegistry) {
//!     // Registry is empty and isolated
//!     assert!(migration_registry.all_migrations().is_empty());
//! }
//! ```

// Module declarations (Rust 2024 Edition)
pub mod global;
pub mod local;
pub mod traits;

// Re-export commonly used items
pub use global::{GlobalRegistry, MIGRATION_PROVIDERS, global_registry};
pub use local::LocalRegistry;
pub use traits::MigrationRegistry;
