use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "dm",
		name: "0001_initial",
		operations: vec![
			Operation::AlterColumn {
				table: "dm_message",
				column: "content",
				new_definition: ColumnDefinition {
					name: "content",
					type_definition: FieldType::VarChar(1000u32),
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "created_at",
				new_definition: ColumnDefinition {
					name: "created_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "id",
				new_definition: ColumnDefinition {
					name: "id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "is_read",
				new_definition: ColumnDefinition {
					name: "is_read",
					type_definition: FieldType::Boolean,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "room_id",
				new_definition: ColumnDefinition {
					name: "room_id",
					type_definition: FieldType::Uuid,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "sender_id",
				new_definition: ColumnDefinition {
					name: "sender_id",
					type_definition: FieldType::Uuid,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_message",
				column: "updated_at",
				new_definition: ColumnDefinition {
					name: "updated_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room",
				column: "created_at",
				new_definition: ColumnDefinition {
					name: "created_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room",
				column: "id",
				new_definition: ColumnDefinition {
					name: "id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room",
				column: "is_group",
				new_definition: ColumnDefinition {
					name: "is_group",
					type_definition: FieldType::Boolean,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room",
				column: "name",
				new_definition: ColumnDefinition {
					name: "name",
					type_definition: FieldType::VarChar(100u32),
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room",
				column: "updated_at",
				new_definition: ColumnDefinition {
					name: "updated_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room_members",
				column: "from_d_m_room_id",
				new_definition: ColumnDefinition {
					name: "from_d_m_room_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room_members",
				column: "id",
				new_definition: ColumnDefinition {
					name: "id",
					type_definition: FieldType::Integer,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: true,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "dm_room_members",
				column: "to_user_id",
				new_definition: ColumnDefinition {
					name: "to_user_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::DropTable {
				name: "dm_dmroom_members",
			},
			Operation::CreateTable {
				name: "dm_dmroom_members",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "dmroom_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "user_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_dm_dmroom_members_dmroom_id".to_string(),
						columns: vec!["dmroom_id".to_string()],
						referenced_table: "dm_room".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_dm_dmroom_members_user_id".to_string(),
						columns: vec!["user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "dm_dmroom_members_unique".to_string(),
						columns: vec!["dmroom_id".to_string(), "user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::RenameTable {
				old_name: "dm_message",
				new_name: "dm_message",
			},
			Operation::RenameTable {
				old_name: "dm_room",
				new_name: "dm_room",
			},
			Operation::RenameTable {
				old_name: "dm_room_members",
				new_name: "dm_room_members",
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
