use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration {
		app_label: "dm".to_string(),
		name: "0001_initial".to_string(),
		operations: vec![
			Operation::CreateTable {
				name: "dm_message".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "content".to_string(),
						type_definition: FieldType::VarChar(1000u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "is_read".to_string(),
						type_definition: FieldType::Boolean,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "room_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "sender_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "updated_at".to_string(),
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "dm_room".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "is_group".to_string(),
						type_definition: FieldType::Boolean,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "name".to_string(),
						type_definition: FieldType::VarChar(100u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "updated_at".to_string(),
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "dm_dmroom_members".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "dmroom_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_dm_dmroom_members_dmroom_id".to_string(),
						columns: vec!["dmroom_id".to_string()],
						referenced_table: "dm_room".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_dm_dmroom_members_user_id".to_string(),
						columns: vec!["user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "dm_dmroom_members_unique".to_string(),
						columns: vec!["dmroom_id".to_string(), "user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
		],
		dependencies: vec![("auth".to_string(), "0001_initial".to_string())],
		atomic: true,
		replaces: vec![],
		..Default::default()
	}
}
