use reinhardt_db::migrations::{
	BulkLoadFormat, BulkLoadOptions, BulkLoadSource, ColumnDefinition, FieldType,
	FilesystemRepository, Migration, MigrationError, MigrationRenderOptions, MigrationSource,
	Operation,
	dependency::{DependencyCondition, OptionalDependency, SwappableDependency},
};
use std::fs;
use tempfile::TempDir;

fn migration() -> Migration {
	let mut migration = Migration::new("0001_squashed", "accounts");
	migration.operations.push(Operation::CreateTable {
		name: "accounts".to_string(),
		columns: vec![ColumnDefinition::new("id", FieldType::Integer)],
		constraints: vec![],
		without_rowid: None,
		interleave_in_parent: None,
		partition: None,
	});
	migration
}

#[test]
fn render_produces_parseable_formatted_source_with_optional_header() {
	let temp_dir = TempDir::new().unwrap();
	let repository = FilesystemRepository::new(temp_dir.path());

	let with_header = repository
		.render(
			&migration(),
			MigrationRenderOptions {
				include_header: true,
			},
		)
		.unwrap();
	let without_header = repository
		.render(
			&migration(),
			MigrationRenderOptions {
				include_header: false,
			},
		)
		.unwrap();

	syn::parse_file(&with_header).unwrap();
	syn::parse_file(&without_header).unwrap();
	assert!(with_header.starts_with(
		"// reinhardt-migration-source: 1\n// Generated by Reinhardt migrations.\n\n"
	));
	assert!(without_header.starts_with("// reinhardt-migration-source: 1\n"));
	assert!(!without_header.contains("Generated by Reinhardt migrations"));
	assert!(without_header.contains("Migration::new"));
}

#[tokio::test]
async fn render_preserves_dependencies_replacements_flags_and_conditional_metadata() {
	let temp_dir = TempDir::new().unwrap();
	let repository = FilesystemRepository::new(temp_dir.path());
	let mut migration = migration();
	migration.dependencies = vec![("auth".to_string(), "0001_initial".to_string())];
	migration.replaces = vec![
		("accounts".to_string(), "0001_initial".to_string()),
		("accounts".to_string(), "0002_handle".to_string()),
	];
	migration.atomic = false;
	migration.initial = Some(false);
	migration.state_only = true;
	migration.database_only = false;
	migration.swappable_dependencies = vec![SwappableDependency::new(
		"AUTH_USER_MODEL",
		"auth",
		"User",
		"0001_initial",
	)];
	migration.optional_dependencies = vec![OptionalDependency::new(
		"audit",
		"0001_initial",
		DependencyCondition::FeatureEnabled("audit".to_string()),
	)];
	migration.operations.push(Operation::BulkLoad {
		table: "accounts".to_string(),
		source: BulkLoadSource::Stdin,
		format: BulkLoadFormat::Csv,
		options: BulkLoadOptions::default(),
	});

	let source = repository
		.render(
			&migration,
			MigrationRenderOptions {
				include_header: false,
			},
		)
		.unwrap();
	repository
		.create_new_source("accounts", "0001_squashed", &source)
		.unwrap();
	let loaded = reinhardt_db::migrations::FilesystemSource::new(temp_dir.path())
		.all_migrations()
		.await
		.unwrap();
	let loaded = &loaded[0];

	assert_eq!(loaded.operations, migration.operations);
	assert_eq!(loaded.dependencies, migration.dependencies);
	assert_eq!(loaded.replaces, migration.replaces);
	assert_eq!(loaded.atomic, migration.atomic);
	assert_eq!(loaded.initial, migration.initial);
	assert_eq!(loaded.state_only, migration.state_only);
	assert_eq!(loaded.database_only, migration.database_only);
	assert_eq!(
		loaded.swappable_dependencies,
		migration.swappable_dependencies
	);
	assert_eq!(
		loaded.optional_dependencies,
		migration.optional_dependencies
	);
}

#[test]
fn create_new_source_formats_and_preserves_existing_destination() {
	let temp_dir = TempDir::new().unwrap();
	let repository = FilesystemRepository::new(temp_dir.path());
	let source = repository
		.render(
			&migration(),
			MigrationRenderOptions {
				include_header: false,
			},
		)
		.unwrap();

	let path = repository
		.create_new_source("accounts", "0001_squashed", &source)
		.unwrap();
	let formatted = fs::read_to_string(&path).unwrap();
	let error = repository
		.create_new_source("accounts", "0001_squashed", "fn replacement() {}")
		.unwrap_err();

	syn::parse_file(&formatted).unwrap();
	assert_eq!(fs::read_to_string(path).unwrap(), formatted);
	assert!(matches!(error, MigrationError::IoError(_)));
}

#[test]
fn create_new_source_rejects_invalid_names_and_source_before_writing() {
	let temp_dir = TempDir::new().unwrap();
	let repository = FilesystemRepository::new(temp_dir.path());

	let traversal = repository
		.create_new_source("../accounts", "0001_squashed", "fn migration() {}")
		.unwrap_err();
	let invalid_source = repository
		.create_new_source("accounts", "0001_squashed", "not valid Rust {")
		.unwrap_err();

	assert!(matches!(traversal, MigrationError::PathTraversal(_)));
	assert!(matches!(
		invalid_source,
		MigrationError::InvalidMigration(_)
	));
	assert!(!temp_dir.path().join("accounts/0001_squashed.rs").exists());
}

#[test]
fn create_new_source_rejects_unsafe_ascii_components() {
	let temp_dir = TempDir::new().unwrap();
	let repository = FilesystemRepository::new(temp_dir.path());
	let source = repository
		.render(
			&migration(),
			MigrationRenderOptions {
				include_header: false,
			},
		)
		.unwrap();
	let invalid_components = [
		("account app", "0001_initial"),
		(".accounts", "0001_initial"),
		("accounts.rs", "0001_initial"),
		("accounts", "migration"),
		("accounts", ".0001_initial"),
		("accounts", "0001 initial"),
		("accounts", "0001_initial.rs"),
		("accounts", "0001_\u{7f}"),
	];

	for (app_label, migration_name) in invalid_components {
		let error = repository
			.create_new_source(app_label, migration_name, &source)
			.unwrap_err();
		assert!(
			matches!(error, MigrationError::PathTraversal(_)),
			"{app_label}.{migration_name}: {error}"
		);
	}
}

#[cfg(unix)]
#[test]
fn create_new_source_does_not_follow_app_directory_symlink() {
	use std::os::unix::fs::symlink;

	let root = TempDir::new().unwrap();
	let outside = TempDir::new().unwrap();
	symlink(outside.path(), root.path().join("accounts")).unwrap();
	let repository = FilesystemRepository::new(root.path());
	let source = repository
		.render(
			&migration(),
			MigrationRenderOptions {
				include_header: false,
			},
		)
		.unwrap();

	let result = repository.create_new_source("accounts", "0001_squashed", &source);

	assert!(result.is_err());
	assert!(!outside.path().join("0001_squashed.rs").exists());
}
