use reinhardt_pages::ClientForm;
use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Serialize, Deserialize, ClientForm)]
#[client_form(server_fn = submit_settings)]
pub struct SettingsRequest {
	pub name: String,
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct SettingsResponse {
	name: String,
}

mod submit_settings {
	// Mirrors the marker module shape generated by #[server_fn].
	#[allow(non_camel_case_types)]
	pub struct marker;

	impl reinhardt_pages::server_fn::ServerFnMetadata for marker {
		const PATH: &'static str = "/api/server_fn/submit_settings";
		const NAME: &'static str = "submit_settings";
		const IS_JSON_CODEC: bool = true;
	}

	impl reinhardt_pages::server_fn::ServerFnRequestMetadata for marker {
		type Request = crate::SettingsRequest;
	}

	impl reinhardt_pages::server_fn::ServerFnResponseMetadata for marker {
		type Response = crate::SettingsResponse;
		type Error = reinhardt_pages::server_fn::ServerFnError;
	}

	pub fn mutation() -> impl Fn(
		<marker as reinhardt_pages::server_fn::ServerFnRequestMetadata>::Request,
	) -> std::pin::Pin<
		std::boxed::Box<
			dyn std::future::Future<
					Output = std::result::Result<
						<marker as reinhardt_pages::server_fn::ServerFnResponseMetadata>::Response,
						<marker as reinhardt_pages::server_fn::ServerFnResponseMetadata>::Error,
					>,
				>,
		>,
	> {
		|request| {
			let _request = request;
			std::boxed::Box::pin(async move { ::core::unreachable!() })
		}
	}
}

fn main() {}
