//! Script prefix management
//!
//! Provides functions to set, get, and clear the script prefix for URL generation.
//! This is useful when your application is deployed at a non-root path
//! (e.g., "/myapp/" instead of "/").
//!
//! # Thread Safety
//!
//! The script prefix is stored in thread-local storage, so each thread has its own
//! independent script prefix. This matches Django's behavior.
//!
//! # Examples
//!
//! ```rust
//! use reinhardt_routers::script_prefix::{set_script_prefix, get_script_prefix, clear_script_prefix};
//!
//! // Set a custom script prefix
//! set_script_prefix("/myapp/");
//! assert_eq!(get_script_prefix(), "/myapp/");
//!
//! // Clear the prefix (returns to default "/")
//! clear_script_prefix();
//! assert_eq!(get_script_prefix(), "/");
//! ```

use std::cell::RefCell;

thread_local! {
	/// Thread-local storage for the script prefix.
	/// Defaults to "/" if not set.
	static SCRIPT_PREFIX: RefCell<String> = RefCell::new(String::from("/"));
}

/// Set the script prefix for URL generation.
///
/// The script prefix is prepended to all URLs generated by the reverse URL functions.
/// This is useful when your application is deployed at a non-root path.
///
/// # Arguments
///
/// * `prefix` - The script prefix to set. Should start and end with "/" for proper URL generation.
///
/// # Examples
///
/// ```rust
/// use reinhardt_routers::script_prefix::set_script_prefix;
///
/// set_script_prefix("/myapp/");
/// ```
pub fn set_script_prefix(prefix: &str) {
	SCRIPT_PREFIX.with(|p| {
		*p.borrow_mut() = prefix.to_string();
	});
}

/// Get the current script prefix.
///
/// Returns the current script prefix, or "/" if no prefix has been set.
///
/// # Examples
///
/// ```rust
/// use reinhardt_routers::script_prefix::{set_script_prefix, get_script_prefix};
///
/// set_script_prefix("/myapp/");
/// assert_eq!(get_script_prefix(), "/myapp/");
/// ```
pub fn get_script_prefix() -> String {
	SCRIPT_PREFIX.with(|p| p.borrow().clone())
}

/// Clear the script prefix, resetting it to the default "/".
///
/// # Examples
///
/// ```rust
/// use reinhardt_routers::script_prefix::{set_script_prefix, get_script_prefix, clear_script_prefix};
///
/// set_script_prefix("/myapp/");
/// clear_script_prefix();
/// assert_eq!(get_script_prefix(), "/");
/// ```
pub fn clear_script_prefix() {
	SCRIPT_PREFIX.with(|p| {
		*p.borrow_mut() = String::from("/");
	});
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_default_script_prefix() {
		// Clear any previous state
		clear_script_prefix();
		assert_eq!(get_script_prefix(), "/");
	}

	#[test]
	fn test_set_and_get_script_prefix() {
		set_script_prefix("/myapp/");
		assert_eq!(get_script_prefix(), "/myapp/");

		// Cleanup
		clear_script_prefix();
	}

	#[test]
	fn test_clear_script_prefix() {
		set_script_prefix("/test/");
		assert_eq!(get_script_prefix(), "/test/");

		clear_script_prefix();
		assert_eq!(get_script_prefix(), "/");
	}

	#[test]
	fn test_multiple_set_operations() {
		set_script_prefix("/app1/");
		assert_eq!(get_script_prefix(), "/app1/");

		set_script_prefix("/app2/");
		assert_eq!(get_script_prefix(), "/app2/");

		set_script_prefix("/");
		assert_eq!(get_script_prefix(), "/");

		// Cleanup
		clear_script_prefix();
	}

	#[test]
	fn test_empty_prefix() {
		set_script_prefix("");
		assert_eq!(get_script_prefix(), "");

		// Cleanup
		clear_script_prefix();
	}

	#[test]
	fn test_prefix_without_trailing_slash() {
		set_script_prefix("/myapp");
		assert_eq!(get_script_prefix(), "/myapp");

		// Cleanup
		clear_script_prefix();
	}
}
