# AGENTS.md

## Purpose

These instructions apply to work on `{{ project_name }}`, a Reinhardt RESTful
application with a native management binary.

## Project Map

- `src/bin/manage.rs` is the management and development entry point.
- `src/lib.rs` contains shared library exports.
- `src/apps/` contains application modules generated by `startapp`.
- `src/config/` contains settings, installed apps, and project route aggregation.
- `settings/` contains base and profile-specific TOML configuration.
- `Makefile.toml` contains the supported development and verification tasks.

## Required Guidance

Read the relevant instruction before changing the matching surface:

- @instructions/MODULE_SYSTEM.md
- @instructions/ANTI_PATTERNS.md
- @instructions/MACRO_USAGE.md
- @instructions/ORM_GUIDANCE.md
- @instructions/TESTING_STANDARDS.md
- @instructions/DOCUMENTATION_STANDARDS.md
- @instructions/REINHARDT_RESTFUL.md

## Framework Usage

- Import framework APIs through the `reinhardt` facade.
- Add applications with `cargo run --bin manage startapp <name>` so generated registries stay synchronized.
- Use this extraction test for every feature: "Could this feature be extracted and moved to another project?" If not, reduce project-level coupling until the feature can live inside an app created with `startapp`.
- Keep feature-owned models, serializers, services, views, and routes inside that app; expose only explicit contracts to other apps.
- Keep project-level route composition in `src/config/urls.rs`; endpoint implementations belong to app-local modules.
- Keep installed-app registration in `src/config/apps.rs` and module declarations in `src/apps.rs`.
- Prefer endpoint macros, route helpers, typed serializers, and framework builders over parallel local infrastructure.

## API Boundaries

- Keep request and response contracts serializable and explicit.
- Define handlers, serializers, models, and services inside the owning app instead of flattening them into `src/config/`.
- Aggregate app routes through each app's `urls` module; do not import individual handlers into project configuration.
- Keep database, filesystem, and other server-only work in native code paths.

## Settings and Secrets

- Settings are composed from `settings/base.toml`, the selected profile, and `REINHARDT_` environment overrides.
- Keep shared defaults in `settings/*.example.toml`; generated `settings/*.toml` files are ignored and may contain private values. Provide deployment secrets through environment variables.
- Never commit credentials, private hostnames, or personal environment values.

## Testing and Verification

Use the narrowest relevant checks, then broaden them when shared behavior changes:

```bash
cargo make fmt-check
cargo make quality
cargo make test
cargo run --bin manage check
cargo run --bin manage showurls
```

Install the generated project's tools first with `cargo make install-tools` in a fresh environment. Tests must assert behavior, use Reinhardt components, and clean up created state.

## Documentation and Synchronization

- Update `README.md` and other relevant documentation when commands, layout, settings, or runtime behavior changes.
- Write code comments and rustdoc in English.
- `AGENTS.md` and `CLAUDE.md` are a deliberate mirror pair. Keep their content identical except for the top-level filename.
