# AGENTS.md

## Purpose

These instructions apply to work on `{{ project_name }}`, a Reinhardt Pages
application with a native management binary and a WASM frontend.

## Project Map

- `src/bin/manage.rs` is the native management and development entry point.
- `src/lib.rs` contains shared library exports and server-only macro support.
- `src/client/` contains browser-only launcher and components.
- `src/apps/` contains application modules generated by `startapp`.
- `src/config/` contains settings, installed apps, and project route aggregation.
- `settings/` contains base and profile-specific TOML configuration.
- `Makefile.toml` contains the supported development and verification tasks.

## Required Guidance

Read the relevant instruction before changing the matching surface:

- @instructions/MODULE_SYSTEM.md
- @instructions/ANTI_PATTERNS.md
- @instructions/MACRO_USAGE.md
- @instructions/PAGE_MACRO.md
- @instructions/REACTIVE_HOOKS.md
- @instructions/ORM_GUIDANCE.md
- @instructions/TESTING_STANDARDS.md
- @instructions/DOCUMENTATION_STANDARDS.md
- @instructions/REINHARDT_PAGES.md

## Framework Usage

- Import framework APIs through the `reinhardt` facade.
- Add applications with `cargo run --bin manage startapp <name> --with-pages` so generated registries stay synchronized.
- Use this extraction test for every feature: "Could this feature be extracted and moved to another project?" If not, reduce project-level coupling until the feature can live inside an app created with `startapp`.
- Keep feature-owned models, server functions, services, routes, and client components inside that app; expose only explicit serializable contracts to other apps.
- Keep project-level route composition in `src/config/urls.rs`; app-level routes belong to each app's `urls` module.
- Keep installed-app registration in `src/config/apps.rs` and module declarations in `src/apps.rs`.
- Prefer named imports, endpoint and Pages macros, route helpers, and typed framework builders over parallel local infrastructure.

## Pages Native/WASM Boundaries

- Keep shared DTOs and target-neutral declarations outside client-only and server-only modules.
- Keep browser code under `src/client/` or an app's `client/` modules.
- Keep native models, forms, views, admin wiring, database access, and filesystem work under server-gated modules.
- Use the generated `client`/`server` cfg aliases and do not import native-only dependencies into WASM code.
- Verify both native and browser targets after changing a shared boundary.

## Settings and Secrets

- Settings are composed from `settings/base.toml`, the selected profile, and `REINHARDT_` environment overrides.
- Keep shared defaults in `settings/*.example.toml`; generated `settings/*.toml` files are ignored and may contain private values. Provide deployment secrets through environment variables.
- Never commit credentials, private hostnames, or personal environment values.

## Testing and Verification

Use the narrowest relevant checks, then broaden them when shared behavior changes:

```bash
cargo make fmt-check
cargo make quality
cargo make test
cargo make wasm-build-dev
cargo make wasm-test
```

Install the generated project's tools first with `cargo make install-tools` in a fresh environment. Tests must assert behavior, use Reinhardt components, and clean up created state.

## Documentation and Synchronization

- Update `README.md` and other relevant documentation when commands, layout, settings, or runtime behavior changes.
- Write code comments and rustdoc in English.
- `AGENTS.md` and `CLAUDE.md` are a deliberate mirror pair. Keep their content identical except for the top-level filename.
