# {{ project_name }}

A Reinhardt Pages project with WASM frontend and server-side rendering.

## Prerequisites

- Rust 1.96.0 or later (2024 Edition)
- cargo-make: `cargo install cargo-make`
- wasm-pack for the browser bundle (installed by `cargo make install-tools`)
- PostgreSQL (optional, for database features)

## Getting Started

### Install Tools

```bash
# Install all development tools (includes WASM build tools)
cargo make install-tools
```

### Development Server

```bash
# Build WASM and start development server
cargo make dev

# Or step by step:
cargo make wasm-build-dev    # Build WASM
cargo make runserver         # Start server
```

Visit `http://127.0.0.1:8000/` in your browser.

`manage runserver` serves the HTTP and WebSocket routes from the project
router. If any application contributes gRPC services, the same command also
starts the gRPC listener on `127.0.0.1:50051`; override it with
`--grpc-address`. The generated application `urls.rs` files are merged from
`src/config/urls.rs`, so no custom server or WebSocket `main.rs` is required.
Browser WebSocket origins are allow-listed in `settings/base.toml`; replace the
generated local origins with the deployed HTTPS origin in production.

### Build for Production

```bash
# Build WASM (release + optimized)
cargo make wasm-build-release

# Build server
cargo build --release
```

## Project Structure

```
{{ project_name }}/
├── src/
│   ├── client/       # WASM UI (runs in browser)
│   │   ├── lib.rs
│   │   └── components/
│   ├── apps/         # App modules generated by startapp
│   │   ├── notes.rs
│   │   └── notes/
│   │       ├── serializers.rs # Client/server wire DTO declarations
│   │       ├── server_fn.rs   # Server-function declaration surface
│   │       ├── services.rs    # Client/server service declaration surface
│   │       ├── urls.rs        # Target-gated app route exports
│   │       ├── client/        # WASM-only UI and client services
│   │       ├── serializers/   # DTO implementations
│   │       ├── server_fn/     # Server-function implementations
│   │       ├── services/      # Split client/server service implementations
│   │       ├── urls/          # Split client/server route implementations
│   │       └── server/        # Native-only models/forms/views/admin wiring
│   └── config/       # Server configuration
├── dist/             # WASM build output
├── dist-wasm/        # wasm-pack output copied into dist/
├── index.html        # WASM entry HTML
├── scripts/          # cargo-make helper scripts
└── Cargo.toml
```

## Management Commands

```bash
# Create a new app
cargo run --bin manage startapp myapp --with-pages

# Database migrations (when using database features)
cargo run --bin manage makemigrations
cargo run --bin manage migrate

# Check project for issues
cargo run --bin manage check

# List registered server URL patterns
cargo run --bin manage showurls

# Run with a custom gRPC listener
cargo run --bin manage runserver --grpc-address 127.0.0.1:50061

# Export the deterministic application contract
cargo run --bin manage contract export --format json
```

### Rust management shell (opt-in)

The generated `commands-shell` feature is intentionally not part of the
default Pages features. Enable it explicitly:

```bash
cargo run --bin manage --features commands-shell -- shell
cargo run --bin manage --features commands-shell -- shell -c \
  'println!("{}", settings.core.debug)'
```

`src/config/shell.rs` supplies `get_shell_config()`. The outer native `main`
calls `shell_runtime_hook()` before the Tokio-backed `native::main`, and the
feature selects `execute_from_command_line_with_resolved_settings_and_shell`. Without
the feature, the resolved-settings dispatcher remains active for
non-shell commands.

The Rust evaluator binds `settings`, the ORM `db` handle, the application `di`
context, and a stable `framework` alias. Unique installed model names are
imported; collisions emit deterministic warnings with their concrete registered
crate paths, and the evaluator's `project_crate` alias can reference those same
types. A project can append Rust with `ShellConfig::with_prelude(...)`.

Interactive input is stateful, supports top-level `.await`, and uses `>>> ` /
`... ` prompts. A panic, evaluator exit, or Ctrl+C during evaluation resets
user state and reloads the project prelude and standard bindings. `shell -c`
evaluates once, exits zero only on success, and Reinhardt's own diagnostics do
not repeat the raw source. Arbitrary Rust, compiler output, panics, and user
code can still print literals; the shell is not a sandbox. History is loaded
and saved best-effort at
`<platform local data directory>/reinhardt/shell/<package-name>.history`.
A missing file is a silent first run; directory-resolution, read, or write
failures warn without preventing startup.

`shell-rhai` was removed; `shell` now means the Rust evaluator and does not
accept old Rhai syntax.

## WASM Build Commands

```bash
cargo make wasm-build-dev      # Build WASM (debug)
cargo make wasm-build-release  # Build WASM (release + optimize)
cargo make wasm-watch          # Watch and rebuild on changes
cargo make wasm-clean          # Clean WASM build artifacts
```

## Learn More

- [Generated `page!` Macro Guide](instructions/PAGE_MACRO.md)
- [Generated Reactive Hooks Guide](instructions/REACTIVE_HOOKS.md)
- [Generated ORM and Migration Guide](instructions/ORM_GUIDANCE.md)
- [Reinhardt Documentation](https://github.com/kent8192/reinhardt-rs)
- [Reinhardt Pages Guide](https://github.com/kent8192/reinhardt-rs/tree/main/docs)
- [wasm-pack Documentation](https://rustwasm.github.io/wasm-pack/)
