//! Cross-target server function metadata trait.
//!
//! `ServerFnMetadata` carries the call-site facts about a `#[server_fn]`:
//! its HTTP path, name, and wire codec. It is available on **both** native
//! and wasm targets without any feature flag.
//!
//! `ServerFnRegistration` (native, in [`super::registration`]) and
//! `MockableServerFn` (msw feature, in [`super::mockable`]) extend this
//! trait to add the target-specific entry points — the native HTTP
//! handler and the MSW mock dispatch types respectively. Constants live
//! here in one place; the supertraits inherit them.
//!
//! Manual implementation is not expected — the `#[server_fn]` macro emits
//! an implementation on the marker struct it generates, on every target.

/// Metadata describing a `#[server_fn]`-decorated function.
///
/// Implemented by the `marker` struct generated by `#[server_fn]` on both
/// native and wasm targets. Constants placed here are inherited by
/// `ServerFnRegistration` (native) and `MockableServerFn` (msw) so that a
/// single source of truth survives across the cfg boundary.
///
/// # Example (macro-generated)
///
/// ```ignore
/// // `#[server_fn] pub async fn login(...) -> Result<User, ServerFnError>`
/// // expands (in part) to:
/// pub mod login {
///     pub struct marker;
///
///     impl ::reinhardt_pages::server_fn::ServerFnMetadata for marker {
///         const PATH: &'static str = "/api/server_fn/login";
///         const NAME: &'static str = "login";
///         const CODEC: &'static str = "json";
///     }
/// }
/// ```
pub trait ServerFnMetadata: 'static {
	/// The HTTP path for this server function.
	///
	/// Default format: `/api/server_fn/{function_name}`. Customizable via
	/// `#[server_fn(endpoint = "/custom/path")]`.
	const PATH: &'static str;

	/// The name of the server function (used for debugging and logging).
	const NAME: &'static str;

	/// The codec this server function uses (`"json"`, `"url"`, `"msgpack"`).
	///
	/// Controls how the server expects to decode the incoming request body.
	/// The actual response `Content-Type` may differ depending on the codec;
	/// for example, the `"url"` codec still returns JSON responses while
	/// only the request format differs.
	const CODEC: &'static str = "json";

	/// Names of `#[inject]` parameters (for documentation / debugging).
	const INJECTED_PARAMS: &'static [&'static str] = &[];
}
