//! Cross-target server function metadata trait.
//!
//! `ServerFnMetadata` carries the call-site facts about a `#[server_fn]`:
//! its HTTP path, name, and wire codec. It is available on **both** native
//! and wasm targets without any feature flag.
//!
//! `ServerFnRegistration` (native, in [`super::registration`]) and
//! `MockableServerFn` (msw feature, in `super::mockable`) extend this
//! trait to add the target-specific entry points — the native HTTP
//! handler and the MSW mock dispatch types respectively. Constants live
//! here in one place; the supertraits inherit them.
//!
//! Manual implementation is not expected — the `#[server_fn]` macro emits
//! an implementation on the marker struct it generates, on every target.

/// Metadata describing a `#[server_fn]`-decorated function.
///
/// Implemented by the `marker` struct generated by `#[server_fn]` on both
/// native and wasm targets. Constants placed here are inherited by
/// `ServerFnRegistration` (native) and `MockableServerFn` (msw) so that a
/// single source of truth survives across the cfg boundary.
///
/// # Example (macro-generated)
///
/// ```ignore
/// // `#[server_fn] pub async fn login(...) -> Result<User, ServerFnError>`
/// // expands (in part) to:
/// pub mod login {
///     pub struct marker;
///
///     impl ::reinhardt_pages::server_fn::ServerFnMetadata for marker {
///         const PATH: &'static str = "/api/server_fn/login";
///         const NAME: &'static str = "login";
///         const CODEC: &'static str = "json";
///         const IS_JSON_CODEC: bool = true;
///     }
/// }
/// ```
pub trait ServerFnMetadata: 'static {
	/// The HTTP path for this server function.
	///
	/// Default format: `/api/server_fn/{function_name}`. Customizable via
	/// `#[server_fn(endpoint = "/custom/path")]`.
	const PATH: &'static str;

	/// The name of the server function (used for debugging and logging).
	const NAME: &'static str;

	/// The codec this server function uses (`"json"`, `"url"`, `"msgpack"`).
	///
	/// Controls how the server expects to decode the incoming request body.
	/// The actual response `Content-Type` may differ depending on the codec;
	/// for example, the `"url"` codec still returns JSON responses while
	/// only the request format differs.
	const CODEC: &'static str = "json";

	/// Whether this server function uses the default JSON request codec.
	///
	/// This mirrors [`Self::CODEC`] as a boolean so native hot paths can avoid
	/// per-request string comparisons when selecting response assembly.
	const IS_JSON_CODEC: bool;

	/// Names of `#[inject]` parameters (for documentation / debugging).
	const INJECTED_PARAMS: &'static [&'static str] = &[];

	/// Whether this action operates on one resource selected by its lookup.
	const DETAIL: bool = false;

	/// Whether this action executes inside a framework-owned transaction.
	const TRANSACTIONAL: bool = false;

	/// Whether the generated handler can access request extensions and set response cookies.
	///
	/// Plain server functions with only body-deserialized parameters cannot reach
	/// the request extension map, so the router can skip creating the shared
	/// response-cookie jar on that hot path.
	const USES_RESPONSE_COOKIE_JAR: bool = false;
}

/// Normalizes a server function's `Result` return type for generated query keys.
///
/// The [`crate::server_fn`] macro uses this trait instead of syntactically
/// inspecting a return type, so aliases such as `type AppResult<T> =
/// Result<T, AppError>` retain their declared error type in generated query
/// helpers.
#[doc(hidden)]
pub trait ServerFnQueryResult {
	/// The successful response payload.
	type Response;
	/// The declared server function error type.
	type Error;

	/// Converts the return value into the canonical query result shape.
	fn into_query_result(self) -> Result<Self::Response, Self::Error>;
}

impl<T, E> ServerFnQueryResult for Result<T, E> {
	type Response = T;
	type Error = E;

	fn into_query_result(self) -> Result<Self::Response, Self::Error> {
		self
	}
}

/// Defers query-key argument requirements until a generated `key(...)` helper is called.
///
/// Server functions only require request deserialization on the native side. The
/// query cache additionally needs owned, serializable arguments, so this trait
/// keeps those requirements on the opt-in helper rather than on every
/// `#[server_fn]` expansion.
#[doc(hidden)]
pub trait ServerFnQueryArg<T>: Clone + serde::Serialize + 'static {
	/// Converts an opt-in query-key argument to the server function argument type.
	fn into_query_arg(self) -> T;
}

impl<T> ServerFnQueryArg<T> for T
where
	T: Clone + serde::Serialize + 'static,
{
	fn into_query_arg(self) -> T {
		self
	}
}

/// Exposes the success response type of a `#[server_fn]` marker.
///
/// This is implemented by the `#[server_fn]` macro for public server function
/// markers whose return type is a direct `Result<T, E>`. Generated code can
/// use it to name the declared `Ok(T)` response type without changing the
/// public server function call signature. Scoped or private server functions
/// keep their basic [`ServerFnMetadata`] and native registration metadata, but
/// do not expose typed response metadata because the associated types may be
/// private to the defining module.
pub trait ServerFnResponseMetadata: ServerFnMetadata {
	/// Success response type (the `Ok` variant of the function's return type).
	type Response: 'static;
	/// Error type returned by the public server function stub.
	type Error: 'static;
}

/// Exposes the client-visible request argument type of a `#[server_fn]` marker.
///
/// This is implemented by the `#[server_fn]` macro when the public client call
/// shape has exactly one body-deserialized request argument. Parameters resolved
/// by `#[inject]` or `FromRequest` extractors are intentionally excluded because
/// clients and form submit helpers cannot provide them directly.
pub trait ServerFnRequestMetadata: ServerFnMetadata {
	/// Request type accepted by the client-visible server function call.
	type Request: 'static;
}
