//! Server Function Registration Trait
//!
//! This module provides the `ServerFnRegistration` trait which is automatically
//! implemented by the `#[server_fn]` macro for explicit router registration.
//!
//! ## Usage
//!
//! The trait is not meant to be implemented manually. Instead, use the `#[server_fn]`
//! macro which generates a marker struct and implements this trait automatically.
//!
//! ```ignore
//! use reinhardt_pages::server_fn::ServerFnRouterExt;
//! use crate::server_fn::{login, logout};
//!
//! let router = UnifiedRouter::new()
//!     .server_fn(login)
//!     .server_fn(logout);
//! ```

use super::registry::ServerFnHandler;

/// Server function registration metadata.
///
/// This trait is automatically implemented by the `#[server_fn]` macro
/// for each server function's marker struct. It provides the metadata
/// needed to register the server function with a router.
///
/// # Implementation
///
/// The `#[server_fn]` macro generates:
/// 1. A marker struct with the same name as the function (e.g., `login`)
/// 2. An implementation of this trait for that struct
///
/// # Example
///
/// Given a server function:
/// ```ignore
/// #[server_fn]
/// pub async fn login(username: String, password: String) -> Result<User, ServerFnError> {
///     // ...
/// }
/// ```
///
/// The macro generates:
/// ```ignore
/// pub struct login;
///
/// impl ServerFnRegistration for login {
///     const PATH: &'static str = "/api/server_fn/login";
///     const NAME: &'static str = "login";
///
///     fn handler() -> ServerFnHandler {
///         __server_fn_static_wrapper_login
///     }
/// }
/// ```
pub trait ServerFnRegistration: Send + Sync + 'static {
	/// The HTTP path for this server function.
	///
	/// Default format: `/api/server_fn/{function_name}`
	/// Can be customized via `#[server_fn(endpoint = "/custom/path")]`
	const PATH: &'static str;

	/// The name of the server function (for debugging and logging).
	const NAME: &'static str;

	/// Returns the handler function pointer.
	///
	/// This is the internal static wrapper function generated by the macro.
	fn handler() -> ServerFnHandler;
}
