//! Server Function Registration Trait
//!
//! This module provides the `ServerFnRegistration` trait which is automatically
//! implemented by the `#[server_fn]` macro for explicit router registration.
//!
//! ## Usage
//!
//! The trait is not meant to be implemented manually. Instead, use the `#[server_fn]`
//! macro which generates a marker struct and implements this trait automatically.
//!
//! ```ignore
//! use reinhardt_pages::server_fn::ServerFnRouterExt;
//! use crate::server_fn::{login, logout};
//!
//! let router = UnifiedRouter::new()
//!     .server_fn(login)
//!     .server_fn(logout);
//! ```

use super::metadata::ServerFnMetadata;
use super::registry::ServerFnHandler;

/// Native-side registration for a `#[server_fn]`.
///
/// Extends [`ServerFnMetadata`] (which provides `PATH`, `NAME`, `CODEC`, and
/// `INJECTED_PARAMS`) with the handler entry point used by the router on
/// the server side. The handler is intentionally absent on wasm — the
/// client target only sees the function's request stub, not its handler
/// function pointer.
///
/// This trait is automatically implemented by the `#[server_fn]` macro
/// for each server function's marker struct on native targets.
///
/// # Example
///
/// Given a server function:
/// ```ignore
/// #[server_fn]
/// pub async fn login(username: String, password: String) -> Result<User, ServerFnError> {
///     // ...
/// }
/// ```
///
/// The macro generates (on native):
/// ```ignore
/// pub mod login {
///     pub struct marker;
///
///     impl ::reinhardt_pages::server_fn::ServerFnMetadata for marker {
///         const PATH: &'static str = "/api/server_fn/login";
///         const NAME: &'static str = "login";
///         const CODEC: &'static str = "json";
///     }
///
///     impl ::reinhardt_pages::server_fn::ServerFnRegistration for marker {
///         fn handler() -> ServerFnHandler {
///             super::__server_fn_static_wrapper_login
///         }
///     }
/// }
/// ```
pub trait ServerFnRegistration: ServerFnMetadata + Send + Sync {
	/// Returns the handler function pointer.
	///
	/// This is the internal static wrapper function generated by the macro.
	fn handler() -> ServerFnHandler;
}
