//! Server Function Router Extension
//!
//! This module provides the `ServerFnRouterExt` extension trait for registering
//! server functions explicitly with `ServerRouter`.
//!
//! ## Usage
//!
//! ```ignore
//! use reinhardt::pages::server_fn::ServerFnRouterExt;
//! use crate::server_fn::{login, logout, get_user};
//!
//! pub fn routes() -> ServerRouter {
//!     ServerRouter::new()
//!         .server_fn(login)
//!         .server_fn(logout)
//!         .server_fn(get_user)
//! }
//! ```

use super::ServerFnError;
use super::registration::ServerFnRegistration;
use hyper::header::{CONTENT_TYPE, HeaderValue};
use hyper::{Method, StatusCode};
use reinhardt_core::endpoint::EndpointInfo;
use reinhardt_http::{Handler, Request, Response, Result, SharedResponseCookies};
use reinhardt_urls::routers::ServerRouter;
use std::marker::PhantomData;

/// Extension trait for registering server functions with `ServerRouter`.
///
/// This trait provides the `server_fn` method which allows explicit registration
/// of server functions. Unlike the previous `register_all_server_functions()`
/// approach, this makes the registration explicit and visible.
///
/// # Example
///
/// ```ignore
/// use reinhardt::pages::server_fn::ServerFnRouterExt;
/// use crate::server_fn::{login, logout};
///
/// let router = ServerRouter::new()
///     .server_fn(login)    // Explicitly register login
///     .server_fn(logout);  // Explicitly register logout
/// ```
///
/// # Benefits
///
/// - **Explicit**: Clearly shows which server functions are registered
/// - **Type-safe**: Compiler ensures only valid server functions are passed
/// - **IDE-friendly**: Auto-completion and go-to-definition work correctly
/// - **Controllable**: Prevents accidental registration of server functions
pub trait ServerFnRouterExt {
	/// Register a server function with this router.
	///
	/// The server function must have been defined with the `#[server_fn]` macro,
	/// which generates the marker struct passed as the `marker` argument.
	///
	/// # Arguments
	///
	/// * `marker` - The marker struct generated by `#[server_fn]` macro
	///
	/// # Returns
	///
	/// Returns `self` with the server function registered, allowing method chaining.
	///
	/// # Example
	///
	/// ```ignore
	/// use reinhardt::pages::server_fn::ServerFnRouterExt;
	/// use crate::server_fn::login;
	///
	/// let router = ServerRouter::new()
	///     .server_fn(login);
	/// ```
	fn server_fn<S: ServerFnRegistration + 'static>(self, marker: S) -> Self;
}

impl ServerFnRouterExt for ServerRouter {
	fn server_fn<S: ServerFnRegistration + 'static>(self, _marker: S) -> Self {
		self.endpoint(|| ServerFnEndpoint::<S>(PhantomData))
	}
}

struct ServerFnEndpoint<S>(PhantomData<S>);

fn response_content_type(codec: &str) -> HeaderValue {
	match codec {
		"msgpack" => HeaderValue::from_static("application/msgpack"),
		_ => HeaderValue::from_static("application/json"),
	}
}

impl<S: ServerFnRegistration> EndpointInfo for ServerFnEndpoint<S> {
	fn path() -> &'static str {
		S::PATH
	}

	fn method() -> Method {
		Method::POST
	}

	fn name() -> &'static str {
		S::NAME
	}
}

#[async_trait::async_trait]
impl<S: ServerFnRegistration> Handler for ServerFnEndpoint<S> {
	async fn handle(&self, req: Request) -> Result<Response> {
		// Insert a shared cookie jar only for handlers that can access request
		// extensions. Plain body-only server functions cannot set response cookies.
		let cookie_jar = if S::USES_RESPONSE_COOKIE_JAR {
			let jar = SharedResponseCookies::new();
			req.extensions.insert(jar.clone());
			Some(jar)
		} else {
			None
		};

		let mut response = match S::handle(req).await {
			Ok(body) => Response::ok()
				.with_typed_header(CONTENT_TYPE, response_content_type(S::CODEC))
				.with_body(body),
			Err(error_body) => {
				let name = S::NAME;
				let path = S::PATH;
				// Log the error to stderr for debugging.
				eprintln!(
					"[server_fn ERROR] {} ({}): {}",
					name,
					path,
					String::from_utf8_lossy(&error_body)
				);

				// Extract status code from ServerFnError if possible.
				let status_code = serde_json::from_slice::<ServerFnError>(&error_body)
					.ok()
					.map(|err| match err {
						ServerFnError::Server { status, .. } => StatusCode::from_u16(status)
							.unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
						_ => StatusCode::INTERNAL_SERVER_ERROR,
					})
					.unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);

				Response::new(status_code)
					.with_typed_header(CONTENT_TYPE, response_content_type(S::CODEC))
					.with_body(error_body)
			}
		};

		// Apply response cookies from the shared cookie jar.
		if let Some(cookie_jar) = cookie_jar {
			let cookies = cookie_jar.take();
			for cookie in cookies.cookies() {
				response = response.append_header("Set-Cookie", cookie);
			}
		}

		Ok(response)
	}
}
