//! WebSocket routing primitives shared across reinhardt crates.
//!
//! This module provides foundational WebSocket types used by both
//! `reinhardt-websockets` (connection handling) and `reinhardt-urls`
//! (`UnifiedRouter::websocket()` builder). Placing them here avoids a
//! circular dependency between those two crates.

use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;
use tokio::sync::RwLock;

// ── Endpoint metadata ─────────────────────────────────────────────────────

/// Opaque key identifying the consumer selected for a WebSocket route.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct WebSocketConsumerKey(&'static str);

impl WebSocketConsumerKey {
	/// Creates a key from a stable consumer identifier.
	pub const fn new(value: &'static str) -> Self {
		Self(value)
	}

	/// Creates a key from a consumer type.
	pub fn of<T: ?Sized + 'static>() -> Self {
		Self(std::any::type_name::<T>())
	}

	/// Returns the stable consumer identifier.
	pub const fn as_str(self) -> &'static str {
		self.0
	}
}

/// Compile-time WebSocket endpoint metadata.
///
/// Implemented on the consumer struct generated by `#[websocket]`.
/// Parallel to `EndpointInfo` for HTTP views.
pub trait WebSocketEndpointInfo {
	/// Returns the URL path pattern for this WebSocket endpoint.
	fn path() -> &'static str;
	/// Returns the optional route name for this WebSocket endpoint.
	fn name() -> Option<&'static str>;
	/// Returns the opaque key for this endpoint's consumer.
	fn consumer_key() -> WebSocketConsumerKey
	where
		Self: Sized + 'static,
	{
		WebSocketConsumerKey::of::<Self>()
	}
}

/// Inventory metadata submitted by `#[websocket]` at compile time.
///
/// Used by `UrlReverser` to resolve WebSocket route names.
pub struct WebSocketEndpointMetadata {
	/// URL path pattern (e.g. `"/ws/chat/{room_id}/"`).
	pub path: &'static str,
	/// Route name used for URL reversal.
	pub name: &'static str,
	/// Handler function name for diagnostics.
	pub fn_name: &'static str,
	/// Rust module path of the handler for diagnostics.
	pub module_path: &'static str,
}

inventory::collect!(WebSocketEndpointMetadata);

/// Substitute path parameters in a WebSocket URL pattern.
///
/// `"/ws/chat/{room_id}/"` + `[("room_id", "42")]` → `"/ws/chat/42/"`
pub fn substitute_ws_params(path: &str, params: &[(&str, &str)]) -> String {
	let mut result = path.to_string();
	for (name, value) in params {
		result = result.replace(&format!("{{{}}}", name), value);
	}
	result
}

// ── Routing types ─────────────────────────────────────────────────────────

/// Routing result type
pub type RouteResult = Result<(), RouteError>;

/// Routing errors for WebSocket routes
#[derive(Debug, thiserror::Error)]
pub enum RouteError {
	/// No route registered for the given path.
	#[error("Route not found: {0}")]
	NotFound(String),
	/// A route with the given path is already registered.
	#[error("Route already exists: {0}")]
	AlreadyExists(String),
	/// The provided route pattern is syntactically invalid.
	#[error("Invalid route pattern: {0}")]
	InvalidPattern(String),
}

/// A registered WebSocket route (path + optional name + metadata).
#[derive(Clone)]
pub struct WebSocketRoute {
	path: String,
	name: Option<String>,
	consumer_key: WebSocketConsumerKey,
	metadata: HashMap<String, String>,
}

impl fmt::Debug for WebSocketRoute {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		formatter
			.debug_struct("WebSocketRoute")
			.field("path", &self.path)
			.field("name", &self.name)
			.field("consumer_key", &self.consumer_key)
			.field("metadata", &self.metadata)
			.finish()
	}
}

impl WebSocketRoute {
	/// Creates a new route with the given path and optional name.
	pub fn new(path: String, name: Option<String>) -> Self {
		Self {
			path,
			name,
			consumer_key: WebSocketConsumerKey::new(""),
			metadata: HashMap::new(),
		}
	}

	/// Returns the URL path pattern for this route.
	pub fn path(&self) -> &str {
		&self.path
	}

	/// Returns the optional name for this route.
	pub fn name(&self) -> Option<&str> {
		self.name.as_deref()
	}

	/// Returns the consumer key selected for this route.
	pub fn consumer_key(&self) -> WebSocketConsumerKey {
		self.consumer_key
	}

	fn with_consumer_key(mut self, consumer_key: WebSocketConsumerKey) -> Self {
		self.consumer_key = consumer_key;
		self
	}

	/// Attaches a key-value metadata entry to this route.
	pub fn with_metadata(mut self, key: String, value: String) -> Self {
		self.metadata.insert(key, value);
		self
	}

	/// Returns the metadata value for the given key, if present.
	pub fn get_metadata(&self, key: &str) -> Option<&String> {
		self.metadata.get(key)
	}
}

// ── WebSocketRouter ───────────────────────────────────────────────────────

/// WebSocket router: build-time registration + runtime lookup.
///
/// The build-time API (`consumer()`, `reverse()`, `find_pending()`) is used
/// by `UnifiedRouter::websocket()` and WebSocket route declarations.
/// The async API (`register_route()`, `find_route()`, etc.) is used at
/// connection-handling time in `reinhardt-websockets`.
#[derive(Clone)]
pub struct WebSocketRouter {
	routes: Arc<RwLock<HashMap<String, WebSocketRoute>>>,
	names: Arc<RwLock<HashMap<String, String>>>,
	/// Build-time consumer registrations (added by `consumer()` builder).
	pending_consumers: Vec<WebSocketRoute>,
	/// Optional namespace (app label) for this router.
	namespace: Option<String>,
}

impl WebSocketRouter {
	/// Creates a new empty router.
	pub fn new() -> Self {
		Self {
			routes: Arc::new(RwLock::new(HashMap::new())),
			names: Arc::new(RwLock::new(HashMap::new())),
			pending_consumers: Vec::new(),
			namespace: None,
		}
	}

	/// Set the namespace for this router.
	///
	/// Parallel to `ServerRouter::with_namespace`.
	/// WebSocket route paths are not rewritten; named routes are prefixed
	/// with the namespace.
	pub fn with_namespace(mut self, namespace: impl Into<String>) -> Self {
		let namespace = namespace.into();
		for route in &mut self.pending_consumers {
			if let Some(name) = route.name.take() {
				route.name = Some(format!("{namespace}:{name}"));
			}
		}
		self.namespace = Some(namespace);
		self
	}

	/// Returns the namespace set via [`with_namespace`], if any.
	///
	/// [`with_namespace`]: Self::with_namespace
	pub fn namespace(&self) -> Option<&str> {
		self.namespace.as_deref()
	}

	/// Select an inventory-registered WebSocket consumer by its constructor shape.
	///
	/// The closure is type-checked but not executed. Consumers must be generated by
	/// `#[websocket]`, which supplies the runtime factory through inventory.
	pub fn consumer<C, F>(mut self, selector: F) -> Self
	where
		F: Fn() -> C + Send + Sync + 'static,
		C: WebSocketEndpointInfo + Send + Sync + 'static,
	{
		let name = C::name().map(|name| match self.namespace.as_deref() {
			Some(namespace) => format!("{namespace}:{name}"),
			None => name.to_string(),
		});
		drop(selector);
		self.pending_consumers.push(
			WebSocketRoute::new(C::path().to_string(), name).with_consumer_key(C::consumer_key()),
		);
		self
	}

	/// Appends `child`'s structural routes after this router's routes.
	pub fn merge(mut self, child: Self) -> Self {
		let mut child = child;
		if let Some(namespace) = self.namespace.as_deref() {
			for route in &mut child.pending_consumers {
				if let Some(name) = route.name.take() {
					route.name = Some(format!("{namespace}:{name}"));
				}
			}
		}
		self.pending_consumers.extend(child.pending_consumers);
		self
	}

	/// Appends `child`'s structural routes below `prefix`.
	pub fn mount(self, prefix: &str, mut child: Self) -> Self {
		for route in &mut child.pending_consumers {
			route.path = join_ws_paths(prefix, &route.path);
		}
		self.merge(child)
	}

	/// Returns `true` when no structural consumers have been registered.
	pub fn is_empty(&self) -> bool {
		self.pending_consumers.is_empty()
	}

	/// Returns the number of structural consumer routes.
	pub fn len(&self) -> usize {
		self.pending_consumers.len()
	}

	/// Returns the structural consumer routes in registration order.
	#[doc(hidden)]
	pub fn routes(&self) -> &[WebSocketRoute] {
		&self.pending_consumers
	}

	/// Find a pending consumer route by name.
	pub fn find_pending(&self, name: &str) -> Option<&WebSocketRoute> {
		self.pending_consumers
			.iter()
			.find(|r| r.name() == Some(name))
	}

	/// Resolve a WebSocket URL by route name, substituting path parameters.
	pub fn reverse(&self, name: &str, params: &[(&str, &str)]) -> Option<String> {
		self.pending_consumers
			.iter()
			.find(|r| r.name() == Some(name))
			.map(|r| substitute_ws_params(r.path(), params))
	}

	/// Register a route at runtime (async, used by the connection handler).
	pub async fn register_route(&mut self, route: WebSocketRoute) -> RouteResult {
		let mut routes = self.routes.write().await;
		if routes.contains_key(&route.path) {
			return Err(RouteError::AlreadyExists(route.path.clone()));
		}
		if let Some(name) = &route.name {
			let mut names = self.names.write().await;
			names.insert(name.clone(), route.path.clone());
		}
		routes.insert(route.path.clone(), route);
		Ok(())
	}

	/// Looks up a registered route by its exact path.
	pub async fn find_route(&self, path: &str) -> Option<WebSocketRoute> {
		let routes = self.routes.read().await;
		routes.get(path).cloned()
	}

	/// Looks up a registered route by its name.
	pub async fn find_route_by_name(&self, name: &str) -> Option<WebSocketRoute> {
		let names = self.names.read().await;
		if let Some(path) = names.get(name) {
			let routes = self.routes.read().await;
			routes.get(path).cloned()
		} else {
			None
		}
	}

	/// Removes the registered route for the given path.
	pub async fn remove_route(&mut self, path: &str) -> RouteResult {
		let mut routes = self.routes.write().await;
		let route = routes
			.remove(path)
			.ok_or_else(|| RouteError::NotFound(path.to_string()))?;
		if let Some(name) = &route.name {
			let mut names = self.names.write().await;
			names.remove(name);
		}
		Ok(())
	}

	/// Returns all currently registered routes.
	pub async fn all_routes(&self) -> Vec<WebSocketRoute> {
		let routes = self.routes.read().await;
		routes.values().cloned().collect()
	}

	/// Returns `true` if a route is registered for the given path.
	pub async fn has_route(&self, path: &str) -> bool {
		self.routes.read().await.contains_key(path)
	}

	/// Returns the number of currently registered routes.
	pub async fn route_count(&self) -> usize {
		self.routes.read().await.len()
	}

	/// Removes all registered routes and name mappings.
	pub async fn clear(&mut self) {
		self.routes.write().await.clear();
		self.names.write().await.clear();
	}
}

fn join_ws_paths(prefix: &str, path: &str) -> String {
	match (prefix.ends_with('/'), path.starts_with('/')) {
		(true, true) => format!("{prefix}{}", &path[1..]),
		(false, false) => format!("{prefix}/{path}"),
		_ => format!("{prefix}{path}"),
	}
}

impl Default for WebSocketRouter {
	fn default() -> Self {
		Self::new()
	}
}

// ── Global registry ───────────────────────────────────────────────────────

static GLOBAL_ROUTER: once_cell::sync::Lazy<Arc<RwLock<Option<WebSocketRouter>>>> =
	once_cell::sync::Lazy::new(|| Arc::new(RwLock::new(None)));

/// Installs `router` as the process-wide WebSocket router.
pub async fn register_websocket_router(router: WebSocketRouter) {
	*GLOBAL_ROUTER.write().await = Some(router);
}

/// Returns a clone of the current process-wide WebSocket router, if set.
pub async fn get_websocket_router() -> Option<WebSocketRouter> {
	GLOBAL_ROUTER.read().await.clone()
}

/// Clears the process-wide WebSocket router (primarily for tests).
pub async fn clear_websocket_router() {
	*GLOBAL_ROUTER.write().await = None;
}

/// Resolves a registered or pending WebSocket URL by route name.
pub async fn reverse_websocket_url(router: &WebSocketRouter, name: &str) -> Option<String> {
	let names = router.names.read().await;
	if let Some(path) = names.get(name) {
		let routes = router.routes.read().await;
		routes.get(path).map(|r| r.path().to_string())
	} else {
		router.find_pending(name).map(|r| r.path().to_string())
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use rstest::rstest;

	struct TestConsumer;
	impl WebSocketEndpointInfo for TestConsumer {
		fn path() -> &'static str {
			"/ws/chat/{room_id}/"
		}
		fn name() -> Option<&'static str> {
			Some("chat_ws")
		}
	}

	struct RoomConsumer;
	impl WebSocketEndpointInfo for RoomConsumer {
		fn path() -> &'static str {
			"/rooms/{room_id}/"
		}

		fn name() -> Option<&'static str> {
			Some("room")
		}
	}

	struct NotificationConsumer;
	impl WebSocketEndpointInfo for NotificationConsumer {
		fn path() -> &'static str {
			"/notifications/"
		}

		fn name() -> Option<&'static str> {
			Some("notification")
		}
	}

	struct RelativeRoomConsumer;
	impl WebSocketEndpointInfo for RelativeRoomConsumer {
		fn path() -> &'static str {
			"rooms/{room_id}/"
		}

		fn name() -> Option<&'static str> {
			Some("room")
		}
	}

	struct GeneratedConsumer;

	#[rstest]
	fn test_substitute_no_params() {
		assert_eq!(substitute_ws_params("/ws/notif/", &[]), "/ws/notif/");
	}

	#[rstest]
	fn test_substitute_one_param() {
		assert_eq!(
			substitute_ws_params("/ws/chat/{room_id}/", &[("room_id", "42")]),
			"/ws/chat/42/"
		);
	}

	#[rstest]
	fn test_consumer_builder() {
		let router = WebSocketRouter::new().consumer(|| TestConsumer);
		let route = router.find_pending("chat_ws");
		assert!(route.is_some());
		assert_eq!(route.unwrap().path(), "/ws/chat/{room_id}/");
	}

	#[rstest]
	fn test_consumer_retains_endpoint_key() {
		let router = WebSocketRouter::new().consumer(|| RoomConsumer);
		assert_eq!(
			router.routes()[0].consumer_key(),
			RoomConsumer::consumer_key()
		);
	}

	#[rstest]
	#[rstest]
	fn test_generated_consumer_key_matches_macro_shape() {
		assert_eq!(
			WebSocketConsumerKey::of::<GeneratedConsumer>(),
			WebSocketConsumerKey::new(concat!(module_path!(), "::GeneratedConsumer"))
		);
	}

	#[rstest]
	fn test_merge_preserves_route_order() {
		let router = WebSocketRouter::new()
			.consumer(|| RoomConsumer)
			.merge(WebSocketRouter::new().consumer(|| NotificationConsumer));
		assert_eq!(router.len(), 2);
		assert_eq!(router.routes()[0].name(), Some("room"));
		assert_eq!(router.routes()[1].name(), Some("notification"));
	}

	#[rstest]
	fn test_empty_router_has_no_pending_consumers() {
		let router = WebSocketRouter::new();
		assert!(router.is_empty());
		assert_eq!(router.len(), 0);
	}

	#[rstest(
		prefix,
		child_path,
		expected,
		case("/ws/", "/rooms/{room_id}/", "/ws/rooms/{room_id}/"),
		case("/ws", "/rooms/{room_id}/", "/ws/rooms/{room_id}/"),
		case("/ws/", "rooms/{room_id}/", "/ws/rooms/{room_id}/"),
		case("/ws", "rooms/{room_id}/", "/ws/rooms/{room_id}/")
	)]
	fn test_mount_normalizes_one_boundary_slash(prefix: &str, child_path: &str, expected: &str) {
		let child = if child_path.starts_with('/') {
			WebSocketRouter::new().consumer(|| RoomConsumer)
		} else {
			WebSocketRouter::new().consumer(|| RelativeRoomConsumer)
		};
		assert_eq!(child.routes()[0].path(), child_path);
		let mounted = WebSocketRouter::new().mount(prefix, child);
		assert_eq!(mounted.routes()[0].path(), expected);
	}

	#[rstest]
	fn test_with_namespace_rewrites_collected_route_names() {
		let namespaced = WebSocketRouter::new()
			.consumer(|| RoomConsumer)
			.with_namespace("chat");
		assert_eq!(namespaced.routes()[0].name(), Some("chat:room"));
		assert!(namespaced.find_pending("room").is_none());
		assert!(namespaced.find_pending("chat:room").is_some());
	}

	#[tokio::test]
	async fn test_legacy_registered_route_lookup() {
		let mut router = WebSocketRouter::new();
		router
			.register_route(WebSocketRoute::new(
				"/ws/legacy/".to_string(),
				Some("legacy".to_string()),
			))
			.await
			.unwrap();
		assert_eq!(
			router.find_route("/ws/legacy/").await.unwrap().name(),
			Some("legacy")
		);
		assert_eq!(
			reverse_websocket_url(&router, "legacy").await,
			Some("/ws/legacy/".to_string())
		);
	}

	#[rstest]
	fn test_with_namespace_stores_value_without_rewriting_paths() {
		let router = WebSocketRouter::new()
			.with_namespace("auth")
			.consumer(|| TestConsumer);
		assert_eq!(router.namespace(), Some("auth"));
		assert_eq!(
			router.find_pending("auth:chat_ws").unwrap().path(),
			"/ws/chat/{room_id}/"
		);
	}

	#[rstest]
	fn test_reverse() {
		let router = WebSocketRouter::new().consumer(|| TestConsumer);
		assert_eq!(
			router.reverse("chat_ws", &[("room_id", "99")]),
			Some("/ws/chat/99/".to_string())
		);
		assert_eq!(router.reverse("unknown", &[]), None);
	}
}
