use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration {
		app_label: "auth".to_string(),
		name: "0001_initial".to_string(),
		operations: vec![
			Operation::CreateTable {
				name: "auth_password_reset_token".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: FieldType::TimestampTz,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "expires_at".to_string(),
						type_definition: FieldType::TimestampTz,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "is_used".to_string(),
						type_definition: FieldType::Boolean,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "token".to_string(),
						type_definition: FieldType::VarChar(255u32),
						not_null: false,
						unique: true,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![Constraint::Unique {
					name: "auth_passwordresettoken_token_uniq".to_string(),
					columns: vec!["token".to_string()],
				}],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "auth_user".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "bio".to_string(),
						type_definition: FieldType::VarChar(500u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: FieldType::TimestampTz,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "email".to_string(),
						type_definition: FieldType::VarChar(255u32),
						not_null: false,
						unique: true,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "is_active".to_string(),
						type_definition: FieldType::Boolean,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "last_login".to_string(),
						type_definition: FieldType::TimestampTz,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "password_hash".to_string(),
						type_definition: FieldType::VarChar(255u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "username".to_string(),
						type_definition: FieldType::VarChar(150u32),
						not_null: false,
						unique: true,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::Unique {
						name: "auth_user_username_uniq".to_string(),
						columns: vec!["username".to_string()],
					},
					Constraint::Unique {
						name: "auth_user_email_uniq".to_string(),
						columns: vec!["email".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "auth_user_blocked_users".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "from_user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "to_user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_auth_user_blocked_users_from_user_id".to_string(),
						columns: vec!["from_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_auth_user_blocked_users_to_user_id".to_string(),
						columns: vec!["to_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "auth_user_blocked_users_unique".to_string(),
						columns: vec!["from_user_id".to_string(), "to_user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "auth_user_following".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "from_user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "to_user_id".to_string(),
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_auth_user_following_from_user_id".to_string(),
						columns: vec!["from_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_auth_user_following_to_user_id".to_string(),
						columns: vec!["to_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "auth_user_following_unique".to_string(),
						columns: vec!["from_user_id".to_string(), "to_user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
		..Default::default()
	}
}
