//! Views for todos app
//!
//! CRUD operations for TODO items

use reinhardt::{Request, Response, StatusCode, ViewResult, endpoint};
use reinhardt::db::orm::Manager;
use crate::apps::todos::models::Todo;
use chrono::Utc;
use std::sync::Arc;

/// List all todos
///
/// # Example Response
/// ```json
/// {
///   "count": 2,
///   "results": [
///     {
///       "id": 1,
///       "title": "Buy groceries",
///       "description": "Milk, eggs, bread",
///       "completed": false,
///       "created_at": "2025-01-01T00:00:00Z",
///       "updated_at": "2025-01-01T00:00:00Z"
///     }
///   ]
/// }
/// ```
#[endpoint]
pub async fn list_todos(
	_req: Request,
	#[inject] _db: Arc<reinhardt::db::DatabaseConnection>,
) -> ViewResult<Response> {
	// Query all todos from database using ORM
	let manager = Manager::<Todo>::new();
	let todos = manager.all().all().await?;

	let response = serde_json::json!({
		"count": todos.len(),
		"results": todos
	});

	let body = serde_json::to_vec(&response)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Create a new todo
///
/// # Request Body
/// ```json
/// {
///   "title": "Buy groceries",
///   "description": "Milk, eggs, bread",
///   "completed": false
/// }
/// ```
#[endpoint]
pub async fn create_todo(
	mut req: Request,
	#[inject] _db: Arc<reinhardt::db::DatabaseConnection>,
) -> ViewResult<Response> {
	// Parse request body
	let body_bytes = req.body();
	let todo_data: serde_json::Value = serde_json::from_slice(body_bytes)?;

	// Validate required fields
	let title = todo_data
		.get("title")
		.and_then(|v| v.as_str())
		.ok_or("Missing required field: title")?;

	if title.len() < 1 || title.len() > 255 {
		return Err("Title must be between 1 and 255 characters".into());
	}

	// Create new todo using ORM
	let now = Utc::now();
	let todo = Todo {
		id: 0, // Will be auto-generated by database
		title: title.to_string(),
		description: todo_data
			.get("description")
			.and_then(|v| v.as_str())
			.map(String::from),
		completed: todo_data
			.get("completed")
			.and_then(|v| v.as_bool())
			.unwrap_or(false),
		created_at: now,
		updated_at: now,
	};

	let manager = Manager::<Todo>::new();
	let created_todo = manager.create(&todo).await?;

	let body = serde_json::to_vec(&created_todo)?;
	Ok(Response::new(StatusCode::CREATED).with_body(body))
}

/// Get a specific todo by ID
///
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
#[endpoint]
pub async fn get_todo(
	req: Request,
	#[inject] _db: Arc<reinhardt::db::DatabaseConnection>,
) -> ViewResult<Response> {
	// Extract ID from path parameters
	let id = req
		.path_params
		.get("id")
		.ok_or("Missing path parameter: id")?
		.parse::<i64>()
		.map_err(|_| "Invalid ID format")?;

	// Get todo from database using ORM
	let manager = Manager::<Todo>::new();
	let todo = manager
		.get(id)
		.first()
		.await?
		.ok_or_else(|| format!("Todo with id {} not found", id))?;

	let body = serde_json::to_vec(&todo)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Update a todo
///
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
///
/// # Request Body
/// ```json
/// {
///   "title": "Updated title",
///   "description": "Updated description",
///   "completed": true
/// }
/// ```
#[endpoint]
pub async fn update_todo(
	mut req: Request,
	#[inject] _db: Arc<reinhardt::db::DatabaseConnection>,
) -> ViewResult<Response> {
	// Extract ID from path parameters
	let id = req
		.path_params
		.get("id")
		.ok_or("Missing path parameter: id")?
		.parse::<i64>()
		.map_err(|_| "Invalid ID format")?;

	// Parse request body
	let body_bytes = req.body();
	let update_data: serde_json::Value = serde_json::from_slice(body_bytes)?;

	// Get existing todo from database
	let manager = Manager::<Todo>::new();
	let mut todo = manager
		.get(id)
		.first()
		.await?
		.ok_or_else(|| format!("Todo with id {} not found", id))?;

	// Apply partial updates
	if let Some(title) = update_data.get("title").and_then(|v| v.as_str()) {
		if title.len() < 1 || title.len() > 255 {
			return Err("Title must be between 1 and 255 characters".into());
		}
		todo.title = title.to_string();
	}
	if let Some(description) = update_data.get("description") {
		todo.description = description.as_str().map(String::from);
	}
	if let Some(completed) = update_data.get("completed").and_then(|v| v.as_bool()) {
		todo.completed = completed;
	}
	todo.updated_at = Utc::now();

	// Save updated todo
	let updated_todo = manager.update(&todo).await?;

	let body = serde_json::to_vec(&updated_todo)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Delete a todo
///
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
///
/// # Response
/// Returns 204 No Content on success
#[endpoint]
pub async fn delete_todo(
	req: Request,
	#[inject] _db: Arc<reinhardt::db::DatabaseConnection>,
) -> ViewResult<Response> {
	// Extract ID from path parameters
	let id = req
		.path_params
		.get("id")
		.ok_or("Missing path parameter: id")?
		.parse::<i64>()
		.map_err(|_| "Invalid ID format")?;

	// Delete todo from database using ORM
	let manager = Manager::<Todo>::new();
	manager
		.delete(id)
		.await
		.map_err(|_| format!("Todo with id {} not found", id))?;

	Ok(Response::new(StatusCode::NO_CONTENT))
}
