//! Views for todos app
//!
//! CRUD operations for TODO items

use reinhardt::{delete, get, post, put};
use reinhardt::{Json, Path, Request, Response, StatusCode, ViewResult};
use reinhardt::core::serde::json;
use reinhardt::db::orm::Manager;
use crate::apps::todos::models::Todo;
use chrono::Utc;
use serde::Deserialize;


/// Request body for creating/updating todos
#[derive(Debug, Deserialize)]
pub struct TodoRequest {
	pub title: String,
	pub description: Option<String>,
	pub completed: Option<bool>,
}

/// List all todos
///
/// GET /todos/
/// Success response: 200 OK with array of todos
/// # Example Response
/// ```json
/// {
///   "count": 2,
///   "results": [
///     {
///       "id": 1,
///       "title": "Buy groceries",
///       "description": "Milk, eggs, bread",
///       "completed": false,
///       "created_at": "2025-01-01T00:00:00Z",
///       "updated_at": "2025-01-01T00:00:00Z"
///     }
///   ]
/// }
/// ```
#[get("/todos/")]
pub async fn list_todos(_req: Request) -> ViewResult<Response> {
	// Query all todos from database using ORM
	let manager = Manager::<Todo>::new();
	let todos = manager.all().all().await?;

	let response = json::json!({
		"count": todos.len(),
		"results": todos
	});

	let body = json::to_vec(&response)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Create a new todo
///
/// POST /todos/
/// Request body: JSON with title, description, completed fields
/// Success response: 201 Created with created todo
/// Error responses:
/// - 422 Unprocessable Entity: Validation errors
/// # Request Body
/// ```json
/// {
///   "title": "Buy groceries",
///   "description": "Milk, eggs, bread",
///   "completed": false
/// }
/// ```
#[post("/todos/")]
pub async fn create_todo(Json(todo_req): Json<TodoRequest>) -> ViewResult<Response> {
	// Validate required fields
	if todo_req.title.len() < 1 || todo_req.title.len() > 255 {
		return Err("Title must be between 1 and 255 characters".into());
	}

	// Create new todo using ORM
	let now = Utc::now();
	let todo = Todo {
		id: None, // Will be auto-generated by database
		title: todo_req.title,
		description: todo_req.description,
		completed: todo_req.completed.unwrap_or(false),
		created_at: now,
		updated_at: now,
	};

	let manager = Manager::<Todo>::new();
	let created_todo = manager.create(&todo).await?;

	let body = json::to_vec(&created_todo)?;
	Ok(Response::new(StatusCode::CREATED).with_body(body))
}

/// Get a specific todo by ID
///
/// GET /todos/{id}/
/// Success response: 200 OK with todo data
/// Error responses:
/// - 404 Not Found: Todo not found
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
#[get("/todos/{id}/")]
pub async fn get_todo(Path(id): Path<i64>) -> ViewResult<Response> {
	// Get todo from database using ORM
	let manager = Manager::<Todo>::new();
	let todo = manager
		.get(id)
		.first()
		.await?
		.ok_or_else(|| format!("Todo with id {} not found", id))?;

	let body = json::to_vec(&todo)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Update a todo
///
/// PUT /todos/{id}/
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
///
/// # Request Body
/// ```json
/// {
///   "title": "Updated title",
///   "description": "Updated description",
///   "completed": true
/// }
/// ```
#[put("/todos/{id}/")]
pub async fn update_todo(
	Path(id): Path<i64>,
	Json(todo_req): Json<TodoRequest>,
) -> ViewResult<Response> {
	// Validate required fields
	if todo_req.title.len() < 1 || todo_req.title.len() > 255 {
		return Err("Title must be between 1 and 255 characters".into());
	}

	// Get existing todo from database
	let manager = Manager::<Todo>::new();
	let mut todo = manager
		.get(id)
		.first()
		.await?
		.ok_or_else(|| format!("Todo with id {} not found", id))?;

	// Apply updates
	todo.title = todo_req.title;
	todo.description = todo_req.description;
	todo.completed = todo_req.completed.unwrap_or(todo.completed);
	todo.updated_at = Utc::now();

	// Save updated todo
	let updated_todo = manager.update(&todo).await?;

	let body = json::to_vec(&updated_todo)?;
	Ok(Response::new(StatusCode::OK).with_body(body))
}

/// Delete a todo
///
/// DELETE /todos/{id}/
/// # Path Parameters
/// - `id`: Todo ID (e.g., `/todos/1`)
///
/// # Response
/// Returns 204 No Content on success
#[delete("/todos/{id}/")]
pub async fn delete_todo(Path(id): Path<i64>) -> ViewResult<Response> {
	// Delete todo from database using ORM
	let manager = Manager::<Todo>::new();
	manager
		.delete(id)
		.await
		.map_err(|_| format!("Todo with id {} not found", id))?;

	Ok(Response::new(StatusCode::NO_CONTENT))
}
