use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "auth",
		name: "0001_initial",
		operations: vec![
			Operation::AddColumn {
				table: "auth_user",
				column: ColumnDefinition {
					name: "bio",
					type_definition: FieldType::VarChar(500u32),
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "created_at",
				new_definition: ColumnDefinition {
					name: "created_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "expires_at",
				new_definition: ColumnDefinition {
					name: "expires_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "id",
				new_definition: ColumnDefinition {
					name: "id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "is_used",
				new_definition: ColumnDefinition {
					name: "is_used",
					type_definition: FieldType::Boolean,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "token",
				new_definition: ColumnDefinition {
					name: "token",
					type_definition: FieldType::VarChar(255u32),
					not_null: false,
					unique: true,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_password_reset_token",
				column: "user_id",
				new_definition: ColumnDefinition {
					name: "user_id",
					type_definition: FieldType::Uuid,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "created_at",
				new_definition: ColumnDefinition {
					name: "created_at",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "email",
				new_definition: ColumnDefinition {
					name: "email",
					type_definition: FieldType::VarChar(255u32),
					not_null: false,
					unique: true,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "id",
				new_definition: ColumnDefinition {
					name: "id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "is_active",
				new_definition: ColumnDefinition {
					name: "is_active",
					type_definition: FieldType::Boolean,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "last_login",
				new_definition: ColumnDefinition {
					name: "last_login",
					type_definition: FieldType::DateTime,
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "password_hash",
				new_definition: ColumnDefinition {
					name: "password_hash",
					type_definition: FieldType::VarChar(255u32),
					not_null: false,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user",
				column: "username",
				new_definition: ColumnDefinition {
					name: "username",
					type_definition: FieldType::VarChar(150u32),
					not_null: false,
					unique: true,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user_blocked_users",
				column: "from_user_id",
				new_definition: ColumnDefinition {
					name: "from_user_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user_blocked_users",
				column: "to_user_id",
				new_definition: ColumnDefinition {
					name: "to_user_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user_following",
				column: "from_user_id",
				new_definition: ColumnDefinition {
					name: "from_user_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::AlterColumn {
				table: "auth_user_following",
				column: "to_user_id",
				new_definition: ColumnDefinition {
					name: "to_user_id",
					type_definition: FieldType::Uuid,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
				},
				mysql_options: None,
			},
			Operation::CreateTable {
				name: "auth_user_blocked_users",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "from_user_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "to_user_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_auth_user_blocked_users_from_user_id".to_string(),
						columns: vec!["from_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_auth_user_blocked_users_to_user_id".to_string(),
						columns: vec!["to_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "auth_user_blocked_users_unique".to_string(),
						columns: vec!["from_user_id".to_string(), "to_user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::CreateTable {
				name: "auth_user_following",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: FieldType::Integer,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: true,
						default: None,
					},
					ColumnDefinition {
						name: "from_user_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "to_user_id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![
					Constraint::ForeignKey {
						name: "fk_auth_user_following_from_user_id".to_string(),
						columns: vec!["from_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::ForeignKey {
						name: "fk_auth_user_following_to_user_id".to_string(),
						columns: vec!["to_user_id".to_string()],
						referenced_table: "auth_user".to_string(),
						referenced_columns: vec!["id".to_string()],
						on_delete: ForeignKeyAction::Cascade,
						on_update: ForeignKeyAction::Cascade,
						deferrable: None,
					},
					Constraint::Unique {
						name: "auth_user_following_unique".to_string(),
						columns: vec!["from_user_id".to_string(), "to_user_id".to_string()],
					},
				],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
