//! Typed relation traversal primitives for ORM queries.
//!
//! The types in this module describe relation paths generated by the model
//! macro. `QuerySet` consumes those paths to add deterministic SQL joins for
//! typed filters, `select_related`, and `prefetch_related` planning.

use std::borrow::Cow;
use std::collections::HashMap;
use std::marker::PhantomData;

use smallvec::SmallVec;

use crate::orm::Model;
use crate::orm::expressions::FieldRef;
use crate::orm::query::{Filter, FilterOperator, FilterValue, TypedFilter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
/// SQL join kind requested by a relation path.
pub enum RelationJoinKind {
	/// Use an inner join.
	Inner,
	/// Use a left outer join.
	Left,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
/// Number of target rows that one source row can reach through a relation hop.
pub enum RelationMultiplicity {
	/// Each source row reaches at most one target row.
	Single,
	/// Each source row can reach multiple target rows.
	Multiple,
}

impl RelationJoinKind {
	/// Merge two join requirements, preserving left joins when either side needs one.
	pub const fn merge(self, other: Self) -> Self {
		match (self, other) {
			(Self::Left, _) | (_, Self::Left) => Self::Left,
			(Self::Inner, Self::Inner) => Self::Inner,
		}
	}
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
/// One hop in a typed relation path.
pub struct RelationStep {
	/// Local relation name used to derive stable joined-table aliases.
	pub name: Cow<'static, str>,
	/// Source table for this hop.
	pub source_table: Cow<'static, str>,
	/// Target table for this hop.
	pub target_table: Cow<'static, str>,
	/// Source column used in the join predicate.
	pub source_column: Cow<'static, str>,
	/// Target column used in the join predicate.
	pub target_column: Cow<'static, str>,
	/// Default join kind for this hop.
	pub default_join_kind: RelationJoinKind,
	/// Whether this hop can multiply root rows.
	pub multiplicity: RelationMultiplicity,
}

/// Static descriptor generated for a concrete model relation.
pub trait RelationDescriptor {
	/// Model where the relation starts.
	type Source: Model;
	/// Model reached by the relation.
	type Target: Model;

	/// Return the relation steps that connect `Source` to `Target`.
	fn steps() -> Vec<RelationStep>;
}

/// Model support for wrapping relation paths in generated typed accessors.
pub trait RelationTarget: Model {
	/// Generated path wrapper for this target model from a root model.
	type Path<Root: Model>: RelationPathLike<Root = Root, Target = Self>;

	/// Wrap a raw relation path in the generated target-specific path type.
	fn wrap_relation_path<Root: Model>(path: RelationPath<Root, Self>) -> Self::Path<Root>
	where
		Self: Sized;
}

/// Common interface implemented by raw and generated relation path types.
pub trait RelationPathLike {
	/// Root model where the path starts.
	type Root: Model;
	/// Target model reached by the path.
	type Target: Model;

	/// Relation steps in traversal order.
	fn steps(&self) -> &[RelationStep];
	/// Join kind requested by this path.
	fn join_kind(&self) -> RelationJoinKind;
	/// Whole-path join kind override, if the path explicitly requested one.
	fn join_kind_override(&self) -> Option<RelationJoinKind> {
		None
	}
	/// Alias of the final joined relation.
	fn leaf_alias(&self) -> &str;
	/// Return whether any hop can produce multiple target rows per source row.
	fn is_multi_valued(&self) -> bool {
		self.steps()
			.iter()
			.any(|step| step.multiplicity == RelationMultiplicity::Multiple)
	}
}

#[derive(Debug, Clone)]
/// Typed path from one model to a related model.
pub struct RelationPath<Root: Model, Target: Model> {
	steps: SmallVec<[RelationStep; 4]>,
	step_aliases: SmallVec<[String; 4]>,
	join_kind_override: Option<RelationJoinKind>,
	_phantom: PhantomData<(Root, Target)>,
}

impl<Root: Model, Target: Model> RelationPath<Root, Target> {
	/// Create a relation path from static relation steps.
	pub fn new(steps: &'static [RelationStep]) -> Self {
		let mut path_steps: SmallVec<[RelationStep; 4]> = SmallVec::new();
		path_steps.extend(steps.iter().cloned());
		Self::from_smallvec(path_steps)
	}

	/// Create a relation path from owned relation steps.
	pub fn from_owned_steps(steps: Vec<RelationStep>) -> Self {
		let path_steps: SmallVec<[RelationStep; 4]> = steps.into_iter().collect();
		Self::from_smallvec(path_steps)
	}

	fn from_smallvec(path_steps: SmallVec<[RelationStep; 4]>) -> Self {
		let step_aliases = step_aliases(&path_steps, Root::table_name());
		Self {
			steps: path_steps,
			step_aliases,
			join_kind_override: None,
			_phantom: PhantomData,
		}
	}

	/// Create a relation path from a generated descriptor.
	pub fn from_descriptor<D>() -> Self
	where
		D: RelationDescriptor<Source = Root, Target = Target>,
	{
		Self::from_owned_steps(D::steps())
	}

	/// Convert this raw path into the target model's generated typed wrapper.
	///
	/// Raw paths remain available for relations whose target is a manually
	/// implemented [`Model`]. Calling this method requires the target to provide
	/// a [`RelationTarget`] implementation, which `#[model]` generates
	/// automatically.
	pub fn into_typed(self) -> <Target as RelationTarget>::Path<Root>
	where
		Target: RelationTarget,
	{
		Target::wrap_relation_path(self)
	}

	/// Append another generated relation descriptor to this path.
	pub fn then<D, Next>(self) -> RelationPath<Root, Next>
	where
		D: RelationDescriptor<Source = Target, Target = Next>,
		Next: Model,
	{
		let mut steps = self.steps;
		steps.extend(D::steps());
		RelationPath {
			step_aliases: step_aliases(&steps, Root::table_name()),
			steps,
			join_kind_override: self.join_kind_override,
			_phantom: PhantomData,
		}
	}

	/// Force the path to use left joins.
	pub fn optional(mut self) -> Self {
		self.join_kind_override = Some(RelationJoinKind::Left);
		self
	}

	/// Select a field on the target model through this relation path.
	pub fn field<Value>(
		self,
		field: FieldRef<Target, Value>,
	) -> RelatedFieldRef<Root, Target, Value> {
		RelatedFieldRef::new(self, field.name())
	}
}

impl<Root: Model, Target: Model> RelationPathLike for RelationPath<Root, Target> {
	type Root = Root;
	type Target = Target;

	fn steps(&self) -> &[RelationStep] {
		&self.steps
	}

	fn join_kind(&self) -> RelationJoinKind {
		self.join_kind_override
			.unwrap_or_else(|| default_join_kind(&self.steps))
	}

	fn join_kind_override(&self) -> Option<RelationJoinKind> {
		self.join_kind_override
	}

	fn leaf_alias(&self) -> &str {
		self.step_aliases
			.last()
			.map(String::as_str)
			.unwrap_or_else(|| Target::table_name())
	}
}

#[derive(Debug, Clone, PartialEq, Eq)]
/// Planned SQL join derived from a relation path.
pub struct PlannedRelationJoin {
	/// Alias assigned to the joined table.
	pub alias: String,
	/// Local relation name for this hop.
	pub relation_name: String,
	/// Alias or table name of the previous relation hop.
	pub source_alias: String,
	/// Physical target table for the join.
	pub target_table: String,
	/// Source column used by the join predicate.
	pub source_column: String,
	/// Target column used by the join predicate.
	pub target_column: String,
	/// SQL join kind for this planned join.
	pub join_kind: RelationJoinKind,
	/// Whether this join can multiply root rows.
	pub multiplicity: RelationMultiplicity,
}

#[derive(Debug, Clone)]
/// Deduplicated join plan for typed relation paths in a query.
pub struct RelationJoinGraph {
	root_alias: String,
	joins: Vec<PlannedRelationJoin>,
}

impl RelationJoinGraph {
	/// Create an empty join graph with the provided root alias.
	pub fn new(root_alias: impl Into<String>) -> Self {
		Self {
			root_alias: root_alias.into(),
			joins: Vec::new(),
		}
	}

	/// Return a copy of this graph with a different root alias.
	pub fn with_root_alias(mut self, root_alias: impl Into<String>) -> Self {
		let root_alias = root_alias.into();
		if self.root_alias == root_alias {
			return self;
		}

		let previous_root_alias = std::mem::replace(&mut self.root_alias, root_alias);
		let mut aliases = HashMap::from([(previous_root_alias, self.root_alias.clone())]);
		for join in &mut self.joins {
			if let Some(source_alias) = aliases.get(&join.source_alias) {
				join.source_alias.clone_from(source_alias);
			}
			let alias = step_alias(&join.source_alias, &join.relation_name, &self.root_alias);
			let previous_alias = std::mem::replace(&mut join.alias, alias);
			aliases.insert(previous_alias, join.alias.clone());
		}
		self
	}

	/// Add all steps from a relation path to the graph.
	pub fn add_path<P>(&mut self, path: &P)
	where
		P: RelationPathLike,
	{
		self.add_steps_with_override(path.steps(), path.join_kind_override());
	}

	/// Add relation steps with an explicit join kind.
	pub fn add_steps(&mut self, steps: &[RelationStep], join_kind: RelationJoinKind) {
		self.add_steps_with_override(steps, Some(join_kind));
	}

	/// Add relation steps using per-hop defaults unless a whole-path override is supplied.
	pub fn add_steps_with_override(
		&mut self,
		steps: &[RelationStep],
		join_kind_override: Option<RelationJoinKind>,
	) {
		let mut source_alias = self.root_alias.clone();
		let mut force_downstream_left = false;
		for step in steps {
			let alias = step_alias(&source_alias, step.name.as_ref(), &self.root_alias);
			let requested_join_kind = if force_downstream_left {
				RelationJoinKind::Left
			} else {
				join_kind_override.unwrap_or(step.default_join_kind)
			};
			if let Some(existing_index) = self.joins.iter().position(|join| {
				join.source_alias == source_alias && join.relation_name == step.name.as_ref()
			}) {
				let existing = &mut self.joins[existing_index];
				let was_left = existing.join_kind == RelationJoinKind::Left;
				existing.join_kind = existing.join_kind.merge(requested_join_kind);
				let is_left = existing.join_kind == RelationJoinKind::Left;
				let existing_alias = existing.alias.clone();
				if !was_left && is_left {
					self.promote_descendants_to_left(&existing_alias);
				}
				force_downstream_left |= is_left;
				source_alias = existing_alias;
				continue;
			}

			self.joins.push(PlannedRelationJoin {
				alias: alias.clone(),
				relation_name: step.name.to_string(),
				source_alias,
				target_table: step.target_table.to_string(),
				source_column: step.source_column.to_string(),
				target_column: step.target_column.to_string(),
				join_kind: requested_join_kind,
				multiplicity: step.multiplicity,
			});
			force_downstream_left |= requested_join_kind == RelationJoinKind::Left;
			source_alias = alias;
		}
	}

	fn promote_descendants_to_left(&mut self, source_alias: &str) {
		let mut pending = vec![source_alias.to_string()];
		while let Some(parent_alias) = pending.pop() {
			for join in &mut self.joins {
				if join.source_alias == parent_alias {
					join.join_kind = RelationJoinKind::Left;
					pending.push(join.alias.clone());
				}
			}
		}
	}

	/// Return whether the graph has no planned joins.
	pub fn is_empty(&self) -> bool {
		self.joins.is_empty()
	}

	/// Return the planned joins in traversal order.
	pub fn joins(&self) -> &[PlannedRelationJoin] {
		&self.joins
	}

	/// Return whether any planned join can produce multiple rows per root row.
	pub fn has_multi_valued_join(&self) -> bool {
		self.joins
			.iter()
			.any(|join| join.multiplicity == RelationMultiplicity::Multiple)
	}
}

impl Default for RelationJoinGraph {
	fn default() -> Self {
		Self::new("")
	}
}

fn default_join_kind(steps: &[RelationStep]) -> RelationJoinKind {
	steps
		.iter()
		.map(|step| step.default_join_kind)
		.fold(RelationJoinKind::Inner, RelationJoinKind::merge)
}

fn step_alias(source_alias: &str, step_name: &str, root_alias: &str) -> String {
	if source_alias == root_alias {
		if step_name == root_alias {
			format!("{}__{}", root_alias, step_name)
		} else {
			step_name.to_string()
		}
	} else {
		format!("{}__{}", source_alias, step_name)
	}
}

pub(crate) fn step_aliases(steps: &[RelationStep], root_alias: &str) -> SmallVec<[String; 4]> {
	let mut aliases = SmallVec::new();
	let mut source_alias = String::new();
	for (index, step) in steps.iter().enumerate() {
		let alias = if index == 0 {
			step_alias(root_alias, step.name.as_ref(), root_alias)
		} else {
			step_alias(&source_alias, step.name.as_ref(), "")
		};
		source_alias = alias.clone();
		aliases.push(alias);
	}
	aliases
}

#[derive(Debug, Clone)]
/// Field reference reached through a typed relation path.
pub struct RelatedFieldRef<Root: Model, Target: Model, Value> {
	path: RelationPath<Root, Target>,
	field: &'static str,
	_phantom: PhantomData<Value>,
}

impl<Root: Model, Target: Model, Value> RelatedFieldRef<Root, Target, Value> {
	/// Create a related field reference from a path and target field name.
	pub fn new(path: RelationPath<Root, Target>, field: &'static str) -> Self {
		Self {
			path,
			field,
			_phantom: PhantomData,
		}
	}

	/// Return the target field name.
	pub fn name(&self) -> &'static str {
		self.field
	}

	/// Return the relation path for this field.
	pub fn path(&self) -> &RelationPath<Root, Target> {
		&self.path
	}

	fn filter(&self, operator: FilterOperator, value: FilterValue) -> TypedFilter<Root> {
		TypedFilter::new(Filter::related(self.field, operator, value, &self.path))
	}

	/// Build an equality filter for this related field.
	pub fn eq<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Eq, value.into())
	}

	/// Build an exact-match filter for this related field.
	pub fn exact<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.eq(value)
	}

	/// Build a case-insensitive exact-match filter for this related field.
	pub fn iexact<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IExact, value.into())
	}

	/// Build a not-equal filter for this related field.
	pub fn ne<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Ne, value.into())
	}

	/// Build a greater-than filter for this related field.
	pub fn gt<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Gt, value.into())
	}

	/// Build a greater-than-or-equal filter for this related field.
	pub fn gte<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Gte, value.into())
	}

	/// Build a less-than filter for this related field.
	pub fn lt<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Lt, value.into())
	}

	/// Build a less-than-or-equal filter for this related field.
	pub fn lte<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Lte, value.into())
	}

	/// Build a contains filter for this related field.
	pub fn contains<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Contains, value.into())
	}

	/// Build a case-insensitive contains filter for this related field.
	pub fn icontains<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IContains, value.into())
	}

	/// Build a starts-with filter for this related field.
	pub fn startswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::StartsWith, value.into())
	}

	/// Build a case-insensitive starts-with filter for this related field.
	pub fn istartswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IStartsWith, value.into())
	}

	/// Build an ends-with filter for this related field.
	pub fn endswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::EndsWith, value.into())
	}

	/// Build a case-insensitive ends-with filter for this related field.
	pub fn iendswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IEndsWith, value.into())
	}

	/// Build an `IS NULL` filter for this related field.
	pub fn is_null(&self) -> TypedFilter<Root> {
		self.filter(FilterOperator::IsNull, FilterValue::Null)
	}

	/// Build an `IS NOT NULL` filter for this related field.
	pub fn is_not_null(&self) -> TypedFilter<Root> {
		self.filter(FilterOperator::IsNotNull, FilterValue::Null)
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::orm::Model;
	use serde::{Deserialize, Serialize};

	#[derive(Clone, Serialize, Deserialize)]
	struct Document {
		id: Option<i64>,
	}

	#[derive(Clone, Serialize, Deserialize)]
	struct CorpusFile {
		id: Option<i64>,
	}

	#[derive(Clone, Serialize, Deserialize)]
	struct Project {
		id: Option<i64>,
	}

	#[derive(Clone)]
	struct EmptyFields;

	impl crate::orm::FieldSelector for EmptyFields {
		fn with_alias(self, _alias: &str) -> Self {
			self
		}
	}

	impl Model for Document {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"documents"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	impl Model for CorpusFile {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"corpus_files"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	impl Model for Project {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"projects"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	struct DocumentCorpusFile;

	impl RelationDescriptor for DocumentCorpusFile {
		type Source = Document;
		type Target = CorpusFile;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "corpus_file".into(),
				source_table: "documents".into(),
				target_table: "corpus_files".into(),
				source_column: "corpus_file_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct DocumentOptionalCorpusFile;

	impl RelationDescriptor for DocumentOptionalCorpusFile {
		type Source = Document;
		type Target = CorpusFile;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "optional_corpus_file".into(),
				source_table: "documents".into(),
				target_table: "corpus_files".into(),
				source_column: "corpus_file_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Left,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct CorpusFileProject;

	impl RelationDescriptor for CorpusFileProject {
		type Source = CorpusFile;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "project".into(),
				source_table: "corpus_files".into(),
				target_table: "projects".into(),
				source_column: "project_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Left,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct CorpusFileRequiredProject;

	impl RelationDescriptor for CorpusFileRequiredProject {
		type Source = CorpusFile;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "required_project".into(),
				source_table: "corpus_files".into(),
				target_table: "projects".into(),
				source_column: "project_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct ProjectNamedProjects;

	impl RelationDescriptor for ProjectNamedProjects {
		type Source = Project;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "projects".into(),
				source_table: "projects".into(),
				target_table: "projects".into(),
				source_column: "parent_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	impl RelationDescriptor for Project {
		type Source = Project;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "parent".into(),
				source_table: "projects".into(),
				target_table: "projects".into(),
				source_column: "parent_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	#[test]
	fn relation_path_uses_stable_aliases() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();

		assert_eq!(path.leaf_alias(), "corpus_file");
		assert_eq!(path.steps().len(), 1);
		assert_eq!(path.steps()[0].target_table, "corpus_files");
	}

	#[test]
	fn optional_path_promotes_join_kind_to_left() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();

		assert_eq!(path.join_kind(), RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_deduplicates_paths_and_preserves_left_join() {
		let inner = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();
		let left = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&inner);
		graph.add_path(&left);

		let joins = graph.joins();
		assert_eq!(joins.len(), 1);
		assert_eq!(joins[0].alias, "corpus_file");
		assert_eq!(joins[0].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn relation_path_then_appends_relation_steps() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(path.leaf_alias(), "corpus_file__project");
		assert_eq!(path.steps().len(), 2);
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].alias, "corpus_file");
		assert_eq!(joins[0].join_kind, RelationJoinKind::Inner);
		assert_eq!(joins[1].alias, "corpus_file__project");
		assert_eq!(joins[1].source_alias, "corpus_file");
		assert_eq!(joins[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_propagates_left_join_to_downstream_hops() {
		let path =
			RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentOptionalCorpusFile>()
				.then::<CorpusFileRequiredProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].join_kind, RelationJoinKind::Left);
		assert_eq!(joins[1].alias, "optional_corpus_file__required_project");
		assert_eq!(joins[1].source_alias, "optional_corpus_file");
		assert_eq!(joins[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_promotes_existing_descendants_when_prefix_becomes_left() {
		let longer = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileRequiredProject, Project>();
		let prefix = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&longer);
		graph.add_path(&prefix);

		assert_eq!(graph.joins().len(), 2);
		assert_eq!(graph.joins()[0].join_kind, RelationJoinKind::Left);
		assert_eq!(graph.joins()[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_disambiguates_relation_alias_matching_root_alias() {
		let path = RelationPath::<Project, Project>::from_descriptor::<ProjectNamedProjects>();
		let mut graph = RelationJoinGraph::new("projects");

		graph.add_path(&path);

		assert_eq!(path.leaf_alias(), "projects__projects");
		assert_eq!(graph.joins()[0].alias, "projects__projects");
		assert_eq!(graph.joins()[0].source_alias, "projects");
	}

	#[test]
	fn join_graph_keeps_repeated_relation_hops_distinct() {
		let path = RelationPath::<Project, Project>::from_descriptor::<Project>()
			.then::<Project, Project>();
		let mut graph = RelationJoinGraph::new("projects");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(path.leaf_alias(), "parent__parent");
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].alias, "parent");
		assert_eq!(joins[1].alias, "parent__parent");
		assert_eq!(joins[1].source_alias, "parent");
	}
}
