//! Typed relation traversal primitives for ORM queries.
//!
//! The types in this module describe relation paths generated by the model
//! macro. `QuerySet` consumes those paths to add deterministic SQL joins for
//! typed filters, `select_related`, and `prefetch_related` planning.

use std::borrow::Cow;
use std::collections::{HashMap, HashSet};
use std::marker::PhantomData;

use smallvec::SmallVec;

use crate::orm::Model;
use crate::orm::expressions::{FieldRef, GeneratedModelField, UnverifiedModelField};
use crate::orm::query::{Filter, FilterOperator, FilterValue, TypedFilter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
/// SQL join kind requested by a relation path.
pub enum RelationJoinKind {
	/// Use an inner join.
	Inner,
	/// Use a left outer join.
	Left,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
/// Number of target rows that one source row can reach through a relation hop.
pub enum RelationMultiplicity {
	/// Each source row reaches at most one target row.
	Single,
	/// Each source row can reach multiple target rows.
	Multiple,
}

impl RelationJoinKind {
	/// Merge two join requirements, preserving left joins when either side needs one.
	pub const fn merge(self, other: Self) -> Self {
		match (self, other) {
			(Self::Left, _) | (_, Self::Left) => Self::Left,
			(Self::Inner, Self::Inner) => Self::Inner,
		}
	}
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
/// One hop in a typed relation path.
pub struct RelationStep {
	/// Local relation name used to derive stable joined-table aliases.
	pub name: Cow<'static, str>,
	/// Source table for this hop.
	pub source_table: Cow<'static, str>,
	/// Target table for this hop.
	pub target_table: Cow<'static, str>,
	/// Source column used in the join predicate.
	pub source_column: Cow<'static, str>,
	/// Target column used in the join predicate.
	pub target_column: Cow<'static, str>,
	/// Default join kind for this hop.
	pub default_join_kind: RelationJoinKind,
	/// Whether this hop can multiply root rows.
	pub multiplicity: RelationMultiplicity,
}

/// Static descriptor generated for a concrete model relation.
pub trait RelationDescriptor {
	/// Model where the relation starts.
	type Source: Model;
	/// Model reached by the relation.
	type Target: Model;

	/// Return the relation steps that connect `Source` to `Target`.
	fn steps() -> Vec<RelationStep>;
}

/// Marker carried by relation paths emitted by the model derive macro.
///
/// This uninhabited type prevents application code from safely manufacturing
/// the proof that a relation descriptor matches generated model metadata.
#[doc(hidden)]
#[derive(Debug, Clone, Copy)]
pub enum GeneratedRelationPath {}

/// Marker for relation paths constructed by application code.
#[doc(hidden)]
#[derive(Debug, Clone, Copy)]
pub enum UnverifiedRelationPath {}

/// Marker carried by related field references selected through generated paths.
#[doc(hidden)]
#[derive(Debug, Clone, Copy)]
pub enum GeneratedRelatedField {}

/// Marker for related field references without generated relation and field proofs.
#[doc(hidden)]
#[derive(Debug, Clone, Copy)]
pub enum UnverifiedRelatedField {}

mod related_field_origin {
	pub trait Sealed {}

	impl Sealed for super::GeneratedRelationPath {}
	impl Sealed for super::UnverifiedRelationPath {}

	pub trait Combine<FieldOrigin>: Sealed {
		type RelatedFieldOrigin;
	}

	impl<FieldOrigin> Combine<FieldOrigin> for super::UnverifiedRelationPath {
		type RelatedFieldOrigin = super::UnverifiedRelatedField;
	}

	impl Combine<super::GeneratedModelField> for super::GeneratedRelationPath {
		type RelatedFieldOrigin = super::GeneratedRelatedField;
	}

	impl Combine<super::UnverifiedModelField> for super::GeneratedRelationPath {
		type RelatedFieldOrigin = super::UnverifiedRelatedField;
	}
}

/// Type-level combination of a relation-path origin and a target field origin.
///
/// This trait is sealed so only the model derive macro's relation and field
/// markers can produce a [`GeneratedRelatedField`] proof.
#[doc(hidden)]
pub trait RelationFieldOrigin<FieldOrigin>: related_field_origin::Sealed {
	/// Origin carried by the resulting related field reference.
	type RelatedFieldOrigin;
}

impl<PathOrigin, FieldOrigin> RelationFieldOrigin<FieldOrigin> for PathOrigin
where
	PathOrigin: related_field_origin::Combine<FieldOrigin>,
{
	type RelatedFieldOrigin =
		<PathOrigin as related_field_origin::Combine<FieldOrigin>>::RelatedFieldOrigin;
}

/// Model support for wrapping relation paths in generated typed accessors.
pub trait RelationTarget: Model {
	/// Generated path wrapper for this target model from a root model.
	type Path<Root: Model, Origin>: RelationPathLike<Root = Root, Target = Self>;

	/// Wrap a raw relation path in the generated target-specific path type.
	fn wrap_relation_path<Root: Model, Origin>(
		path: RelationPath<Root, Self, Origin>,
	) -> Self::Path<Root, Origin>
	where
		Self: Sized;
}

/// Common interface implemented by raw and generated relation path types.
pub trait RelationPathLike {
	/// Root model where the path starts.
	type Root: Model;
	/// Target model reached by the path.
	type Target: Model;

	/// Relation steps in traversal order.
	fn steps(&self) -> &[RelationStep];
	/// Join kind requested by this path.
	fn join_kind(&self) -> RelationJoinKind;
	/// Whole-path join kind override, if the path explicitly requested one.
	fn join_kind_override(&self) -> Option<RelationJoinKind> {
		None
	}
	/// Alias of the final joined relation.
	fn leaf_alias(&self) -> &str;
	/// Return whether any hop can produce multiple target rows per source row.
	fn is_multi_valued(&self) -> bool {
		self.steps()
			.iter()
			.any(|step| step.multiplicity == RelationMultiplicity::Multiple)
	}
}

#[derive(Debug, Clone)]
/// Typed path from one model to a related model.
pub struct RelationPath<Root: Model, Target: Model, Origin = UnverifiedRelationPath> {
	steps: SmallVec<[RelationStep; 4]>,
	step_aliases: SmallVec<[String; 4]>,
	join_kind_override: Option<RelationJoinKind>,
	_phantom: PhantomData<(Root, Target, Origin)>,
}

impl<Root: Model, Target: Model, Origin> RelationPath<Root, Target, Origin> {
	fn from_smallvec(path_steps: SmallVec<[RelationStep; 4]>) -> Self {
		let step_aliases = step_aliases(&path_steps, Root::table_name());
		Self {
			steps: path_steps,
			step_aliases,
			join_kind_override: None,
			_phantom: PhantomData,
		}
	}

	fn into_unverified(self) -> RelationPath<Root, Target> {
		RelationPath {
			steps: self.steps,
			step_aliases: self.step_aliases,
			join_kind_override: self.join_kind_override,
			_phantom: PhantomData,
		}
	}

	/// Convert this raw path into the target model's generated typed wrapper.
	///
	/// Raw paths remain available for relations whose target is a manually
	/// implemented [`Model`]. Calling this method requires the target to provide
	/// a [`RelationTarget`] implementation, which `#[model]` generates
	/// automatically.
	pub fn into_typed(self) -> <Target as RelationTarget>::Path<Root, Origin>
	where
		Target: RelationTarget,
	{
		Target::wrap_relation_path(self)
	}

	/// Append another relation descriptor without creating a generated proof.
	pub fn then<D, Next>(self) -> RelationPath<Root, Next>
	where
		D: RelationDescriptor<Source = Target, Target = Next>,
		Next: Model,
	{
		let join_kind_override = self.join_kind_override;
		let mut steps = self.steps;
		steps.extend(D::steps());
		let mut path = RelationPath::from_smallvec(steps);
		path.join_kind_override = join_kind_override;
		path
	}

	/// Append a descriptor emitted by the model derive macro.
	///
	/// # Safety
	///
	/// `D` must be a descriptor generated from relation metadata for `Target`.
	#[doc(hidden)]
	pub unsafe fn extend_generated_descriptor<D, Next>(self) -> RelationPath<Root, Next, Origin>
	where
		D: RelationDescriptor<Source = Target, Target = Next>,
		Next: Model,
	{
		let join_kind_override = self.join_kind_override;
		let mut steps = self.steps;
		steps.extend(D::steps());
		let mut path = RelationPath::from_smallvec(steps);
		path.join_kind_override = join_kind_override;
		path
	}

	/// Force the path to use left joins.
	pub fn optional(mut self) -> Self {
		self.join_kind_override = Some(RelationJoinKind::Left);
		self
	}

	/// Select a field on the target model through this relation path.
	pub fn field<Value, FieldOrigin>(
		self,
		field: FieldRef<Target, Value, FieldOrigin>,
	) -> RelatedFieldRef<
		Root,
		Target,
		Value,
		<Origin as RelationFieldOrigin<FieldOrigin>>::RelatedFieldOrigin,
	>
	where
		Origin: RelationFieldOrigin<FieldOrigin>,
	{
		RelatedFieldRef::from_names(self, field.logical_name(), field.name())
	}
}

impl<Root: Model, Target: Model> RelationPath<Root, Target, UnverifiedRelationPath> {
	/// Create a relation path from static relation steps.
	pub fn new(steps: &'static [RelationStep]) -> Self {
		let mut path_steps: SmallVec<[RelationStep; 4]> = SmallVec::new();
		path_steps.extend(steps.iter().cloned());
		Self::from_smallvec(path_steps)
	}

	/// Create a relation path from owned relation steps.
	pub fn from_owned_steps(steps: Vec<RelationStep>) -> Self {
		let path_steps: SmallVec<[RelationStep; 4]> = steps.into_iter().collect();
		Self::from_smallvec(path_steps)
	}

	/// Create a relation path from a relation descriptor.
	pub fn from_descriptor<D>() -> Self
	where
		D: RelationDescriptor<Source = Root, Target = Target>,
	{
		Self::from_owned_steps(D::steps())
	}
}

impl<Root: Model, Target: Model> RelationPath<Root, Target, GeneratedRelationPath> {
	/// Construct a relation path proven by generated model metadata.
	///
	/// # Safety
	///
	/// `steps` must come from relation metadata generated for `Root` and `Target`.
	#[doc(hidden)]
	pub unsafe fn from_generated_steps(steps: Vec<RelationStep>) -> Self {
		let path_steps: SmallVec<[RelationStep; 4]> = steps.into_iter().collect();
		Self::from_smallvec(path_steps)
	}
}

impl<Root: Model, Target: Model, Origin> RelationPathLike for RelationPath<Root, Target, Origin> {
	type Root = Root;
	type Target = Target;

	fn steps(&self) -> &[RelationStep] {
		&self.steps
	}

	fn join_kind(&self) -> RelationJoinKind {
		self.join_kind_override
			.unwrap_or_else(|| default_join_kind(&self.steps))
	}

	fn join_kind_override(&self) -> Option<RelationJoinKind> {
		self.join_kind_override
	}

	fn leaf_alias(&self) -> &str {
		self.step_aliases
			.last()
			.map(String::as_str)
			.unwrap_or_else(|| Target::table_name())
	}
}

#[derive(Debug, Clone, PartialEq, Eq)]
/// Planned SQL join derived from a relation path.
pub struct PlannedRelationJoin {
	/// Alias assigned to the joined table.
	pub alias: String,
	/// Local relation name for this hop.
	pub relation_name: String,
	/// Alias or table name of the previous relation hop.
	pub source_alias: String,
	/// Physical target table for the join.
	pub target_table: String,
	/// Source column used by the join predicate.
	pub source_column: String,
	/// Target column used by the join predicate.
	pub target_column: String,
	/// SQL join kind for this planned join.
	pub join_kind: RelationJoinKind,
	/// Whether this join can multiply root rows.
	pub multiplicity: RelationMultiplicity,
}

#[derive(Debug, Clone)]
/// Deduplicated join plan for typed relation paths in a query.
pub struct RelationJoinGraph {
	root_alias: String,
	joins: Vec<PlannedRelationJoin>,
}

impl RelationJoinGraph {
	/// Create an empty join graph with the provided root alias.
	pub fn new(root_alias: impl Into<String>) -> Self {
		Self {
			root_alias: root_alias.into(),
			joins: Vec::new(),
		}
	}

	/// Return a copy of this graph with a different root alias.
	pub fn with_root_alias(self, root_alias: impl Into<String>) -> Self {
		self.with_root_alias_and_reserved_aliases(root_alias, std::iter::empty())
	}

	/// Return a copy of this graph with a different root alias and externally reserved aliases.
	pub(crate) fn with_root_alias_and_reserved_aliases(
		mut self,
		root_alias: impl Into<String>,
		reserved_aliases: impl IntoIterator<Item = String>,
	) -> Self {
		let root_alias = root_alias.into();
		let previous_root_alias = std::mem::replace(&mut self.root_alias, root_alias);
		let mut aliases = HashMap::from([(previous_root_alias, self.root_alias.clone())]);
		let mut reserved_aliases: HashSet<_> = reserved_aliases.into_iter().collect();
		reserved_aliases.insert(self.root_alias.clone());
		for join in &mut self.joins {
			if let Some(source_alias) = aliases.get(&join.source_alias) {
				join.source_alias.clone_from(source_alias);
			}
			let alias = step_alias_with_reserved(
				&join.source_alias,
				&join.relation_name,
				&self.root_alias,
				&reserved_aliases,
			);
			reserved_aliases.insert(alias.clone());
			let previous_alias = std::mem::replace(&mut join.alias, alias);
			aliases.insert(previous_alias, join.alias.clone());
		}
		self
	}

	/// Add all steps from a relation path to the graph.
	pub fn add_path<P>(&mut self, path: &P)
	where
		P: RelationPathLike,
	{
		self.add_steps_with_override(path.steps(), path.join_kind_override());
	}

	/// Add relation steps required by an aggregate expression.
	///
	/// Aggregate paths are optional by nature: a root row with no related rows
	/// must remain visible with a zero/NULL aggregate result. Existing joins are
	/// deliberately retained unchanged so an INNER join required by a filter
	/// cannot be weakened by a later annotation.
	pub fn add_aggregate_path<P>(&mut self, path: &P)
	where
		P: RelationPathLike,
	{
		self.add_missing_steps(path.steps(), RelationJoinKind::Left);
	}

	/// Add aggregate relation steps when only their erased descriptors remain.
	pub(crate) fn add_aggregate_steps(&mut self, steps: &[RelationStep]) {
		self.add_missing_steps(steps, RelationJoinKind::Left);
	}

	fn add_missing_steps(&mut self, steps: &[RelationStep], join_kind: RelationJoinKind) {
		let mut source_alias = self.root_alias.clone();
		let mut force_downstream_left = false;
		let mut reserved_aliases = HashSet::from([self.root_alias.clone()]);
		reserved_aliases.extend(self.joins.iter().map(|join| join.alias.clone()));
		for step in steps {
			let requested_join_kind = if force_downstream_left {
				RelationJoinKind::Left
			} else {
				join_kind
			};
			if let Some(existing_index) = self.joins.iter().position(|join| {
				join.source_alias == source_alias && join.relation_name == step.name.as_ref()
			}) {
				let existing = &self.joins[existing_index];
				force_downstream_left |= existing.join_kind == RelationJoinKind::Left;
				source_alias.clone_from(&existing.alias);
				continue;
			}

			let alias = step_alias_with_reserved(
				&source_alias,
				step.name.as_ref(),
				&self.root_alias,
				&reserved_aliases,
			);
			reserved_aliases.insert(alias.clone());
			self.joins.push(PlannedRelationJoin {
				alias: alias.clone(),
				relation_name: step.name.to_string(),
				source_alias,
				target_table: step.target_table.to_string(),
				source_column: step.source_column.to_string(),
				target_column: step.target_column.to_string(),
				join_kind: requested_join_kind,
				multiplicity: step.multiplicity,
			});
			force_downstream_left = true;
			source_alias = alias;
		}
	}

	/// Add relation steps with an explicit join kind.
	pub fn add_steps(&mut self, steps: &[RelationStep], join_kind: RelationJoinKind) {
		self.add_steps_with_override(steps, Some(join_kind));
	}

	/// Add relation steps using per-hop defaults unless a whole-path override is supplied.
	pub fn add_steps_with_override(
		&mut self,
		steps: &[RelationStep],
		join_kind_override: Option<RelationJoinKind>,
	) {
		let mut source_alias = self.root_alias.clone();
		let mut force_downstream_left = false;
		let mut reserved_aliases = HashSet::from([self.root_alias.clone()]);
		reserved_aliases.extend(self.joins.iter().map(|join| join.alias.clone()));
		for step in steps {
			let requested_join_kind = if force_downstream_left {
				RelationJoinKind::Left
			} else {
				join_kind_override.unwrap_or(step.default_join_kind)
			};
			if let Some(existing_index) = self.joins.iter().position(|join| {
				join.source_alias == source_alias && join.relation_name == step.name.as_ref()
			}) {
				let existing = &mut self.joins[existing_index];
				let was_left = existing.join_kind == RelationJoinKind::Left;
				existing.join_kind = existing.join_kind.merge(requested_join_kind);
				let is_left = existing.join_kind == RelationJoinKind::Left;
				let existing_alias = existing.alias.clone();
				if !was_left && is_left {
					self.promote_descendants_to_left(&existing_alias);
				}
				force_downstream_left |= is_left;
				source_alias = existing_alias;
				continue;
			}

			let alias = step_alias_with_reserved(
				&source_alias,
				step.name.as_ref(),
				&self.root_alias,
				&reserved_aliases,
			);
			reserved_aliases.insert(alias.clone());
			self.joins.push(PlannedRelationJoin {
				alias: alias.clone(),
				relation_name: step.name.to_string(),
				source_alias,
				target_table: step.target_table.to_string(),
				source_column: step.source_column.to_string(),
				target_column: step.target_column.to_string(),
				join_kind: requested_join_kind,
				multiplicity: step.multiplicity,
			});
			force_downstream_left |= requested_join_kind == RelationJoinKind::Left;
			source_alias = alias;
		}
	}

	fn promote_descendants_to_left(&mut self, source_alias: &str) {
		let mut pending = vec![source_alias.to_string()];
		while let Some(parent_alias) = pending.pop() {
			for join in &mut self.joins {
				if join.source_alias == parent_alias {
					join.join_kind = RelationJoinKind::Left;
					pending.push(join.alias.clone());
				}
			}
		}
	}

	/// Return whether the graph has no planned joins.
	pub fn is_empty(&self) -> bool {
		self.joins.is_empty()
	}

	/// Return the planned joins in traversal order.
	pub fn joins(&self) -> &[PlannedRelationJoin] {
		&self.joins
	}

	/// Return the planned aliases for a relation path's steps.
	///
	/// The aliases are resolved from this graph rather than recomputed so callers
	/// observe the same collision handling used by the generated JOIN clauses.
	pub fn aliases_for_steps(&self, steps: &[RelationStep]) -> Option<SmallVec<[String; 4]>> {
		let mut source_alias = self.root_alias.clone();
		let mut aliases = SmallVec::new();
		for step in steps {
			let join = self.joins.iter().find(|join| {
				join.source_alias == source_alias && join.relation_name == step.name.as_ref()
			})?;
			source_alias.clone_from(&join.alias);
			aliases.push(source_alias.clone());
		}
		Some(aliases)
	}

	/// Return whether any planned join can produce multiple rows per root row.
	pub fn has_multi_valued_join(&self) -> bool {
		self.joins
			.iter()
			.any(|join| join.multiplicity == RelationMultiplicity::Multiple)
	}
}

impl Default for RelationJoinGraph {
	fn default() -> Self {
		Self::new("")
	}
}

fn default_join_kind(steps: &[RelationStep]) -> RelationJoinKind {
	steps
		.iter()
		.map(|step| step.default_join_kind)
		.fold(RelationJoinKind::Inner, RelationJoinKind::merge)
}

fn step_alias(source_alias: &str, step_name: &str, root_alias: &str) -> String {
	if source_alias == root_alias {
		if step_name == root_alias {
			format!("{}__{}", root_alias, step_name)
		} else {
			step_name.to_string()
		}
	} else {
		format!("{}__{}", source_alias, step_name)
	}
}

fn step_alias_with_reserved(
	source_alias: &str,
	step_name: &str,
	root_alias: &str,
	reserved_aliases: &HashSet<String>,
) -> String {
	let mut alias = step_alias(source_alias, step_name, root_alias);
	while reserved_aliases.contains(&alias) {
		alias = format!("{alias}__{step_name}");
	}
	alias
}

pub(crate) fn step_aliases(steps: &[RelationStep], root_alias: &str) -> SmallVec<[String; 4]> {
	let mut aliases = SmallVec::new();
	let mut source_alias = String::new();
	for (index, step) in steps.iter().enumerate() {
		let alias = if index == 0 {
			step_alias(root_alias, step.name.as_ref(), root_alias)
		} else {
			step_alias(&source_alias, step.name.as_ref(), "")
		};
		source_alias = alias.clone();
		aliases.push(alias);
	}
	aliases
}

#[derive(Debug, Clone)]
/// Field reference reached through a typed relation path.
pub struct RelatedFieldRef<Root: Model, Target: Model, Value, Origin = UnverifiedRelatedField> {
	path: RelationPath<Root, Target>,
	field: &'static str,
	column: String,
	_phantom: PhantomData<(Value, Origin)>,
}

impl<Root: Model, Target: Model, Value>
	RelatedFieldRef<Root, Target, Value, UnverifiedRelatedField>
{
	/// Create a related field reference from a path and target field name.
	pub fn new<PathOrigin>(
		path: RelationPath<Root, Target, PathOrigin>,
		field: &'static str,
	) -> Self {
		let column = Target::field_metadata()
			.into_iter()
			.find(|metadata| metadata.name == field)
			.map_or_else(
				|| field.to_string(),
				|metadata| metadata.db_column_name().to_string(),
			);

		Self {
			path: path.into_unverified(),
			field,
			column,
			_phantom: PhantomData,
		}
	}
}

impl<Root: Model, Target: Model, Value, Origin> RelatedFieldRef<Root, Target, Value, Origin> {
	fn from_names<PathOrigin>(
		path: RelationPath<Root, Target, PathOrigin>,
		field: &'static str,
		column: &'static str,
	) -> Self {
		Self {
			path: path.into_unverified(),
			field,
			column: column.to_string(),
			_phantom: PhantomData,
		}
	}

	/// Return the target field name.
	pub fn name(&self) -> &'static str {
		self.field
	}

	/// Return the relation path for this field.
	pub fn path(&self) -> &RelationPath<Root, Target> {
		&self.path
	}

	fn filter(&self, operator: FilterOperator, value: FilterValue) -> TypedFilter<Root> {
		TypedFilter::new(Filter::related(&self.column, operator, value, &self.path))
	}

	/// Build an equality filter for this related field.
	pub fn eq<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Eq, value.into())
	}

	/// Build an exact-match filter for this related field.
	pub fn exact<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.eq(value)
	}

	/// Build a case-insensitive exact-match filter for this related field.
	pub fn iexact<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IExact, value.into())
	}

	/// Build a not-equal filter for this related field.
	pub fn ne<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Ne, value.into())
	}

	/// Build a greater-than filter for this related field.
	pub fn gt<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Gt, value.into())
	}

	/// Build a greater-than-or-equal filter for this related field.
	pub fn gte<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Gte, value.into())
	}

	/// Build a less-than filter for this related field.
	pub fn lt<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Lt, value.into())
	}

	/// Build a less-than-or-equal filter for this related field.
	pub fn lte<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Lte, value.into())
	}

	/// Build a contains filter for this related field.
	pub fn contains<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::Contains, value.into())
	}

	/// Build a case-insensitive contains filter for this related field.
	pub fn icontains<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IContains, value.into())
	}

	/// Build a starts-with filter for this related field.
	pub fn startswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::StartsWith, value.into())
	}

	/// Build a case-insensitive starts-with filter for this related field.
	pub fn istartswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IStartsWith, value.into())
	}

	/// Build an ends-with filter for this related field.
	pub fn endswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::EndsWith, value.into())
	}

	/// Build a case-insensitive ends-with filter for this related field.
	pub fn iendswith<V: Into<FilterValue>>(&self, value: V) -> TypedFilter<Root> {
		self.filter(FilterOperator::IEndsWith, value.into())
	}

	/// Build an `IS NULL` filter for this related field.
	pub fn is_null(&self) -> TypedFilter<Root> {
		self.filter(FilterOperator::IsNull, FilterValue::Null)
	}

	/// Build an `IS NOT NULL` filter for this related field.
	pub fn is_not_null(&self) -> TypedFilter<Root> {
		self.filter(FilterOperator::IsNotNull, FilterValue::Null)
	}
}

impl<Root, Target, Value> RelatedFieldRef<Root, Target, Value, GeneratedRelatedField>
where
	Root: Model,
	Target: Model,
	Value: crate::orm::DatabaseField,
{
	/// Convert this generated related field into a structured typed expression.
	pub fn into_expression(self) -> crate::orm::query_fields::TypedExpression<Root, Value> {
		self.into()
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::orm::Model;
	use serde::{Deserialize, Serialize};

	#[derive(Clone, Serialize, Deserialize)]
	struct Document {
		id: Option<i64>,
	}

	#[derive(Clone, Serialize, Deserialize)]
	struct CorpusFile {
		id: Option<i64>,
	}

	#[derive(Clone, Serialize, Deserialize)]
	struct Project {
		id: Option<i64>,
	}

	#[derive(Clone)]
	struct EmptyFields;

	impl crate::orm::FieldSelector for EmptyFields {
		fn with_alias(self, _alias: &str) -> Self {
			self
		}
	}

	impl Model for Document {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"documents"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	impl Model for CorpusFile {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"corpus_files"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	impl Model for Project {
		type PrimaryKey = i64;
		type Fields = EmptyFields;
		type Objects = crate::orm::Manager<Self>;

		fn table_name() -> &'static str {
			"projects"
		}

		fn new_fields() -> Self::Fields {
			EmptyFields
		}

		fn primary_key(&self) -> Option<Self::PrimaryKey> {
			self.id
		}

		fn set_primary_key(&mut self, value: Self::PrimaryKey) {
			self.id = Some(value);
		}
	}

	struct DocumentCorpusFile;

	impl RelationDescriptor for DocumentCorpusFile {
		type Source = Document;
		type Target = CorpusFile;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "corpus_file".into(),
				source_table: "documents".into(),
				target_table: "corpus_files".into(),
				source_column: "corpus_file_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct DocumentOptionalCorpusFile;

	impl RelationDescriptor for DocumentOptionalCorpusFile {
		type Source = Document;
		type Target = CorpusFile;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "optional_corpus_file".into(),
				source_table: "documents".into(),
				target_table: "corpus_files".into(),
				source_column: "corpus_file_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Left,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct CorpusFileProject;

	impl RelationDescriptor for CorpusFileProject {
		type Source = CorpusFile;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "project".into(),
				source_table: "corpus_files".into(),
				target_table: "projects".into(),
				source_column: "project_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Left,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct CorpusFileRequiredProject;

	impl RelationDescriptor for CorpusFileRequiredProject {
		type Source = CorpusFile;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "required_project".into(),
				source_table: "corpus_files".into(),
				target_table: "projects".into(),
				source_column: "project_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct DocumentRelationNamedCorpusFileProject;

	impl RelationDescriptor for DocumentRelationNamedCorpusFileProject {
		type Source = Document;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "corpus_file__project".into(),
				source_table: "documents".into(),
				target_table: "projects".into(),
				source_column: "project_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	struct ProjectNamedProjects;

	impl RelationDescriptor for ProjectNamedProjects {
		type Source = Project;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "projects".into(),
				source_table: "projects".into(),
				target_table: "projects".into(),
				source_column: "parent_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	impl RelationDescriptor for Project {
		type Source = Project;
		type Target = Project;

		fn steps() -> Vec<RelationStep> {
			vec![RelationStep {
				name: "parent".into(),
				source_table: "projects".into(),
				target_table: "projects".into(),
				source_column: "parent_id".into(),
				target_column: "id".into(),
				default_join_kind: RelationJoinKind::Inner,
				multiplicity: RelationMultiplicity::Single,
			}]
		}
	}

	#[test]
	fn relation_path_uses_stable_aliases() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();

		assert_eq!(path.leaf_alias(), "corpus_file");
		assert_eq!(path.steps().len(), 1);
		assert_eq!(path.steps()[0].target_table, "corpus_files");
	}

	#[test]
	fn optional_path_promotes_join_kind_to_left() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();

		assert_eq!(path.join_kind(), RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_deduplicates_paths_and_preserves_left_join() {
		let inner = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();
		let left = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&inner);
		graph.add_path(&left);

		let joins = graph.joins();
		assert_eq!(joins.len(), 1);
		assert_eq!(joins[0].alias, "corpus_file");
		assert_eq!(joins[0].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn relation_path_then_appends_relation_steps() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(path.leaf_alias(), "corpus_file__project");
		assert_eq!(path.steps().len(), 2);
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].alias, "corpus_file");
		assert_eq!(joins[0].join_kind, RelationJoinKind::Inner);
		assert_eq!(joins[1].alias, "corpus_file__project");
		assert_eq!(joins[1].source_alias, "corpus_file");
		assert_eq!(joins[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn optional_path_override_survives_extension() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional()
			.then::<CorpusFileProject, Project>();

		assert_eq!(path.join_kind(), RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_propagates_left_join_to_downstream_hops() {
		let path =
			RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentOptionalCorpusFile>()
				.then::<CorpusFileRequiredProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].join_kind, RelationJoinKind::Left);
		assert_eq!(joins[1].alias, "optional_corpus_file__required_project");
		assert_eq!(joins[1].source_alias, "optional_corpus_file");
		assert_eq!(joins[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_promotes_existing_descendants_when_prefix_becomes_left() {
		let longer = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileRequiredProject, Project>();
		let prefix = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.optional();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&longer);
		graph.add_path(&prefix);

		assert_eq!(graph.joins().len(), 2);
		assert_eq!(graph.joins()[0].join_kind, RelationJoinKind::Left);
		assert_eq!(graph.joins()[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn join_graph_disambiguates_relation_alias_matching_root_alias() {
		let path = RelationPath::<Project, Project>::from_descriptor::<ProjectNamedProjects>();
		let mut graph = RelationJoinGraph::new("projects");

		graph.add_path(&path);

		assert_eq!(path.leaf_alias(), "projects__projects");
		assert_eq!(graph.joins()[0].alias, "projects__projects");
		assert_eq!(graph.joins()[0].source_alias, "projects");
	}

	#[test]
	fn join_graph_rebases_nested_alias_that_matches_root_alias() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");
		graph.add_path(&path);

		let graph = graph.with_root_alias("corpus_file__project");
		let joins = graph.joins();

		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].source_alias, "corpus_file__project");
		assert_eq!(joins[0].alias, "corpus_file");
		assert_eq!(joins[1].source_alias, "corpus_file");
		assert_eq!(joins[1].alias, "corpus_file__project__project");
	}

	#[test]
	fn join_graph_reserves_aliases_while_adding_paths() {
		let direct = RelationPath::<Document, Project>::from_descriptor::<
			DocumentRelationNamedCorpusFileProject,
		>();
		let nested = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>()
			.then::<CorpusFileProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");

		graph.add_path(&direct);
		graph.add_path(&nested);

		let joins = graph.joins();
		assert_eq!(joins.len(), 3);
		assert_eq!(joins[0].alias, "corpus_file__project");
		assert_eq!(joins[1].alias, "corpus_file");
		assert_eq!(joins[2].alias, "corpus_file__project__project");
	}

	#[test]
	fn join_graph_keeps_repeated_relation_hops_distinct() {
		let path = RelationPath::<Project, Project>::from_descriptor::<Project>()
			.then::<Project, Project>();
		let mut graph = RelationJoinGraph::new("projects");

		graph.add_path(&path);

		let joins = graph.joins();
		assert_eq!(path.leaf_alias(), "parent__parent");
		assert_eq!(joins.len(), 2);
		assert_eq!(joins[0].alias, "parent");
		assert_eq!(joins[1].alias, "parent__parent");
		assert_eq!(joins[1].source_alias, "parent");
	}

	#[test]
	fn aggregate_path_keeps_filter_inner_join_and_adds_left_hops() {
		let filter_path =
			RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();
		let aggregate_path = filter_path.clone().then::<CorpusFileProject, Project>();
		let mut graph = RelationJoinGraph::new("documents");
		graph.add_path(&filter_path);
		graph.add_aggregate_path(&aggregate_path);

		assert_eq!(graph.joins().len(), 2);
		assert_eq!(graph.joins()[0].join_kind, RelationJoinKind::Inner);
		assert_eq!(graph.joins()[1].join_kind, RelationJoinKind::Left);
	}

	#[test]
	fn aggregate_path_deduplicates_repeated_left_hops() {
		let path = RelationPath::<Document, CorpusFile>::from_descriptor::<DocumentCorpusFile>();
		let mut graph = RelationJoinGraph::new("documents");
		graph.add_aggregate_path(&path);
		graph.add_aggregate_path(&path);

		assert_eq!(graph.joins().len(), 1);
		assert_eq!(graph.joins()[0].join_kind, RelationJoinKind::Left);
	}
}
