name: "\u2728 Feature Request"
description: Suggest a new feature or enhancement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues to verify this feature hasn't been requested
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem
      description: |
        Why do you need this feature? What problem does it solve?
        Describe the use case and the pain points you're experiencing.
      placeholder: |
        I'm trying to do X, but currently I have to do Y which is cumbersome because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to see an API like...

        ```rust
        // Example code
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've considered using X, but it doesn't work because...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that would help
