use reinhardt_migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "snippets",
		name: "auto_migration_20251202_061505",
		operations: vec![Operation::CreateTable {
			name: "snippets",
			columns: vec![
				ColumnDefinition {
					name: "id",
					type_definition: BigIntegerField,
					not_null: true,
					unique: false,
					primary_key: true,
					auto_increment: false,
					default: None,
					max_length: None,
				},
				ColumnDefinition {
					name: "created_at",
					type_definition: DateTimeField,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
					max_length: None,
				},
				ColumnDefinition {
					name: "code",
					type_definition: CharField,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
					max_length: None,
				},
				ColumnDefinition {
					name: "language",
					type_definition: CharField,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
					max_length: None,
				},
				ColumnDefinition {
					name: "title",
					type_definition: CharField,
					not_null: true,
					unique: false,
					primary_key: false,
					auto_increment: false,
					default: None,
					max_length: None,
				},
			],
			constraints: vec![],
		}],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
