name: Setup Protobuf Compiler
description: Install protoc
runs:
  using: composite
  steps:
    - name: Install protoc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
