//! Default byte-vector models through migration generation and PostgreSQL application.

#![cfg(feature = "postgres")]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use reinhardt::model;
use reinhardt_commands::{BaseCommand, CommandContext, MakeMigrationsCommand, MigrateCommand};
use reinhardt_db::migrations::model_registry::global_registry;
use reinhardt_db::migrations::{
	FieldType, FilesystemSource, MigrationSource, Operation, SqlDialect,
};
use reinhardt_query::prelude::{
	Alias, Expr, ExprTrait, IntoValue, Order, PostgresQueryBuilder, Query, QueryStatementBuilder,
};
use reinhardt_test::fixtures::postgres_container;
use rstest::rstest;
use serial_test::serial;
use sqlx::PgPool;
use tempfile::TempDir;
use testcontainers::{ContainerAsync, GenericImage};

const APP: &str = "binary_migration_test";
const TABLE: &str = "binary_migration_test_record";

// The model macro registers this fixture; tests inspect its migration metadata.
#[allow(dead_code)]
#[model(
	app_label = "binary_migration_test",
	table_name = "binary_migration_test_record"
)]
#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct BinaryRecord {
	#[field(primary_key = true)]
	id: i64,
	payload: Vec<u8>,
	#[field(null = true, unique = true)]
	code_hash: Option<Vec<u8>>,
}

struct ProjectDirGuard {
	previous: PathBuf,
}

impl ProjectDirGuard {
	fn enter(path: &Path) -> Self {
		let previous = std::env::current_dir().expect("read current directory");
		std::env::set_current_dir(path).expect("enter temporary project");
		Self { previous }
	}
}

impl Drop for ProjectDirGuard {
	fn drop(&mut self) {
		std::env::set_current_dir(&self.previous).expect("restore current directory");
	}
}

#[rstest]
#[tokio::test]
#[serial(global_registry)]
async fn generated_binary_model_migration_applies_to_postgres(
	#[future] postgres_container: (ContainerAsync<GenericImage>, Arc<PgPool>, u16, String),
) {
	// Arrange: a real registered model and an empty, disposable project/database.
	let (_container, pool, _port, url) = postgres_container.await;
	let project = TempDir::new_in("/tmp").expect("create temporary project");
	std::fs::create_dir_all(project.path().join("src/bin")).expect("create entry point directory");
	std::fs::write(project.path().join("src/bin/manage.rs"), "fn main() {}\n")
		.expect("write management entry point");
	let _cwd = ProjectDirGuard::enter(project.path());
	let migrations_dir = project.path().join("migrations");
	let mut context = CommandContext::new(vec![APP.to_owned()]);
	context.set_option(
		"migrations-dir".to_owned(),
		migrations_dir.to_str().unwrap().to_owned(),
	);
	context.set_option("name".to_owned(), "binary_fields".to_owned());
	context.set_option("force-empty-state".to_owned(), "true".to_owned());
	let metadata = global_registry()
		.get_model(APP, "BinaryRecord")
		.expect("model macro must register BinaryRecord");
	assert_eq!(metadata.fields["payload"].field_type, FieldType::Binary);
	assert_eq!(metadata.fields["code_hash"].field_type, FieldType::Binary);

	// Act: generate the Rust migration and load its actual operations from disk.
	MakeMigrationsCommand
		.execute(&context)
		.await
		.expect("generate byte-vector migration");
	let migration = FilesystemSource::new(&migrations_dir)
		.get_migration(APP, "0001_binary_fields")
		.await
		.expect("load generated migration");
	let (operation, columns) = migration
		.operations
		.iter()
		.find_map(|operation| match operation {
			Operation::CreateTable { name, columns, .. } if name == TABLE => {
				Some((operation, columns))
			}
			_ => None,
		})
		.expect("generated migration must create the model table");

	// Assert: both forms retain generic metadata and render applicable PostgreSQL types.
	for name in ["payload", "code_hash"] {
		let column = columns
			.iter()
			.find(|column| column.name == name)
			.expect("byte-vector column");
		assert_eq!(column.type_definition, FieldType::Binary);
		assert_eq!(column.not_null, name == "payload");
	}
	let sql = operation.to_sql(&SqlDialect::Postgres);
	assert!(sql.contains("payload BYTEA NOT NULL"), "{sql}");
	assert!(sql.contains("code_hash BYTEA"), "{sql}");
	assert!(!sql.contains("BINARY"), "{sql}");
	context.set_option("database".to_owned(), url);
	MigrateCommand
		.execute(&context)
		.await
		.expect("apply generated byte-vector migration");

	let column_types = Query::select()
		.columns([
			Alias::new("column_name"),
			Alias::new("data_type"),
			Alias::new("is_nullable"),
		])
		.from((Alias::new("information_schema"), Alias::new("columns")))
		.and_where(Expr::col(Alias::new("table_name")).eq(TABLE))
		.and_where(Expr::col(Alias::new("column_name")).is_in(["payload", "code_hash"]))
		.order_by(Alias::new("column_name"), Order::Asc)
		.to_string(PostgresQueryBuilder);
	let types: Vec<(String, String, String)> = sqlx::query_as(&column_types)
		.fetch_all(pool.as_ref())
		.await
		.expect("inspect physical column types");
	assert_eq!(
		types,
		vec![
			("code_hash".to_owned(), "bytea".to_owned(), "YES".to_owned()),
			("payload".to_owned(), "bytea".to_owned(), "NO".to_owned()),
		]
	);

	// Exercise arbitrary bytes, an empty vector, and the nullable/unique field.
	let payload = vec![0_u8, 255, 16, 0];
	let hash = vec![255_u8, 0, 1];
	let insert = Query::insert()
		.into_table(Alias::new(TABLE))
		.columns([
			Alias::new("id"),
			Alias::new("payload"),
			Alias::new("code_hash"),
		])
		.values_panic([
			1_i64.into_value(),
			payload.clone().into_value(),
			Some(hash.clone()).into_value(),
		])
		.values_panic([
			2_i64.into_value(),
			Vec::<u8>::new().into_value(),
			Option::<Vec<u8>>::None.into_value(),
		])
		.to_string(PostgresQueryBuilder);
	sqlx::query(&insert)
		.execute(pool.as_ref())
		.await
		.expect("store binary values");
	let select = Query::select()
		.columns([Alias::new("payload"), Alias::new("code_hash")])
		.from(Alias::new(TABLE))
		.order_by(Alias::new("id"), Order::Asc)
		.to_string(PostgresQueryBuilder);
	let rows: Vec<(Vec<u8>, Option<Vec<u8>>)> = sqlx::query_as(&select)
		.fetch_all(pool.as_ref())
		.await
		.expect("read binary values");
	assert_eq!(
		rows,
		vec![(payload.clone(), Some(hash.clone())), (vec![], None)]
	);

	let duplicate = Query::insert()
		.into_table(Alias::new(TABLE))
		.columns([
			Alias::new("id"),
			Alias::new("payload"),
			Alias::new("code_hash"),
		])
		.values_panic([
			3_i64.into_value(),
			payload.into_value(),
			Some(hash).into_value(),
		])
		.to_string(PostgresQueryBuilder);
	let error = sqlx::query(&duplicate)
		.execute(pool.as_ref())
		.await
		.expect_err("unique hash must reject duplicates");
	assert_eq!(
		error
			.as_database_error()
			.and_then(|error| error.code())
			.as_deref(),
		Some("23505")
	);
}
