name: Setup GTK Dependencies
description: Install GTK and WebKit dependencies for wry/tao on Linux

runs:
  using: composite
  steps:
    - name: Install GTK dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
