//! Composable settings fragment trait
//!
//! Defines the [`SettingsFragment`] trait that all composable settings units implement.
//! Each fragment maps to a TOML section and can be validated independently.
//!
//! # TOML section mapping
//!
//! Each fragment's [`SettingsFragment::section()`] determines which TOML section it
//! deserializes from. For example, `CoreSettings` (section `"core"`) reads from `[core]`,
//! and `I18nSettings` (section `"i18n"`) reads from `[i18n]`.
//!
//! # Nested structs within fragments
//!
//! When a fragment contains nested structs (e.g., `CoreSettings.security`), the
//! nested struct maps to a TOML sub-section named after the field:
//!
//! ```toml
//! [core]
//! secret_key = "..."
//! debug = false
//!
//! [core.security]
//! secure_ssl_redirect = true
//! session_cookie_secure = true
//! ```
//!
//! In the legacy `Settings` format (where `CoreSettings` is flattened at the root),
//! the sub-section becomes a top-level section:
//!
//! ```toml
//! secret_key = "..."
//! debug = false
//!
//! [security]
//! secure_ssl_redirect = true
//! session_cookie_secure = true
//! ```
//!
//! # Shallow merge semantics
//!
//! When multiple TOML files are merged (e.g., `base.toml` + `local.toml`), each
//! top-level section is replaced as a whole. If `local.toml` defines `[core]`, it
//! replaces the entire `[core]` section from `base.toml`. Therefore, environment-specific
//! files must be self-contained for any section they define.

use super::policy::FieldPolicy;
use super::profile::Profile;
use super::validation::ValidationResult;
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::fmt::Debug;

/// Profile-aware validation for settings fragments.
///
/// Implement this trait to add custom validation logic to a settings fragment.
/// The `#[settings(fragment = true)]` macro generates a default (no-op) implementation
/// automatically. To provide custom validation, use `validate = false` in the macro
/// and implement this trait manually:
///
/// ```ignore
/// #[settings(fragment = true, section = "security", validate = false)]
/// struct SecuritySettings { /* ... */ }
///
/// impl SettingsValidation for SecuritySettings {
///     fn validate(&self, profile: &Profile) -> ValidationResult {
///         // custom validation logic
///         Ok(())
///     }
/// }
/// ```
pub trait SettingsValidation {
	/// Validate this fragment against the given profile.
	///
	/// Default implementation: no-op (always valid).
	fn validate(&self, _profile: &Profile) -> ValidationResult {
		Ok(())
	}
}

/// A composable unit of configuration.
///
/// Each fragment maps to a TOML section and can be validated independently.
/// Fragments are composed into a `ProjectSettings` struct using the
/// `#[settings(key: Type | !Type)]` macro.
///
/// # Implementing
///
/// Use `#[settings(fragment = true, section = "...")]` to auto-derive this trait,
/// or implement it manually for custom validation.
pub trait SettingsFragment:
	Clone + Debug + Serialize + DeserializeOwned + Send + Sync + 'static
{
	/// The accessor trait for this fragment.
	///
	/// Expresses the type-level association between a settings fragment
	/// and its `Has*Settings` accessor trait. Use `()` for fragments
	/// without a dedicated accessor trait.
	type Accessor: ?Sized;

	/// TOML section name (e.g., `"cache"`, `"core"`).
	fn section() -> &'static str;

	/// Validate this fragment against the given profile.
	///
	/// Default implementation: no-op (always valid).
	/// For custom validation, implement [`SettingsValidation`] and override
	/// this method to delegate to it.
	fn validate(&self, _profile: &Profile) -> ValidationResult {
		Ok(())
	}

	/// Returns the default field policies defined by the library author.
	///
	/// Generated by the `#[settings(fragment = true)]` macro from
	/// `#[setting(...)]` field attributes. Returns empty slice by default
	/// for backward compatibility with existing fragments.
	fn field_policies() -> &'static [FieldPolicy] {
		&[]
	}
}

/// Generic accessor trait for settings fragments.
///
/// The `#[settings]` macro generates implementations of this trait
/// using fully-qualified paths, so users do not need to manually
/// import individual `Has*Settings` traits.
///
/// Blanket implementations bridge `HasSettings<F>` to the specific
/// `Has*Settings` traits for each built-in fragment.
pub trait HasSettings<F: SettingsFragment> {
	/// Returns a reference to the contained fragment.
	fn get_settings(&self) -> &F;
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::settings::profile::Profile;
	use rstest::rstest;

	#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
	struct TestFragment {
		pub value: String,
	}

	impl SettingsFragment for TestFragment {
		type Accessor = ();

		fn section() -> &'static str {
			"test"
		}
	}

	#[rstest]
	fn test_settings_fragment_section() {
		// Arrange
		// (no setup needed)

		// Act
		let section = TestFragment::section();

		// Assert
		assert_eq!(section, "test");
	}

	#[rstest]
	fn test_settings_fragment_validate_default_ok() {
		// Arrange
		let fragment = TestFragment {
			value: "hello".to_string(),
		};
		let profile = Profile::Development;

		// Act
		let result = fragment.validate(&profile);

		// Assert
		assert!(result.is_ok());
	}
}
