/// Field-level policy for settings fragments.
///
/// Determines whether a field must have an explicit value
/// after all configuration sources are merged by `SettingsBuilder`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldRequirement {
	/// The field MUST have a value after all sources are resolved.
	/// `SettingsBuilder::build_composed()` returns an error if missing.
	Required,
	/// The field MAY be absent. Default value is used if not provided.
	Optional,
}

/// Metadata describing a single field's policy within a `SettingsFragment`.
///
/// Generated by the `#[settings(fragment = true)]` macro from
/// `#[setting(...)]` field attributes and `default_policy` configuration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldPolicy {
	/// Field name (matches the struct field name, used for key lookup
	/// in the merged `IndexMap<String, serde_json::Value>`)
	pub name: &'static str,
	/// Whether the field is required or optional
	pub requirement: FieldRequirement,
	/// Whether a compile-time default value is defined via `#[setting(default = "...")]`
	/// or the type implements `Default` (for fields inheriting `default_policy = "optional"`)
	pub has_default: bool,
}
