name: Docker Login
description: Login to Docker Hub to avoid rate limits

inputs:
  username:
    description: Docker Hub username
    required: false
  token:
    description: Docker Hub access token
    required: false

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      if: inputs.username != '' && inputs.token != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
