use proc_macro2::TokenStream;
use quote::quote;
use syn::{ItemFn, parse2};

/// Flatten a function body into a flat token stream for pattern scanning.
///
/// Recursively descends into `Group` tokens (braces, parentheses, brackets)
/// so that `.endpoint()`, `.viewset()`, and `.mount()` calls inside control
/// flow blocks (`if`, `match`, `for`, etc.) are detected.
fn flatten_body(func: &ItemFn) -> Vec<proc_macro2::TokenTree> {
	fn recurse(
		tokens: impl IntoIterator<Item = proc_macro2::TokenTree>,
	) -> Vec<proc_macro2::TokenTree> {
		let mut result = Vec::new();
		for tt in tokens {
			match &tt {
				proc_macro2::TokenTree::Group(group) => {
					result.push(tt.clone());
					result.extend(recurse(group.stream()));
				}
				_ => result.push(tt),
			}
		}
		result
	}

	func.block
		.stmts
		.iter()
		.flat_map(|stmt| {
			let tokens: TokenStream = quote! { #stmt };
			recurse(tokens)
		})
		.collect()
}

/// Extract endpoint path expressions from a function body.
///
/// Scans tokens for `.endpoint(EXPR)` patterns and returns
/// the path expressions.
fn extract_endpoint_paths(func: &ItemFn) -> Vec<TokenStream> {
	let mut paths = Vec::new();
	let body_tokens = flatten_body(func);

	let mut i = 0;
	while i < body_tokens.len() {
		// Look for: Punct('.') Ident("endpoint") Group(Parenthesized)
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == "endpoint"
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			paths.push(group.stream());
			i += 3;
			continue;
		}
		i += 1;
	}
	paths
}

/// A viewset call extracted from the function body.
///
/// Example: `.viewset("/snippets", views::viewset())`
/// yields `ViewSetCall { expr_path: "views :: viewset" }`.
/// The `#[url_patterns]` macro uses `expr_path` to locate the
/// `__viewset_resolvers_{fn_name}` bundle module generated by `#[viewset]`.
struct ViewSetCall {
	expr_path: TokenStream,
}

/// Extract `.viewset(STR, EXPR)` calls from a function body.
///
/// Scans for the pattern `.viewset(string_literal, path_expr(...))` and
/// returns the second argument's path (stripping the trailing `()` call).
fn extract_viewset_calls(func: &ItemFn) -> Vec<ViewSetCall> {
	let mut calls = Vec::new();
	let body_tokens = flatten_body(func);

	let mut i = 0;
	while i < body_tokens.len() {
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == "viewset"
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			// Group contains: STR_LITERAL, EXPR (possibly with trailing `()`)
			let mut found_comma = false;
			let mut expr_tokens = Vec::new();
			for tt in group.stream() {
				if found_comma {
					// Skip trailing parenthesized group (the `()` function call)
					if let proc_macro2::TokenTree::Group(g) = &tt
						&& g.delimiter() == proc_macro2::Delimiter::Parenthesis
					{
						continue;
					}
					expr_tokens.push(tt);
				} else if let proc_macro2::TokenTree::Punct(p) = &tt
					&& p.as_char() == ','
				{
					found_comma = true;
				}
			}
			if !expr_tokens.is_empty() {
				let expr_path: TokenStream = expr_tokens.into_iter().collect();
				calls.push(ViewSetCall { expr_path });
			}
			i += 3;
			continue;
		}
		i += 1;
	}
	calls
}

/// A mount call extracted from the function body.
struct MountCall {
	expr_path: TokenStream,
}

/// Extract `.mount(STR, EXPR)` calls from a function body.
///
/// Scans for the pattern `.mount(string_literal, path_expr(...))` and
/// returns the second argument's path (stripping the trailing `()` call).
fn extract_mount_calls(func: &ItemFn) -> Vec<MountCall> {
	let mut calls = Vec::new();
	let body_tokens = flatten_body(func);

	let mut i = 0;
	while i < body_tokens.len() {
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == "mount"
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			let mut found_comma = false;
			let mut expr_tokens = Vec::new();
			for tt in group.stream() {
				if found_comma {
					if let proc_macro2::TokenTree::Group(g) = &tt
						&& g.delimiter() == proc_macro2::Delimiter::Parenthesis
					{
						continue;
					}
					expr_tokens.push(tt);
				} else if let proc_macro2::TokenTree::Punct(p) = &tt
					&& p.as_char() == ','
				{
					found_comma = true;
				}
			}
			if !expr_tokens.is_empty() {
				let expr_path: TokenStream = expr_tokens.into_iter().collect();
				calls.push(MountCall { expr_path });
			}
			i += 3;
			continue;
		}
		i += 1;
	}
	calls
}

/// Build a re-export statement for a URL resolver module from an endpoint path.
///
/// Given an endpoint path like `views::login`, generates:
/// `pub use super::views::__url_resolver_login::*;`
///
/// For absolute paths starting with `crate::` or `super::`, the `super::` prefix is omitted:
/// `pub use crate::views::__url_resolver_login::*;`
fn build_resolver_reexport(path: &TokenStream) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	let last_segment = &parsed.segments.last().unwrap().ident;
	let resolver_mod = syn::Ident::new(
		&format!("__url_resolver_{last_segment}"),
		last_segment.span(),
	);

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute =
		first_segment == "crate" || first_segment == "super" || parsed.leading_colon.is_some();

	let parent_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	if is_absolute {
		quote! {
			pub use #(#parent_segments ::)* #resolver_mod::*;
		}
	} else {
		quote! {
			pub use super:: #(#parent_segments ::)* #resolver_mod::*;
		}
	}
}

/// Extract the metadata macro identifier from an endpoint path.
///
/// Given `views::login`, returns the identifier `__url_resolver_meta_login`.
/// The caller is responsible for qualifying the path (via `$base` in the
/// `__for_each_url_resolver` macro).
fn build_meta_ident(path: &TokenStream) -> Option<syn::Ident> {
	let parsed: syn::Path = syn::parse2(path.clone()).ok()?;
	let last_segment = &parsed.segments.last()?.ident;
	Some(syn::Ident::new(
		&format!("__url_resolver_meta_{last_segment}"),
		last_segment.span(),
	))
}

/// Build a re-export statement for a viewset's URL resolver bundle module.
///
/// Given a viewset call path like `views::viewset` (already stripped of
/// trailing `()`), extracts the function name (`viewset`) to reference the
/// `__viewset_resolvers_viewset` bundle module generated by `#[viewset]`.
///
/// The bundle module lives as a sibling of the annotated free function,
/// so only the function name (last segment) is stripped to get the module path.
fn build_viewset_reexport(call: &ViewSetCall) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(call.expr_path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	let last_segment = &parsed.segments.last().unwrap().ident;
	let bundle_mod = syn::Ident::new(
		&format!("__viewset_resolvers_{last_segment}"),
		last_segment.span(),
	);

	// Strip the function name to get the module path.
	// For `views::viewset`, module = `views`.
	let module_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute = first_segment == "crate" || first_segment == "super";

	if is_absolute {
		if module_segments.is_empty() {
			quote! { pub use #bundle_mod::*; }
		} else {
			quote! { pub use #(#module_segments ::)* #bundle_mod::*; }
		}
	} else if module_segments.is_empty() {
		quote! { pub use super::#bundle_mod::*; }
	} else {
		quote! { pub use super:: #(#module_segments ::)* #bundle_mod::*; }
	}
}

/// Build a re-export statement for a mounted child router's `url_resolvers` module.
///
/// Given a mount path like `crate::apps::api::urls::url_patterns` (already
/// stripped of trailing `()`), strips the function name and re-exports
/// `url_resolvers::*` from the parent module.
fn build_mount_reexport(call: &MountCall) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(call.expr_path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	// Strip the last segment (the function name, e.g., `url_patterns`)
	let module_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	if module_segments.is_empty() {
		return quote! {};
	}

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute = first_segment == "crate" || first_segment == "super";

	if is_absolute {
		quote! {
			pub use #(#module_segments ::)* url_resolvers::*;
		}
	} else {
		quote! {
			pub use super:: #(#module_segments ::)* url_resolvers::*;
		}
	}
}

/// Implementation of the `#[url_patterns]` attribute macro.
///
/// Optionally accepts an app label string: `#[url_patterns("users")]`.
/// When provided, the returned router is wrapped with `.with_namespace("users")`
/// to enable per-app route name namespacing (Issue #3526).
pub(crate) fn url_patterns_impl(args: TokenStream, input: TokenStream) -> syn::Result<TokenStream> {
	let func: ItemFn = parse2(input)?;

	let endpoint_paths = extract_endpoint_paths(&func);
	let viewset_calls = extract_viewset_calls(&func);
	let mount_calls = extract_mount_calls(&func);

	let endpoint_re_exports = endpoint_paths.iter().map(build_resolver_reexport);
	let viewset_re_exports = viewset_calls.iter().map(build_viewset_reexport);
	let mount_re_exports = mount_calls.iter().map(build_mount_reexport);
	let meta_idents: Vec<syn::Ident> = endpoint_paths.iter().filter_map(build_meta_ident).collect();

	// Parse optional app label: #[url_patterns("users")]
	let func_output = if !args.is_empty() {
		let app_label: syn::LitStr = syn::parse2(args)?;
		let fn_vis = &func.vis;
		let fn_attrs = &func.attrs;
		let fn_sig = &func.sig;
		let fn_block = &func.block;

		// Wrap the function to apply with_namespace
		quote! {
			#(#fn_attrs)*
			#fn_vis #fn_sig {
				let __router = (|| #fn_block)();
				__router.with_namespace(#app_label)
			}
		}
	} else {
		// No app label — emit function unchanged (backward compatible)
		quote! { #func }
	};

	Ok(quote! {
		#func_output

		#[doc(hidden)]
		pub mod url_resolvers {
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#endpoint_re_exports
			)*
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#viewset_re_exports
			)*
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#mount_re_exports
			)*

			/// Invoke a callback macro for each URL resolver in this app.
			/// Used by the `#[routes]` macro to build per-app resolver structs.
			/// `$base` must be the absolute path to this `url_resolvers` module
			/// so that the metadata macros resolve at the call site.
			#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
			macro_rules! __for_each_url_resolver {
				($callback:ident, $app:ident, $base:path) => {
					#(
						$base :: #meta_idents ! ($callback, $app);
					)*
				};
			}
			#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
			pub(crate) use __for_each_url_resolver;
		}
	})
}

#[cfg(test)]
mod tests {
	use super::*;

	// === Endpoint extraction (existing tests) ===

	#[test]
	fn extract_single_endpoint() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
			}
		})
		.unwrap();

		let paths = extract_endpoint_paths(&func);
		assert_eq!(paths.len(), 1);
		assert_eq!(paths[0].to_string(), "views :: login");
	}

	#[test]
	fn extract_multiple_endpoints() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
					.endpoint(views::register)
					.endpoint(views::profile)
			}
		})
		.unwrap();

		let paths = extract_endpoint_paths(&func);
		assert_eq!(paths.len(), 3);
	}

	#[test]
	fn extract_no_endpoints() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
			}
		})
		.unwrap();

		let paths = extract_endpoint_paths(&func);
		assert_eq!(paths.len(), 0);
	}

	#[test]
	fn extract_endpoints_mixed_with_other_calls() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.with_middleware(auth_middleware)
					.endpoint(views::login)
					.endpoint(views::register)
			}
		})
		.unwrap();

		let paths = extract_endpoint_paths(&func);
		assert_eq!(paths.len(), 2);
	}

	// === Endpoint reexport (existing tests) ===

	#[test]
	fn build_reexport_relative_path() {
		let path: TokenStream = quote! { views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_crate_path() {
		let path: TokenStream = quote! { crate::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use crate :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_super_path() {
		let path: TokenStream = quote! { super::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_deeply_nested_path() {
		let path: TokenStream = quote! { api::v1::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: api :: v1 :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	// --- Meta ident tests (Issue #3647) ---

	#[test]
	fn build_meta_ident_relative_path() {
		let path: TokenStream = quote! { views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	#[test]
	fn build_meta_ident_crate_path() {
		let path: TokenStream = quote! { crate::views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	#[test]
	fn build_meta_ident_deeply_nested() {
		let path: TokenStream = quote! { api::v1::views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	#[test]
	fn url_patterns_impl_generates_for_each_macro() {
		let input = quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
					.endpoint(views::register)
			}
		};

		let result = url_patterns_impl(quote! {}, input).unwrap();
		let output = result.to_string();

		assert!(
			output.contains("__for_each_url_resolver"),
			"missing __for_each_url_resolver macro"
		);
		assert!(
			output.contains("$base"),
			"missing $base parameter in __for_each_url_resolver"
		);
		assert!(
			output.contains("__url_resolver_meta_login"),
			"missing login meta ident"
		);
		assert!(
			output.contains("__url_resolver_meta_register"),
			"missing register meta ident"
		);
	}

	#[test]
	fn url_patterns_with_app_label_wraps_namespace() {
		let input = quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
			}
		};

		let result = url_patterns_impl(quote! { "users" }, input).unwrap();
		let output = result.to_string();

		assert!(
			output.contains("with_namespace"),
			"missing with_namespace call"
		);
	}

	#[test]
	fn url_patterns_without_app_label_no_namespace() {
		let input = quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
			}
		};

		let result = url_patterns_impl(quote! {}, input).unwrap();
		let output = result.to_string();

		assert!(
			!output.contains("with_namespace"),
			"should not have with_namespace without label"
		);
	}

	// === ViewSet extraction ===

	#[test]
	fn extract_viewset_single() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.viewset("/snippets", views::viewset())
			}
		})
		.unwrap();

		let calls = extract_viewset_calls(&func);
		assert_eq!(calls.len(), 1);
		let path_str = calls[0].expr_path.to_string();
		assert!(path_str.contains("views"));
		assert!(path_str.contains("viewset"));
		// Trailing `()` should be stripped
		assert!(!path_str.ends_with("()"));
	}

	#[test]
	fn extract_viewset_none() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello)
			}
		})
		.unwrap();

		let calls = extract_viewset_calls(&func);
		assert_eq!(calls.len(), 0);
	}

	#[test]
	fn extract_viewset_multiple() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.viewset("/users", views::user_viewset())
					.viewset("/posts", views::post_viewset())
			}
		})
		.unwrap();

		let calls = extract_viewset_calls(&func);
		assert_eq!(calls.len(), 2);
	}

	// === Mount extraction ===

	#[test]
	fn extract_mount_single() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.mount("/api/", crate::apps::api::urls::url_patterns())
			}
		})
		.unwrap();

		let calls = extract_mount_calls(&func);
		assert_eq!(calls.len(), 1);
		let path_str = calls[0].expr_path.to_string();
		assert!(path_str.contains("apps"));
		assert!(path_str.contains("url_patterns"));
	}

	#[test]
	fn extract_mount_none() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello)
			}
		})
		.unwrap();

		let calls = extract_mount_calls(&func);
		assert_eq!(calls.len(), 0);
	}

	// === ViewSet reexport ===

	#[test]
	fn build_viewset_reexport_relative() {
		let call = ViewSetCall {
			expr_path: quote! { views::viewset },
		};
		let result = build_viewset_reexport(&call);
		let output = result.to_string();
		assert!(output.contains("__viewset_resolvers_viewset"));
		assert!(output.contains("super :: views"));
	}

	#[test]
	fn build_viewset_reexport_crate_path() {
		let call = ViewSetCall {
			expr_path: quote! { crate::apps::snippets::views::viewset },
		};
		let result = build_viewset_reexport(&call);
		let output = result.to_string();
		assert!(
			output.contains("crate :: apps :: snippets :: views :: __viewset_resolvers_viewset")
		);
	}

	// === Mount reexport ===

	#[test]
	fn build_mount_reexport_crate_path() {
		let call = MountCall {
			expr_path: quote! { crate::apps::api::urls::url_patterns },
		};
		let result = build_mount_reexport(&call);
		let expected = "pub use crate :: apps :: api :: urls :: url_resolvers :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_mount_reexport_relative_path() {
		let call = MountCall {
			expr_path: quote! { api::urls::url_patterns },
		};
		let result = build_mount_reexport(&call);
		let expected = "pub use super :: api :: urls :: url_resolvers :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	// === Combined extraction ===

	#[test]
	fn extract_all_types_combined() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello_world)
					.viewset("/snippets", views::viewset())
					.mount("/api/", crate::apps::api::urls::url_patterns())
			}
		})
		.unwrap();

		assert_eq!(extract_endpoint_paths(&func).len(), 1);
		assert_eq!(extract_viewset_calls(&func).len(), 1);
		assert_eq!(extract_mount_calls(&func).len(), 1);
	}

	// === Nested control flow extraction (Issue #3648) ===

	#[test]
	fn extract_endpoints_inside_if_else() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				if std::env::var("USE_VIEWSET").is_ok() {
					ServerRouter::new()
						.viewset("/snippets-viewset", views::viewset())
				} else {
					ServerRouter::new()
						.endpoint(views::list)
						.endpoint(views::create)
						.endpoint(views::retrieve)
				}
			}
		})
		.unwrap();

		let endpoints = extract_endpoint_paths(&func);
		assert_eq!(endpoints.len(), 3);
		assert_eq!(endpoints[0].to_string(), "views :: list");
		assert_eq!(endpoints[1].to_string(), "views :: create");
		assert_eq!(endpoints[2].to_string(), "views :: retrieve");

		let viewsets = extract_viewset_calls(&func);
		assert_eq!(viewsets.len(), 1);
	}

	#[test]
	fn extract_endpoints_inside_match() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				match mode {
					Mode::Full => {
						ServerRouter::new()
							.endpoint(views::list)
							.endpoint(views::create)
					}
					Mode::Readonly => {
						ServerRouter::new()
							.endpoint(views::list)
					}
				}
			}
		})
		.unwrap();

		let endpoints = extract_endpoint_paths(&func);
		assert_eq!(endpoints.len(), 3);
	}

	#[test]
	fn extract_mounts_inside_control_flow() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				if enabled {
					ServerRouter::new()
						.mount("/api/", crate::apps::api::urls::url_patterns())
				} else {
					ServerRouter::new()
				}
			}
		})
		.unwrap();

		let mounts = extract_mount_calls(&func);
		assert_eq!(mounts.len(), 1);
	}
}
