//! Implementation of the `#[url_patterns]` attribute macro.
//!
//! # Syntax (Issue #3670)
//!
//! ```text
//! #[url_patterns(<InstalledApp::variant>, mode = server|client|unified)]
//! ```
//!
//! The first argument is a path to a variant of an enum implementing
//! `reinhardt_apps::apps::AppLabel` — normally the `InstalledApp` enum
//! generated by the `installed_apps!` macro, which auto-implements
//! `AppLabel` for its generated variants. Generated wrappers resolve
//! the runtime namespace through the trait:
//!
//! ```text
//! __router.with_namespace(<T as AppLabel>::path(&<InstalledApp::variant>))
//! ```
//!
//! A compile-time trait-bound assertion is also emitted, so paths that
//! do not resolve to an `AppLabel` implementor fail to compile with a
//! clear `the trait bound is not satisfied` error.
//!
//! # Modes
//!
//! | mode      | Router         | Scanned calls                                  | Resolver module(s)                             |
//! |-----------|----------------|-----------------------------------------------|------------------------------------------------|
//! | `server`  | `ServerRouter` | `.endpoint()`, `.viewset()`, `.mount()`        | `url_resolvers`                                 |
//! | `client`  | `ClientRouter` | `.named_route()` family                        | `client_url_resolvers`                          |
//! | `unified` | `UnifiedRouter`| both sides (inside `.server(\|s\|)` / `.client(\|c\|)` closures) | `url_resolvers` + `client_url_resolvers` |

use proc_macro2::TokenStream;
use quote::quote;
use syn::{ItemFn, parse2};

/// Generate a `__for_each_*` callback dispatch macro.
///
/// Produces a `macro_rules!` definition that iterates over `meta_idents`,
/// invoking `$base :: $meta_ident ! ($callback, $app)` for each.
///
/// `native_only` controls whether the emitted macro is gated to non-wasm
/// targets. Server (`__for_each_url_resolver`) and ws
/// (`__for_each_ws_url_resolver`) modes are native-only because they depend on
/// `ServerRouter`. Client (`__for_each_client_url_resolver`) mode must be
/// available on wasm so that `urls.client().<app>().<route>()` typed accessors
/// can be generated for SPA targets (issue #4119).
fn gen_for_each_macro(
	macro_name: &proc_macro2::Ident,
	meta_idents: &[syn::Ident],
	native_only: bool,
) -> TokenStream {
	let gate = if native_only {
		quote! { #[cfg(not(all(target_family = "wasm", target_os = "unknown")))] }
	} else {
		quote! {}
	};
	quote! {
		#gate
		macro_rules! #macro_name {
			($callback:ident, $app:ident, $($base:tt)+) => {
				#(
					$($base)+ :: #meta_idents ! ($callback, $app);
				)*
			};
		}
		#gate
		pub(crate) use #macro_name;
	}
}

/// Flatten a function body into a flat token stream for pattern scanning.
///
/// Recursively descends into `Group` tokens (braces, parentheses, brackets)
/// so that `.endpoint()`, `.viewset()`, and `.mount()` calls inside control
/// flow blocks (`if`, `match`, `for`, etc.) are detected.
fn flatten_body(func: &ItemFn) -> Vec<proc_macro2::TokenTree> {
	fn recurse(
		tokens: impl IntoIterator<Item = proc_macro2::TokenTree>,
	) -> Vec<proc_macro2::TokenTree> {
		let mut result = Vec::new();
		for tt in tokens {
			match &tt {
				proc_macro2::TokenTree::Group(group) => {
					result.push(tt.clone());
					result.extend(recurse(group.stream()));
				}
				_ => result.push(tt),
			}
		}
		result
	}

	func.block
		.stmts
		.iter()
		.flat_map(|stmt| {
			let tokens: TokenStream = quote! { #stmt };
			recurse(tokens)
		})
		.collect()
}

/// Extract endpoint path expressions from flattened body tokens.
///
/// Scans tokens for `.endpoint(EXPR)` patterns and returns
/// the path expressions.
fn extract_endpoint_paths(body_tokens: &[proc_macro2::TokenTree]) -> Vec<TokenStream> {
	let mut paths = Vec::new();

	let mut i = 0;
	while i < body_tokens.len() {
		// Look for: Punct('.') Ident("endpoint") Group(Parenthesized)
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == "endpoint"
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			paths.push(group.stream());
			i += 3;
			continue;
		}
		i += 1;
	}
	paths
}

/// Extract `.consumer(EXPR)` calls from flattened body tokens.
///
/// Parallel to `extract_endpoint_paths()` for WebSocket routes.
/// Returns the factory function path expressions.
fn extract_consumer_paths(body_tokens: &[proc_macro2::TokenTree]) -> Vec<TokenStream> {
	let mut paths = Vec::new();
	let mut i = 0;
	while i < body_tokens.len() {
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == "consumer"
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			paths.push(group.stream());
			i += 3;
			continue;
		}
		i += 1;
	}
	paths
}

/// A chained method call extracted from the function body.
///
/// Used for both `.viewset(STR, EXPR)` and `.mount(STR, EXPR)` patterns,
/// which share the same structure: a string literal first argument and a
/// path expression second argument (with trailing `()` stripped).
///
/// Example: `.viewset("/snippets", views::viewset())`
/// yields `ChainCall { expr_path: "views :: viewset" }`.
struct ChainCall {
	expr_path: TokenStream,
}

/// Extract chained method calls matching `.method_name(STR, EXPR)` from flattened body tokens.
///
/// Scans for the pattern `.{method_name}(string_literal, path_expr(...))` and
/// returns the second argument's path (stripping the trailing `()` call).
/// Used for both `viewset` and `mount` extraction.
fn extract_chain_calls(
	body_tokens: &[proc_macro2::TokenTree],
	method_name: &str,
) -> Vec<ChainCall> {
	let mut calls = Vec::new();

	let mut i = 0;
	while i < body_tokens.len() {
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& ident == method_name
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			// Group contains: STR_LITERAL, EXPR (possibly with trailing `()`)
			let mut found_comma = false;
			let mut expr_tokens = Vec::new();
			for tt in group.stream() {
				if found_comma {
					// Skip trailing parenthesized group (the `()` function call)
					if let proc_macro2::TokenTree::Group(g) = &tt
						&& g.delimiter() == proc_macro2::Delimiter::Parenthesis
					{
						continue;
					}
					expr_tokens.push(tt);
				} else if let proc_macro2::TokenTree::Punct(p) = &tt
					&& p.as_char() == ','
				{
					found_comma = true;
				}
			}
			if !expr_tokens.is_empty() {
				let expr_path: TokenStream = expr_tokens.into_iter().collect();
				calls.push(ChainCall { expr_path });
			}
			i += 3;
			continue;
		}
		i += 1;
	}
	calls
}

/// Build a re-export statement for a URL resolver module from an endpoint path.
///
/// Given an endpoint path like `views::login`, generates:
/// `pub use super::views::__url_resolver_login::*;`
///
/// For absolute paths starting with `crate::` or `super::`, the `super::` prefix is omitted:
/// `pub use crate::views::__url_resolver_login::*;`
fn build_resolver_reexport(path: &TokenStream) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	let last_segment = &parsed.segments.last().unwrap().ident;
	let resolver_mod = syn::Ident::new(
		&format!("__url_resolver_{last_segment}"),
		last_segment.span(),
	);

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute =
		first_segment == "crate" || first_segment == "super" || parsed.leading_colon.is_some();

	let parent_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	if is_absolute {
		quote! {
			pub use #(#parent_segments ::)* #resolver_mod::*;
		}
	} else {
		quote! {
			pub use super:: #(#parent_segments ::)* #resolver_mod::*;
		}
	}
}

/// Extract the metadata macro identifier from an endpoint path.
///
/// Given `views::login`, returns the identifier `__url_resolver_meta_login`.
/// The caller is responsible for qualifying the path (via `$base` in the
/// `__for_each_url_resolver` macro).
fn build_meta_ident(path: &TokenStream) -> Option<syn::Ident> {
	let parsed: syn::Path = syn::parse2(path.clone()).ok()?;
	let last_segment = &parsed.segments.last()?.ident;
	Some(syn::Ident::new(
		&format!("__url_resolver_meta_{last_segment}"),
		last_segment.span(),
	))
}

/// Build a re-export statement for a viewset's URL resolver bundle module.
///
/// Given a viewset call path like `views::viewset` (already stripped of
/// trailing `()`), extracts the function name (`viewset`) to reference the
/// `__viewset_resolvers_viewset` bundle module generated by `#[viewset]`.
///
/// The bundle module lives as a sibling of the annotated free function,
/// so only the function name (last segment) is stripped to get the module path.
fn build_viewset_reexport(call: &ChainCall) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(call.expr_path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	let last_segment = &parsed.segments.last().unwrap().ident;
	let bundle_mod = syn::Ident::new(
		&format!("__viewset_resolvers_{last_segment}"),
		last_segment.span(),
	);

	// Strip the function name to get the module path.
	// For `views::viewset`, module = `views`.
	let module_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute = first_segment == "crate" || first_segment == "super";

	if is_absolute {
		if module_segments.is_empty() {
			quote! { pub use #bundle_mod::*; }
		} else {
			quote! { pub use #(#module_segments ::)* #bundle_mod::*; }
		}
	} else if module_segments.is_empty() {
		quote! { pub use super::#bundle_mod::*; }
	} else {
		quote! { pub use super:: #(#module_segments ::)* #bundle_mod::*; }
	}
}

/// Build a re-export statement for a mounted child router's `url_resolvers` module.
///
/// Given a mount path like `crate::apps::api::urls::url_patterns` (already
/// stripped of trailing `()`), strips the function name and re-exports
/// `url_resolvers::*` from the parent module.
fn build_mount_reexport(call: &ChainCall) -> TokenStream {
	let parsed: syn::Path = match syn::parse2(call.expr_path.clone()) {
		Ok(p) => p,
		Err(_) => return quote! {},
	};

	if parsed.segments.is_empty() {
		return quote! {};
	}

	// Strip the last segment (the function name, e.g., `url_patterns`)
	let module_segments: Vec<&syn::Ident> = parsed
		.segments
		.iter()
		.take(parsed.segments.len() - 1)
		.map(|s| &s.ident)
		.collect();

	if module_segments.is_empty() {
		return quote! {};
	}

	let first_segment = parsed.segments.first().unwrap().ident.to_string();
	let is_absolute = first_segment == "crate" || first_segment == "super";

	if is_absolute {
		quote! {
			pub use #(#module_segments ::)* url_resolvers::*;
		}
	} else {
		quote! {
			pub use super:: #(#module_segments ::)* url_resolvers::*;
		}
	}
}

/// A named client route extracted from the function body.
///
/// Example: `.named_route("login_page", "/login/", handler)`
/// yields `ClientNamedRoute { name: "login_page", pattern: "/login/" }`.
struct ClientNamedRoute {
	name: String,
	pattern: String,
}

/// Extract `.named_route(NAME, PATTERN, HANDLER)` calls from a function body.
///
/// Scans for the pattern `.named_route("name", "/pattern/", expr)` and
/// extracts the route name and URL pattern strings.
fn extract_named_route_calls(body_tokens: &[proc_macro2::TokenTree]) -> Vec<ClientNamedRoute> {
	let mut routes = Vec::new();

	let mut i = 0;
	while i < body_tokens.len() {
		if i + 2 < body_tokens.len()
			&& let proc_macro2::TokenTree::Punct(p) = &body_tokens[i]
			&& p.as_char() == '.'
			&& let proc_macro2::TokenTree::Ident(ident) = &body_tokens[i + 1]
			&& (ident == "named_route"
				|| ident == "named_route_path"
				|| ident == "named_route_path2"
				|| ident == "named_route_path3"
				|| ident == "named_route_params"
				|| ident == "named_route_result")
			&& let proc_macro2::TokenTree::Group(group) = &body_tokens[i + 2]
			&& group.delimiter() == proc_macro2::Delimiter::Parenthesis
		{
			// Parse the first two string literal arguments: name, pattern
			let inner_tokens: Vec<proc_macro2::TokenTree> = group.stream().into_iter().collect();
			if let Some(route) = parse_named_route_args(&inner_tokens) {
				routes.push(route);
			}
			i += 3;
			continue;
		}
		i += 1;
	}
	routes
}

/// Parse the arguments of a `named_route(name, pattern, ...)` call.
///
/// Extracts the first two string literals (name and pattern).
fn parse_named_route_args(tokens: &[proc_macro2::TokenTree]) -> Option<ClientNamedRoute> {
	let mut literals = Vec::new();
	for tt in tokens {
		if let proc_macro2::TokenTree::Literal(lit) = tt {
			let lit_str = lit.to_string();
			// Check if it's a string literal (starts and ends with ")
			if lit_str.starts_with('"') && lit_str.ends_with('"') && lit_str.len() >= 2 {
				literals.push(lit_str[1..lit_str.len() - 1].to_string());
				if literals.len() == 2 {
					break;
				}
			}
		}
	}

	if literals.len() >= 2 {
		Some(ClientNamedRoute {
			name: literals[0].clone(),
			pattern: literals[1].clone(),
		})
	} else {
		None
	}
}

/// Extract URL parameter names from a pattern string.
///
/// Given `/users/{id}/posts/{post_id}/`, returns `["id", "post_id"]`.
fn extract_url_params(pattern: &str) -> Vec<String> {
	let mut params = Vec::new();
	let mut in_param = false;
	let mut name = String::new();
	for ch in pattern.chars() {
		match ch {
			'{' => {
				in_param = true;
				name.clear();
			}
			'}' => {
				if in_param && !name.is_empty() {
					// Strip type constraint (e.g., "{id:int}" → "id")
					if let Some(pos) = name.find(':') {
						name.truncate(pos);
					}
					params.push(name.clone());
				}
				in_param = false;
			}
			_ if in_param => name.push(ch),
			_ => {}
		}
	}
	params
}

/// Parsed arguments for `#[url_patterns]`.
struct UrlPatternsArgs {
	/// Path to an `InstalledApp` enum variant (e.g.
	/// `crate::config::apps::InstalledApp::auth`).
	app_path: syn::ExprPath,
	/// Routing mode dictating which calls to scan and which resolver modules
	/// to emit.
	mode: UrlPatternsMode,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum UrlPatternsMode {
	Server,
	Client,
	Unified,
	Ws,
}

/// Parse `#[url_patterns]` arguments.
///
/// Accepted form (Issue #3670):
///   `#[url_patterns(<InstalledApp::variant>, mode = server|client|unified)]`
fn parse_url_patterns_args(args: TokenStream) -> syn::Result<UrlPatternsArgs> {
	if args.is_empty() {
		return Err(syn::Error::new(
			proc_macro2::Span::call_site(),
			"`#[url_patterns]` requires two arguments: an InstalledApp variant and a mode.\n\
			 \n  Example: #[url_patterns(InstalledApp::auth, mode = server)]\n  \
			 Valid modes: `server`, `client`, `unified`",
		));
	}

	let parser = |input: syn::parse::ParseStream<'_>| -> syn::Result<UrlPatternsArgs> {
		let app_path: syn::ExprPath = input.parse()?;
		input.parse::<syn::Token![,]>()?;
		let key: syn::Ident = input.parse()?;
		if key != "mode" {
			return Err(syn::Error::new(
				key.span(),
				"expected `mode = server|client|unified`",
			));
		}
		input.parse::<syn::Token![=]>()?;
		let mode_ident: syn::Ident = input.parse()?;
		let mode = match mode_ident.to_string().as_str() {
			"server" => UrlPatternsMode::Server,
			"client" => UrlPatternsMode::Client,
			"unified" => UrlPatternsMode::Unified,
			"ws" => UrlPatternsMode::Ws,
			other => {
				return Err(syn::Error::new(
					mode_ident.span(),
					format!(
						"unknown mode `{other}`, expected `server`, `client`, `unified`, or `ws`"
					),
				));
			}
		};
		// Allow optional trailing comma.
		if input.peek(syn::Token![,]) {
			input.parse::<syn::Token![,]>()?;
		}
		Ok(UrlPatternsArgs { app_path, mode })
	};

	syn::parse::Parser::parse2(parser, args)
}

/// Returns `(enum_type_path, variant_path)` from an `InstalledApp::variant`-shaped
/// expression path.
///
/// For `crate::config::apps::InstalledApp::auth`, yields
/// (`crate::config::apps::InstalledApp`, `crate::config::apps::InstalledApp::auth`).
fn split_enum_type_and_variant(app_path: &syn::ExprPath) -> syn::Result<(syn::Path, syn::Path)> {
	if app_path.path.segments.len() < 2 {
		return Err(syn::Error::new_spanned(
			app_path,
			"expected a path of the form `InstalledApp::variant` (at least two segments)",
		));
	}

	// Rebuild the enum-type path by collecting all but the final variant
	// segment back into a `Punctuated`. The `FromIterator<T>` impl inserts a
	// default separator between elements and leaves no trailing punctuation,
	// yielding a well-formed path (cf. raw `Punctuated::pop`, which preserves
	// the trailing separator and would emit an invalid `A::B::`).
	let segments: syn::punctuated::Punctuated<_, syn::Token![::]> = app_path
		.path
		.segments
		.iter()
		.take(app_path.path.segments.len() - 1)
		.cloned()
		.collect();
	let type_path = syn::Path {
		leading_colon: app_path.path.leading_colon,
		segments,
	};
	Ok((type_path, app_path.path.clone()))
}

/// Build `url_resolvers` module body for server-side scanning of a function body.
fn build_server_resolvers(body_tokens: &[proc_macro2::TokenTree]) -> TokenStream {
	let endpoint_paths = extract_endpoint_paths(body_tokens);
	let viewset_calls = extract_chain_calls(body_tokens, "viewset");
	let mount_calls = extract_chain_calls(body_tokens, "mount");

	let endpoint_re_exports: Vec<_> = endpoint_paths.iter().map(build_resolver_reexport).collect();
	let viewset_re_exports: Vec<_> = viewset_calls.iter().map(build_viewset_reexport).collect();
	let mount_re_exports: Vec<_> = mount_calls.iter().map(build_mount_reexport).collect();
	let meta_idents: Vec<syn::Ident> = endpoint_paths.iter().filter_map(build_meta_ident).collect();
	let for_each_resolver_macro = gen_for_each_macro(
		&syn::Ident::new("__for_each_url_resolver", proc_macro2::Span::call_site()),
		&meta_idents,
		true,
	);

	quote! {
		#[doc(hidden)]
		pub mod url_resolvers {
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#endpoint_re_exports
			)*
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#viewset_re_exports
			)*
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#mount_re_exports
			)*

			#for_each_resolver_macro
		}
	}
}

/// Build `client_url_resolvers` module body for client-side scanning of a function body.
fn build_client_resolvers(body_tokens: &[proc_macro2::TokenTree]) -> syn::Result<TokenStream> {
	let named_routes = extract_named_route_calls(body_tokens);
	let mut meta_macro_defs: Vec<TokenStream> = Vec::new();
	let mut meta_idents: Vec<syn::Ident> = Vec::new();

	for route in &named_routes {
		if syn::parse_str::<syn::Ident>(&route.name).is_err() {
			return Err(syn::Error::new(
				proc_macro2::Span::call_site(),
				format!(
					"Client route name `{}` is not a valid Rust identifier. \
					 Route names must be valid identifiers (no hyphens, dots, or leading digits).",
					route.name
				),
			));
		}

		let method_ident = syn::Ident::new(&route.name, proc_macro2::Span::call_site());
		let route_name_str = &route.name;
		let meta_macro_ident = syn::Ident::new(
			&format!("__client_url_resolver_meta_{}", route.name),
			proc_macro2::Span::call_site(),
		);

		let params = extract_url_params(&route.pattern);
		let param_strs: Vec<&str> = params.iter().map(|s| s.as_str()).collect();

		let meta_def = if params.is_empty() {
			quote! {
				#[doc(hidden)]
				macro_rules! #meta_macro_ident {
					($callback:ident, $app:ident) => {
						$callback!($app, #method_ident, #route_name_str, );
					};
				}
				pub(crate) use #meta_macro_ident;
			}
		} else {
			quote! {
				#[doc(hidden)]
				macro_rules! #meta_macro_ident {
					($callback:ident, $app:ident) => {
						$callback!($app, #method_ident, #route_name_str, #(#param_strs),* );
					};
				}
				pub(crate) use #meta_macro_ident;
			}
		};

		meta_macro_defs.push(meta_def);
		meta_idents.push(meta_macro_ident);
	}

	// Client resolvers are cross-target (native + wasm) so that
	// `urls.client().<app>().<route>()` typed accessors compile on
	// `wasm32-unknown-unknown`. Server / ws resolvers stay native-only.
	// Fixes #4119.
	let for_each_client_resolver_macro = gen_for_each_macro(
		&syn::Ident::new(
			"__for_each_client_url_resolver",
			proc_macro2::Span::call_site(),
		),
		&meta_idents,
		false,
	);

	Ok(quote! {
		#[doc(hidden)]
		pub mod client_url_resolvers {
			#(
				#meta_macro_defs
			)*

			#for_each_client_resolver_macro
		}
	})
}

/// Implementation of the `#[url_patterns]` attribute macro.
///
/// Supports three modes, dispatched by the required `mode = ...` argument:
///
/// - `#[url_patterns(InstalledApp::variant, mode = server)]` — scans for
///   `.endpoint()`, `.viewset()`, `.mount()` calls on a `ServerRouter`;
///   generates the `url_resolvers` module.
/// - `#[url_patterns(InstalledApp::variant, mode = client)]` — scans for
///   `.named_route()` family calls on a `ClientRouter`; generates the
///   `client_url_resolvers` module.
/// - `#[url_patterns(InstalledApp::variant, mode = unified)]` — scans both
///   inside `.server(|s| ...)` and `.client(|c| ...)` closures on a
///   `UnifiedRouter`; emits both resolver modules.
///
/// The first argument must be a path to a variant of an enum implementing
/// `reinhardt_apps::apps::AppLabel` (auto-implemented by `installed_apps!`).
/// A compile-time trait-bound assertion is emitted to enforce this.
pub(crate) fn url_patterns_impl(args: TokenStream, input: TokenStream) -> syn::Result<TokenStream> {
	let parsed_args = parse_url_patterns_args(args)?;
	match parsed_args.mode {
		UrlPatternsMode::Server => url_patterns_server_impl(parsed_args, input),
		UrlPatternsMode::Client => url_patterns_client_impl(parsed_args, input),
		UrlPatternsMode::Unified => url_patterns_unified_impl(parsed_args, input),
		UrlPatternsMode::Ws => url_patterns_ws_impl(parsed_args, input),
	}
}

/// Build the wrapper function + trait assertion shared by all three modes.
fn build_wrapper_and_assertion(
	func: &ItemFn,
	app_path: &syn::ExprPath,
) -> syn::Result<(TokenStream, TokenStream)> {
	let (type_path, variant_path) = split_enum_type_and_variant(app_path)?;
	let apps_crate = crate::crate_paths::get_reinhardt_apps_crate();

	let fn_vis = &func.vis;
	let fn_attrs = &func.attrs;
	let fn_sig = &func.sig;
	let fn_block = &func.block;

	let wrapper = quote! {
		#(#fn_attrs)*
		#fn_vis #fn_sig {
			let __router = (|| #fn_block)();
			__router.with_namespace(
				<#type_path as #apps_crate::apps::AppLabel>::path(&#variant_path)
			)
		}
	};

	let trait_assertion = quote! {
		const _: fn() = || {
			fn __assert_app_label<T: #apps_crate::apps::AppLabel>(_: T) {}
			__assert_app_label(#variant_path);
		};
	};

	Ok((wrapper, trait_assertion))
}

/// Server-mode implementation: emits `url_resolvers` module.
fn url_patterns_server_impl(
	parsed_args: UrlPatternsArgs,
	input: TokenStream,
) -> syn::Result<TokenStream> {
	let func: ItemFn = parse2(input)?;
	let body_tokens = flatten_body(&func);
	let resolvers = build_server_resolvers(&body_tokens);
	let (wrapper, trait_assertion) = build_wrapper_and_assertion(&func, &parsed_args.app_path)?;

	Ok(quote! {
		#wrapper
		#trait_assertion
		#resolvers
	})
}

/// Client-mode implementation: emits `client_url_resolvers` module.
fn url_patterns_client_impl(
	parsed_args: UrlPatternsArgs,
	input: TokenStream,
) -> syn::Result<TokenStream> {
	let func: ItemFn = parse2(input)?;
	let body_tokens = flatten_body(&func);
	let resolvers = build_client_resolvers(&body_tokens)?;
	let (wrapper, trait_assertion) = build_wrapper_and_assertion(&func, &parsed_args.app_path)?;

	Ok(quote! {
		#wrapper
		#trait_assertion
		#resolvers
	})
}

/// Build `ws_url_resolvers` module for WebSocket mode.
/// Parallel to `build_server_resolvers()`, but uses `__ws_url_resolver_*` names.
fn build_ws_resolvers(body_tokens: &[proc_macro2::TokenTree]) -> TokenStream {
	let consumer_paths = extract_consumer_paths(body_tokens);
	let re_exports: Vec<_> = consumer_paths
		.iter()
		.map(|path| {
			let parsed: syn::Path = match syn::parse2(path.clone()) {
				Ok(p) => p,
				Err(_) => {
					return syn::Error::new_spanned(
						path,
						"`.consumer(...)` argument must be a path to a handler function",
					)
					.to_compile_error();
				}
			};
			if parsed.segments.is_empty() {
				return quote! {};
			}
			let last_segment = &parsed.segments.last().unwrap().ident;
			let resolver_mod = syn::Ident::new(
				&format!("__ws_url_resolver_{last_segment}"),
				last_segment.span(),
			);
			let first_segment = parsed.segments.first().unwrap().ident.to_string();
			let is_absolute = first_segment == "crate"
				|| first_segment == "super"
				|| parsed.leading_colon.is_some();
			let parent_segments: Vec<&syn::Ident> = parsed
				.segments
				.iter()
				.take(parsed.segments.len() - 1)
				.map(|s| &s.ident)
				.collect();
			if is_absolute {
				quote! { pub use #(#parent_segments ::)* #resolver_mod::*; }
			} else {
				quote! { pub use super:: #(#parent_segments ::)* #resolver_mod::*; }
			}
		})
		.collect();

	let meta_idents: Vec<syn::Ident> = consumer_paths
		.iter()
		.filter_map(|path| {
			let parsed: syn::Path = syn::parse2(path.clone()).ok()?;
			let last = &parsed.segments.last()?.ident;
			Some(syn::Ident::new(
				&format!("__ws_url_resolver_meta_{last}"),
				last.span(),
			))
		})
		.collect();

	let for_each_macro = gen_for_each_macro(
		&syn::Ident::new("__for_each_ws_url_resolver", proc_macro2::Span::call_site()),
		&meta_idents,
		true,
	);

	quote! {
		#[doc(hidden)]
		pub mod ws_url_resolvers {
			#(
				#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
				#re_exports
			)*
			#for_each_macro
		}
	}
}

/// WebSocket-mode implementation: emits `ws_url_resolvers` module.
fn url_patterns_ws_impl(
	parsed_args: UrlPatternsArgs,
	input: TokenStream,
) -> syn::Result<TokenStream> {
	let func: ItemFn = parse2(input)?;
	let body_tokens = flatten_body(&func);
	let resolvers = build_ws_resolvers(&body_tokens);
	let (wrapper, trait_assertion) = build_wrapper_and_assertion(&func, &parsed_args.app_path)?;

	Ok(quote! {
		#wrapper
		#trait_assertion
		#resolvers
	})
}

/// Unified-mode implementation: emits both server and client resolver modules.
///
/// Scanning relies on the existing `flatten_body` recursion into group tokens,
/// which transparently picks up `.endpoint()/.viewset()/.mount()` calls inside
/// `.server(|s| ...)` closures and `.named_route*()` calls inside
/// `.client(|c| ...)` closures.
fn url_patterns_unified_impl(
	parsed_args: UrlPatternsArgs,
	input: TokenStream,
) -> syn::Result<TokenStream> {
	let func: ItemFn = parse2(input)?;
	let body_tokens = flatten_body(&func);
	let server_resolvers = build_server_resolvers(&body_tokens);
	let client_resolvers = build_client_resolvers(&body_tokens)?;
	let (wrapper, trait_assertion) = build_wrapper_and_assertion(&func, &parsed_args.app_path)?;

	Ok(quote! {
		#wrapper
		#trait_assertion
		#server_resolvers
		#client_resolvers
	})
}

#[cfg(test)]
mod tests {
	use super::*;

	// === Endpoint extraction (existing tests) ===

	#[test]
	fn extract_single_endpoint() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let paths = extract_endpoint_paths(&body_tokens);
		assert_eq!(paths.len(), 1);
		assert_eq!(paths[0].to_string(), "views :: login");
	}

	#[test]
	fn extract_multiple_endpoints() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
					.endpoint(views::register)
					.endpoint(views::profile)
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let paths = extract_endpoint_paths(&body_tokens);
		assert_eq!(paths.len(), 3);
	}

	#[test]
	fn extract_no_endpoints() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let paths = extract_endpoint_paths(&body_tokens);
		assert_eq!(paths.len(), 0);
	}

	#[test]
	fn extract_endpoints_mixed_with_other_calls() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.with_middleware(auth_middleware)
					.endpoint(views::login)
					.endpoint(views::register)
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let paths = extract_endpoint_paths(&body_tokens);
		assert_eq!(paths.len(), 2);
	}

	// === Endpoint reexport (existing tests) ===

	#[test]
	fn build_reexport_relative_path() {
		let path: TokenStream = quote! { views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_crate_path() {
		let path: TokenStream = quote! { crate::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use crate :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_super_path() {
		let path: TokenStream = quote! { super::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_reexport_deeply_nested_path() {
		let path: TokenStream = quote! { api::v1::views::login };
		let result = build_resolver_reexport(&path);
		let expected = "pub use super :: api :: v1 :: views :: __url_resolver_login :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	// --- Meta ident tests (Issue #3647) ---

	#[test]
	fn build_meta_ident_relative_path() {
		let path: TokenStream = quote! { views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	#[test]
	fn build_meta_ident_crate_path() {
		let path: TokenStream = quote! { crate::views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	#[test]
	fn build_meta_ident_deeply_nested() {
		let path: TokenStream = quote! { api::v1::views::login };
		let result = build_meta_ident(&path).unwrap();
		assert_eq!(result.to_string(), "__url_resolver_meta_login");
	}

	/// Normalize whitespace in a token stream string for robust comparison.
	/// Collapses all runs of whitespace to a single space.
	fn normalize_ws(s: &str) -> String {
		s.split_whitespace().collect::<Vec<_>>().join(" ")
	}

	// === Parser tests for new typed syntax (Issue #3670) ===

	#[test]
	fn parse_server_mode_simple_path() {
		let args = quote! { InstalledApp::auth, mode = server };
		let parsed = parse_url_patterns_args(args).expect("should parse");
		assert!(matches!(parsed.mode, UrlPatternsMode::Server));
		assert_eq!(
			parsed
				.app_path
				.path
				.segments
				.last()
				.unwrap()
				.ident
				.to_string(),
			"auth",
		);
	}

	#[test]
	fn parse_client_mode() {
		let args = quote! { InstalledApp::auth, mode = client };
		let parsed = parse_url_patterns_args(args).expect("should parse");
		assert!(matches!(parsed.mode, UrlPatternsMode::Client));
	}

	#[test]
	fn parse_unified_mode() {
		let args = quote! { InstalledApp::auth, mode = unified };
		let parsed = parse_url_patterns_args(args).expect("should parse");
		assert!(matches!(parsed.mode, UrlPatternsMode::Unified));
	}

	#[test]
	fn parse_crate_qualified_path() {
		let args = quote! { crate::config::apps::InstalledApp::auth, mode = server };
		let parsed = parse_url_patterns_args(args).expect("should parse");
		let segments: Vec<String> = parsed
			.app_path
			.path
			.segments
			.iter()
			.map(|s| s.ident.to_string())
			.collect();
		assert_eq!(
			segments,
			vec!["crate", "config", "apps", "InstalledApp", "auth"]
		);
	}

	#[test]
	fn parse_trailing_comma_after_mode() {
		let args = quote! { InstalledApp::auth, mode = server, };
		assert!(parse_url_patterns_args(args).is_ok());
	}

	#[test]
	fn reject_missing_mode() {
		let args = quote! { InstalledApp::auth };
		assert!(parse_url_patterns_args(args).is_err());
	}

	#[test]
	fn reject_unknown_mode() {
		let args = quote! { InstalledApp::auth, mode = foo };
		let err = parse_url_patterns_args(args)
			.err()
			.expect("should return an Err")
			.to_string();
		assert!(err.contains("server"));
		assert!(err.contains("client"));
		assert!(err.contains("unified"));
	}

	#[test]
	fn reject_wrong_key() {
		let args = quote! { InstalledApp::auth, kind = server };
		assert!(parse_url_patterns_args(args).is_err());
	}

	#[test]
	fn reject_mode_as_string_literal() {
		let args = quote! { InstalledApp::auth, mode = "server" };
		assert!(parse_url_patterns_args(args).is_err());
	}

	#[test]
	fn reject_string_literal_first_arg() {
		let args = quote! { "auth", mode = server };
		assert!(parse_url_patterns_args(args).is_err());
	}

	#[test]
	fn reject_empty_args() {
		let args = quote! {};
		assert!(parse_url_patterns_args(args).is_err());
	}

	#[test]
	fn reject_integer_first_arg() {
		let args = quote! { 42, mode = server };
		assert!(parse_url_patterns_args(args).is_err());
	}

	// === Generated code tests ===

	#[test]
	fn server_mode_generates_trait_assertion_and_with_namespace() {
		let args = quote! { InstalledApp::users, mode = server };
		let input = quote! {
			pub fn server_url_patterns() -> ServerRouter {
				ServerRouter::new().endpoint(views::login)
			}
		};

		let out = url_patterns_impl(args, input).expect("should generate");
		let out_s = normalize_ws(&out.to_string());

		assert!(
			out_s.contains("AppLabel"),
			"generated code must reference AppLabel trait; got: {out_s}"
		);
		assert!(
			out_s.contains("__assert_app_label"),
			"generated code must contain the trait-bound assertion fn"
		);
		assert!(
			out_s.contains("with_namespace"),
			"generated code must call .with_namespace"
		);
	}

	#[test]
	fn server_mode_generates_url_resolvers_module_and_for_each_macro() {
		let args = quote! { InstalledApp::users, mode = server };
		let input = quote! {
			pub fn server_url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::login)
					.endpoint(views::register)
			}
		};

		let out = url_patterns_impl(args, input).unwrap();
		let normalized = normalize_ws(&out.to_string());

		assert!(
			normalized.contains("pub mod url_resolvers"),
			"server mode must emit url_resolvers module"
		);
		assert!(
			normalized.contains("__for_each_url_resolver"),
			"server mode must emit __for_each_url_resolver macro"
		);
		// Regression for Issue #3660: $base must be tt+ (not :path)
		assert!(
			normalized.contains("$ ($ base : tt) +"),
			"__for_each_url_resolver must use $($base:tt)+ to allow :: extension"
		);
		assert!(
			!normalized.contains("$ base : path"),
			"__for_each_url_resolver must NOT use $base:path"
		);
		// Regression for Issue #3647: meta idents named __url_resolver_meta_<name>
		assert!(normalized.contains("__url_resolver_meta_login"));
		assert!(normalized.contains("__url_resolver_meta_register"));
	}

	#[test]
	fn server_mode_generated_code_is_valid_rust() {
		let args = quote! { InstalledApp::users, mode = server };
		let input = quote! {
			pub fn server_url_patterns() -> ServerRouter {
				ServerRouter::new().endpoint(views::login)
			}
		};

		let out = url_patterns_impl(args, input).unwrap();
		let wrapped = quote! {
			mod __test_wrapper {
				#out
			}
		};
		let parsed: Result<syn::File, _> = syn::parse2(wrapped);
		assert!(
			parsed.is_ok(),
			"generated code is not valid Rust: {}",
			parsed.unwrap_err()
		);
	}

	#[test]
	fn client_mode_generates_client_url_resolvers_module() {
		let args = quote! { InstalledApp::users, mode = client };
		let input = quote! {
			pub fn client_url_patterns() -> ClientRouter {
				ClientRouter::new().named_route("login", "/login/", || {})
			}
		};
		let out = url_patterns_impl(args, input).expect("should generate");
		let out_s = normalize_ws(&out.to_string());
		assert!(
			out_s.contains("client_url_resolvers"),
			"client mode must emit `client_url_resolvers` module"
		);
		assert!(
			out_s.contains("__for_each_client_url_resolver"),
			"client mode must emit __for_each_client_url_resolver macro"
		);
		assert!(
			out_s.contains("AppLabel"),
			"client mode must include AppLabel trait assertion"
		);
	}

	#[test]
	fn unified_mode_generates_both_resolver_modules() {
		let args = quote! { InstalledApp::users, mode = unified };
		let input = quote! {
			pub fn unified_url_patterns() -> UnifiedRouter {
				UnifiedRouter::new()
					.server(|s| s.endpoint(views::login))
					.client(|c| c.named_route("login_page", "/login/", || {}))
			}
		};
		let out = url_patterns_impl(args, input).expect("should generate");
		let out_s = normalize_ws(&out.to_string());
		assert!(
			out_s.contains("pub mod url_resolvers"),
			"unified mode must emit url_resolvers module"
		);
		assert!(
			out_s.contains("pub mod client_url_resolvers"),
			"unified mode must emit client_url_resolvers module"
		);
		assert!(out_s.contains("__for_each_url_resolver"));
		assert!(out_s.contains("__for_each_client_url_resolver"));
		assert!(out_s.contains("AppLabel"));
		assert!(out_s.contains("with_namespace"));
	}

	// === ViewSet extraction ===

	#[test]
	fn extract_viewset_single() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.viewset("/snippets", views::viewset())
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let calls = extract_chain_calls(&body_tokens, "viewset");
		assert_eq!(calls.len(), 1);
		let path_str = calls[0].expr_path.to_string();
		assert!(path_str.contains("views"));
		assert!(path_str.contains("viewset"));
		// Trailing `()` should be stripped
		assert!(!path_str.ends_with("()"));
	}

	#[test]
	fn extract_viewset_none() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello)
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let calls = extract_chain_calls(&body_tokens, "viewset");
		assert_eq!(calls.len(), 0);
	}

	#[test]
	fn extract_viewset_multiple() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.viewset("/users", views::user_viewset())
					.viewset("/posts", views::post_viewset())
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let calls = extract_chain_calls(&body_tokens, "viewset");
		assert_eq!(calls.len(), 2);
	}

	// === Mount extraction ===

	#[test]
	fn extract_mount_single() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.mount("/api/", crate::apps::api::urls::url_patterns())
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let calls = extract_chain_calls(&body_tokens, "mount");
		assert_eq!(calls.len(), 1);
		let path_str = calls[0].expr_path.to_string();
		assert!(path_str.contains("apps"));
		assert!(path_str.contains("url_patterns"));
	}

	#[test]
	fn extract_mount_none() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello)
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let calls = extract_chain_calls(&body_tokens, "mount");
		assert_eq!(calls.len(), 0);
	}

	// === ViewSet reexport ===

	#[test]
	fn build_viewset_reexport_relative() {
		let call = ChainCall {
			expr_path: quote! { views::viewset },
		};
		let result = build_viewset_reexport(&call);
		let output = result.to_string();
		assert!(output.contains("__viewset_resolvers_viewset"));
		assert!(output.contains("super :: views"));
	}

	#[test]
	fn build_viewset_reexport_crate_path() {
		let call = ChainCall {
			expr_path: quote! { crate::apps::snippets::views::viewset },
		};
		let result = build_viewset_reexport(&call);
		let output = result.to_string();
		assert!(
			output.contains("crate :: apps :: snippets :: views :: __viewset_resolvers_viewset")
		);
	}

	// === Mount reexport ===

	#[test]
	fn build_mount_reexport_crate_path() {
		let call = ChainCall {
			expr_path: quote! { crate::apps::api::urls::url_patterns },
		};
		let result = build_mount_reexport(&call);
		let expected = "pub use crate :: apps :: api :: urls :: url_resolvers :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	#[test]
	fn build_mount_reexport_relative_path() {
		let call = ChainCall {
			expr_path: quote! { api::urls::url_patterns },
		};
		let result = build_mount_reexport(&call);
		let expected = "pub use super :: api :: urls :: url_resolvers :: * ;";
		assert_eq!(result.to_string(), expected);
	}

	// === Combined extraction ===

	#[test]
	fn extract_all_types_combined() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				ServerRouter::new()
					.endpoint(views::hello_world)
					.viewset("/snippets", views::viewset())
					.mount("/api/", crate::apps::api::urls::url_patterns())
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		assert_eq!(extract_endpoint_paths(&body_tokens).len(), 1);
		assert_eq!(extract_chain_calls(&body_tokens, "viewset").len(), 1);
		assert_eq!(extract_chain_calls(&body_tokens, "mount").len(), 1);
	}

	// === Nested control flow extraction (Issue #3648) ===

	#[test]
	fn extract_endpoints_inside_if_else() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				if std::env::var("USE_VIEWSET").is_ok() {
					ServerRouter::new()
						.viewset("/snippets-viewset", views::viewset())
				} else {
					ServerRouter::new()
						.endpoint(views::list)
						.endpoint(views::create)
						.endpoint(views::retrieve)
				}
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let endpoints = extract_endpoint_paths(&body_tokens);
		assert_eq!(endpoints.len(), 3);
		assert_eq!(endpoints[0].to_string(), "views :: list");
		assert_eq!(endpoints[1].to_string(), "views :: create");
		assert_eq!(endpoints[2].to_string(), "views :: retrieve");

		let viewsets = extract_chain_calls(&body_tokens, "viewset");
		assert_eq!(viewsets.len(), 1);
	}

	#[test]
	fn extract_endpoints_inside_match() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				match mode {
					Mode::Full => {
						ServerRouter::new()
							.endpoint(views::list)
							.endpoint(views::create)
					}
					Mode::Readonly => {
						ServerRouter::new()
							.endpoint(views::list)
					}
				}
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let endpoints = extract_endpoint_paths(&body_tokens);
		assert_eq!(endpoints.len(), 3);
	}

	#[test]
	fn parse_ws_mode() {
		let args = quote! { InstalledApp::chat, mode = ws };
		let parsed = parse_url_patterns_args(args).unwrap();
		assert!(matches!(parsed.mode, UrlPatternsMode::Ws));
	}

	#[test]
	fn extract_consumer_paths_basic() {
		let func: ItemFn = parse2(quote! {
			pub fn ws_url_patterns() -> WebSocketRouter {
				WebSocketRouter::new()
					.consumer(chat_ws)
					.consumer(notif_ws)
			}
		})
		.unwrap();
		let body_tokens = flatten_body(&func);
		let paths = extract_consumer_paths(&body_tokens);
		assert_eq!(paths.len(), 2);
		assert_eq!(paths[0].to_string(), "chat_ws");
		assert_eq!(paths[1].to_string(), "notif_ws");
	}

	#[test]
	fn ws_mode_generates_ws_url_resolvers_module() {
		let args = quote! { InstalledApp::chat, mode = ws };
		let input = quote! {
			pub fn ws_url_patterns() -> WebSocketRouter {
				WebSocketRouter::new()
					.consumer(chat_ws)
					.consumer(notif_ws)
			}
		};
		let out = url_patterns_impl(args, input).unwrap();
		let normalized = normalize_ws(&out.to_string());
		assert!(
			normalized.contains("pub mod ws_url_resolvers"),
			"ws mode must emit ws_url_resolvers module"
		);
		assert!(
			normalized.contains("__for_each_ws_url_resolver"),
			"ws mode must emit __for_each_ws_url_resolver macro"
		);
		assert!(normalized.contains("__ws_url_resolver_meta_chat_ws"));
		assert!(normalized.contains("__ws_url_resolver_meta_notif_ws"));
	}

	#[test]
	fn reject_unknown_mode_now_includes_ws() {
		let args = quote! { InstalledApp::auth, mode = foo };
		let err = parse_url_patterns_args(args)
			.err()
			.expect("should return an Err")
			.to_string();
		assert!(err.contains("ws"), "error message should mention ws mode");
	}

	#[test]
	fn extract_mounts_inside_control_flow() {
		let func: ItemFn = parse2(quote! {
			pub fn url_patterns() -> ServerRouter {
				if enabled {
					ServerRouter::new()
						.mount("/api/", crate::apps::api::urls::url_patterns())
				} else {
					ServerRouter::new()
				}
			}
		})
		.unwrap();

		let body_tokens = flatten_body(&func);
		let mounts = extract_chain_calls(&body_tokens, "mount");
		assert_eq!(mounts.len(), 1);
	}
}
