//! Integration tests for the field lookup system

use reinhardt_orm::field_lookup::{Field, Lookup, LookupType};
use reinhardt_orm::Model;
use reinhardt_validators::TableName;
use serde::{Deserialize, Serialize};

// Test model
#[derive(Debug, Clone, Serialize, Deserialize)]
struct User {
    id: i64,
    email: String,
    age: i32,
}

const USER_TABLE: TableName = TableName::new_const("test_user");

impl Model for User {
    type PrimaryKey = i64;

    fn table_name() -> &'static str {
        USER_TABLE.as_str()
    }

    fn primary_key(&self) -> Option<&Self::PrimaryKey> {
        Some(&self.id)
    }

    fn set_primary_key(&mut self, value: Self::PrimaryKey) {
        self.id = value;
    }
}

// Field accessor methods (normally generated by #[derive(FieldLookup)])
impl User {
    pub fn id() -> Field<User, i64> {
        Field::new(vec!["id"])
    }

    pub fn email() -> Field<User, String> {
        Field::new(vec!["email"])
    }

    pub fn age() -> Field<User, i32> {
        Field::new(vec!["age"])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_string_field_contains() {
        let lookup = User::email().contains("example.com");
        assert_eq!(lookup.field_path(), &["email"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Contains);
    }

    #[test]
    fn test_string_field_with_transform() {
        let lookup = User::email().lower().contains("example");
        assert_eq!(lookup.field_path(), &["email", "lower"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Contains);
    }

    #[test]
    fn test_numeric_field_comparison() {
        let lookup = User::age().gte(18);
        assert_eq!(lookup.field_path(), &["age"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Gte);
    }

    #[test]
    fn test_numeric_field_with_transform() {
        let lookup = User::age().abs().gt(5);
        assert_eq!(lookup.field_path(), &["age", "abs"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Gt);
    }

    #[test]
    fn test_field_eq() {
        let lookup = User::email().eq("test@example.com".to_string());
        assert_eq!(lookup.field_path(), &["email"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Exact);
    }

    #[test]
    fn test_field_range() {
        let lookup = User::age().in_range(18, 65);
        assert_eq!(lookup.field_path(), &["age"]);
        assert_eq!(lookup.lookup_type(), &LookupType::Range);
    }
}
