use reinhardt_migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "polls",
		name: "auto_migration_20251202_061438",
		operations: vec![
			Operation::CreateTable {
				name: "questions",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: BigIntegerField,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "question_text",
						type_definition: CharField,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "pub_date",
						type_definition: DateTimeField,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
				],
				constraints: vec![],
			},
			Operation::CreateTable {
				name: "choices",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: BigIntegerField,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "question_id",
						type_definition: BigIntegerField,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "votes",
						type_definition: IntegerField,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "choice_text",
						type_definition: CharField,
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
				],
				constraints: vec![],
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
