name: Cache Docker Images
description: Cache Docker images to avoid Docker Hub rate limits

inputs:
  key:
    description: 'Cache key suffix (e.g., workflow name)'
    required: false
    default: 'default'
  images-file:
    description: 'Path to the file listing Docker images to cache'
    required: false
    default: '.github/docker-images.txt'

runs:
  using: composite
  steps:
    - name: Create cache directory
      shell: bash
      run: mkdir -p ~/docker-cache

    - name: Restore Docker images from cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/docker-cache
        key: docker-images-${{ inputs.key }}-${{ hashFiles(inputs.images-file) }}
        restore-keys: |
          docker-images-${{ inputs.key }}-

    - name: Load or Pull Docker images
      shell: bash
      env:
        IMAGES_FILE: ${{ inputs.images-file }}
        CACHE_HIT: ${{ steps.cache-restore.outputs.cache-hit }}
      run: |
        # Read images from the specified images file
        if [ ! -f "$IMAGES_FILE" ]; then
          echo "Warning: $IMAGES_FILE not found, skipping image caching"
          exit 0
        fi

        while IFS= read -r image || [ -n "$image" ]; do
          # Skip empty lines and comments
          [[ -z "$image" || "$image" =~ ^[[:space:]]*# ]] && continue

          # Trim whitespace
          image=$(echo "$image" | xargs)

          # Create safe filename from image name
          safe_name=$(echo "$image" | tr '/:' '_')
          tar_file=~/docker-cache/${safe_name}.tar

          if [ -f "$tar_file" ]; then
            echo "Loading $image from cache..."
            if docker load -i "$tar_file"; then
              echo "Successfully loaded $image from cache"
              # Remove tar file after successful load to save disk space (cache hit case)
              if [ "$CACHE_HIT" = "true" ]; then
                rm -f "$tar_file"
                echo "Removed $tar_file to save disk space (cache hit)"
              fi
            else
              echo "Failed to load $image from cache, pulling from registry..."
              docker pull "$image"
              docker save -o "$tar_file" "$image"
            fi
          else
            echo "Pulling $image from Docker Hub..."
            if docker pull "$image"; then
              echo "Saving $image to cache..."
              docker save -o "$tar_file" "$image"
            else
              echo "Warning: Failed to pull $image"
            fi
          fi
        done < "$IMAGES_FILE"

    - name: Save Docker images to cache
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/docker-cache
        key: docker-images-${{ inputs.key }}-${{ hashFiles(inputs.images-file) }}

    - name: Cleanup tar files after cache save
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cleaning up tar files after cache save..."
        rm -rf ~/docker-cache
        echo "Removed ~/docker-cache to save disk space"
