//! Portable AST construction and PostgreSQL sequence/identity rendering.
use reinhardt_query::prelude::*;
use rstest::rstest;

#[rstest]
fn qualified_sequence_operations_quote_literal_components() {
	let create = Query::create_sequence()
		.name("a.b\"c")
		.schema("tenant.dot")
		.as_type(SequenceType::SmallInteger)
		.increment(-2)
		.start(-10)
		.owned_by_schema_column("tenant.dot", "owner.dot", "value\"no")
		.to_string(PostgresQueryBuilder);
	assert!(create.contains("\"tenant.dot\".\"a.b\"\"c\" AS smallint"));
	assert!(create.contains("OWNED BY \"tenant.dot\".\"owner.dot\".\"value\"\"no\""));
	let rename = Query::alter_sequence()
		.name("old.dot")
		.schema("tenant.dot")
		.rename_to("new.dot")
		.to_string(PostgresQueryBuilder);
	assert_eq!(
		rename,
		"ALTER SEQUENCE \"tenant.dot\".\"old.dot\" RENAME TO \"new.dot\""
	);
	let drop = Query::drop_sequence()
		.name("new.dot")
		.schema("tenant.dot")
		.restrict()
		.to_string(PostgresQueryBuilder);
	assert_eq!(drop, "DROP SEQUENCE \"tenant.dot\".\"new.dot\" RESTRICT");
}

#[rstest]
fn identity_has_precedence_over_inferred_serial() {
	let column = ColumnDef::new("n")
		.big_integer()
		.auto_increment(true)
		.not_null(true)
		.identity(
			IdentityDef::new(IdentityGeneration::Always)
				.sequence_name("n_seq")
				.sequence_schema("tenant.dot")
				.start(20)
				.increment(2)
				.cache(5),
		);
	let mut table = Query::create_table();
	table.table("events").col(column);
	let sql = table.to_string(PostgresQueryBuilder);
	assert!(sql.contains("BIGINT"));
	assert!(sql.contains("GENERATED ALWAYS AS IDENTITY"));
	assert!(sql.contains("SEQUENCE NAME \"tenant.dot\".\"n_seq\""));
	assert!(!sql.contains("serial"));
	assert!(
		SqliteQueryBuilder
			.build_create_table_checked(&table)
			.is_err()
	);
	assert!(
		MySqlQueryBuilder
			.build_create_table_checked(&table)
			.is_err()
	);
	let mut incomplete = Query::create_table();
	incomplete.table("events").col(
		ColumnDef::new("n")
			.big_integer()
			.identity(IdentityDef::new(IdentityGeneration::Always).sequence_schema("tenant.dot")),
	);
	assert!(
		PostgresQueryBuilder
			.build_create_table_checked(&incomplete)
			.is_err()
	);
}

#[rstest]
fn identity_alter_uses_structured_options_and_rejects_other_backends() {
	// Arrange
	let mut alter = Query::alter_table();
	alter.table(("tenant.dot", "events.dot")).set_identity(
		"value\"no",
		IdentityDef::new(IdentityGeneration::ByDefault)
			.increment(-2)
			.min_value(None)
			.max_value(Some(-1))
			.start(-10)
			.cache(5)
			.cycle(false),
	);
	// Act
	let sql = PostgresQueryBuilder
		.build_alter_table_checked(&alter)
		.unwrap()
		.0;
	// Assert
	assert_eq!(
		sql,
		"ALTER TABLE \"tenant.dot\".\"events.dot\" ALTER COLUMN \"value\"\"no\" SET GENERATED BY DEFAULT SET INCREMENT BY -2 SET NO MINVALUE SET MAXVALUE -1 SET START WITH -10 SET CACHE 5 SET NO CYCLE"
	);
	assert!(!sql.contains("RESTART"));
	assert!(MySqlQueryBuilder.build_alter_table_checked(&alter).is_err());
	assert!(
		SqliteQueryBuilder
			.build_alter_table_checked(&alter)
			.is_err()
	);
	assert!(
		reinhardt_query::backend::CockroachDBQueryBuilder::new()
			.build_alter_table_checked(&alter)
			.is_err()
	);
	let mut invalid = Query::alter_table();
	invalid.table("events").set_identity(
		"n",
		IdentityDef::new(IdentityGeneration::Always).sequence_name("renamed"),
	);
	assert!(
		PostgresQueryBuilder
			.build_alter_table_checked(&invalid)
			.is_err()
	);
}
