language: rust
project_name: "reinhardt"
encoding: "utf-8"
ignore_all_files_in_gitignore: false
ignored_paths:
  - "target/**"
  - "**/*.rs.bk"
  - "**/*.rs.bak*"
  - ".cargo/**"
  - ".git/**"
  - "**/.env*"
# Explicitly include files
include:
  - "**/*.rs"
  - "**/*.toml"
read_only: false
excluded_tools: []
# Recommended context
recommended_context: "ide-assistant"
recommended_modes:
  - "editing"
included_optional_tools:
  - "switch_modes"
# Dashboard settings
web_dashboard: true
web_dashboard_open_on_launch: false # Set to false to disable auto-open on launch
initial_prompt: |
  This is a Rust project using cargo.
  Common commands:
  - Check: cargo check --workspace --all --all-features
  - Build: cargo build --workspace --all --all-features
  - Test: cargo test --workspace --all --all-features
  - Format: cargo make fmt
  - Lint: cargo make clippy
