//! Runtime values generated by component style definitions.

use std::{borrow::Cow, fmt};

/// Error returned when a runtime CSS value fails validation.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum CssValueError {
	/// The supplied color is neither a supported named color nor a hexadecimal color.
	#[error("invalid CSS color `{value}`")]
	InvalidColor {
		/// The rejected value.
		value: String,
	},
}

fn finite(value: f64, wrapper: &str) -> f64 {
	assert!(value.is_finite(), "{wrapper} rejects non-finite values");
	value
}

fn write_decimal(value: f64, output: &mut String) {
	output.push_str(&value.to_string());
}

mod private {
	pub trait Sealed {}
}

/// Sealed serialization contract used by generated component-variable setters.
#[doc(hidden)]
pub trait StyleValue: private::Sealed {
	/// Writes exactly one validated CSS value.
	fn write_css_value(&self, output: &mut String);
	/// Returns the numeric value when this CSS value supports numeric constraints.
	fn numeric_value(&self) -> Option<f64>;
}

macro_rules! numeric_value {
	($name:ident, $wrapper:literal, $suffix:literal) => {
		#[doc = concat!("A finite runtime `", $wrapper, "` CSS value.")]
		#[derive(Clone, Copy, Debug, PartialEq)]
		pub struct $name(f64);

		impl $name {
			/// Creates a validated finite value.
			pub fn new(value: f64) -> Self {
				Self(finite(value, $wrapper))
			}
		}

		impl private::Sealed for $name {}

		impl StyleValue for $name {
			fn write_css_value(&self, output: &mut String) {
				write_decimal(self.0, output);
				output.push_str($suffix);
			}

			fn numeric_value(&self) -> Option<f64> {
				Some(self.0)
			}
		}

		impl fmt::Display for $name {
			fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
				let mut output = String::new();
				self.write_css_value(&mut output);
				formatter.write_str(&output)
			}
		}
	};
}

numeric_value!(CssPercentage, "CssPercentage", "%");
numeric_value!(CssNumber, "CssNumber", "");

/// A finite CSS length with a checked unit.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CssLength {
	value: f64,
	unit: &'static str,
}

macro_rules! length_constructors {
	($(($name:ident, $unit:literal)),+ $(,)?) => {
		impl CssLength {
			$(
				#[doc = concat!("Creates a finite CSS length in `", $unit, "` units.")]
				pub fn $name(value: f64) -> Self {
					Self { value: finite(value, "CssLength"), unit: $unit }
				}
			)+
		}
	};
}

length_constructors!(
	(px, "px"),
	(cm, "cm"),
	(mm, "mm"),
	(q, "q"),
	(inches, "in"),
	(pc, "pc"),
	(pt, "pt"),
	(em, "em"),
	(rem, "rem"),
	(ex, "ex"),
	(rex, "rex"),
	(cap, "cap"),
	(rcap, "rcap"),
	(ch, "ch"),
	(rch, "rch"),
	(ic, "ic"),
	(ric, "ric"),
	(lh, "lh"),
	(rlh, "rlh"),
	(vw, "vw"),
	(vh, "vh"),
	(vi, "vi"),
	(vb, "vb"),
	(vmin, "vmin"),
	(vmax, "vmax"),
	(svw, "svw"),
	(svh, "svh"),
	(svi, "svi"),
	(svb, "svb"),
	(svmin, "svmin"),
	(svmax, "svmax"),
	(lvw, "lvw"),
	(lvh, "lvh"),
	(lvi, "lvi"),
	(lvb, "lvb"),
	(lvmin, "lvmin"),
	(lvmax, "lvmax"),
	(dvw, "dvw"),
	(dvh, "dvh"),
	(dvi, "dvi"),
	(dvb, "dvb"),
	(dvmin, "dvmin"),
	(dvmax, "dvmax"),
	(cqw, "cqw"),
	(cqh, "cqh"),
	(cqi, "cqi"),
	(cqb, "cqb"),
	(cqmin, "cqmin"),
	(cqmax, "cqmax"),
);

impl private::Sealed for CssLength {}

impl StyleValue for CssLength {
	fn write_css_value(&self, output: &mut String) {
		write_decimal(self.value, output);
		output.push_str(self.unit);
	}

	fn numeric_value(&self) -> Option<f64> {
		Some(self.value)
	}
}

impl fmt::Display for CssLength {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		let mut output = String::new();
		self.write_css_value(&mut output);
		formatter.write_str(&output)
	}
}

/// A checked runtime value that is either a CSS length or percentage.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CssLengthPercentage {
	/// A length value.
	Length(CssLength),
	/// A percentage value.
	Percentage(CssPercentage),
}

impl From<CssLength> for CssLengthPercentage {
	fn from(value: CssLength) -> Self {
		Self::Length(value)
	}
}

impl From<CssPercentage> for CssLengthPercentage {
	fn from(value: CssPercentage) -> Self {
		Self::Percentage(value)
	}
}

impl private::Sealed for CssLengthPercentage {}

impl StyleValue for CssLengthPercentage {
	fn write_css_value(&self, output: &mut String) {
		match self {
			Self::Length(value) => value.write_css_value(output),
			Self::Percentage(value) => value.write_css_value(output),
		}
	}

	fn numeric_value(&self) -> Option<f64> {
		match self {
			Self::Length(value) => value.numeric_value(),
			Self::Percentage(value) => value.numeric_value(),
		}
	}
}

impl fmt::Display for CssLengthPercentage {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		let mut output = String::new();
		self.write_css_value(&mut output);
		formatter.write_str(&output)
	}
}

/// A finite CSS angle with one of the registered angle units.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CssAngle {
	value: f64,
	unit: &'static str,
}

impl CssAngle {
	/// Creates a degree value.
	pub fn deg(value: f64) -> Self {
		Self::new(value, "deg")
	}

	/// Creates a gradian value.
	pub fn grad(value: f64) -> Self {
		Self::new(value, "grad")
	}

	/// Creates a radian value.
	pub fn rad(value: f64) -> Self {
		Self::new(value, "rad")
	}

	/// Creates a turn value.
	pub fn turn(value: f64) -> Self {
		Self::new(value, "turn")
	}

	fn new(value: f64, unit: &'static str) -> Self {
		Self {
			value: finite(value, "CssAngle"),
			unit,
		}
	}
}

impl private::Sealed for CssAngle {}

impl StyleValue for CssAngle {
	fn write_css_value(&self, output: &mut String) {
		write_decimal(self.value, output);
		output.push_str(self.unit);
	}

	fn numeric_value(&self) -> Option<f64> {
		Some(self.value)
	}
}

impl fmt::Display for CssAngle {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		let mut output = String::new();
		self.write_css_value(&mut output);
		formatter.write_str(&output)
	}
}

/// A finite CSS time value.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CssTime {
	value: f64,
	unit: &'static str,
}

impl CssTime {
	/// Creates a millisecond value.
	pub fn ms(value: f64) -> Self {
		Self::new(value, "ms")
	}

	/// Creates a seconds value.
	pub fn s(value: f64) -> Self {
		Self::new(value, "s")
	}

	fn new(value: f64, unit: &'static str) -> Self {
		Self {
			value: finite(value, "CssTime"),
			unit,
		}
	}
}

impl private::Sealed for CssTime {}

impl StyleValue for CssTime {
	fn write_css_value(&self, output: &mut String) {
		write_decimal(self.value, output);
		output.push_str(self.unit);
	}

	fn numeric_value(&self) -> Option<f64> {
		Some(self.value)
	}
}

impl fmt::Display for CssTime {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		let mut output = String::new();
		self.write_css_value(&mut output);
		formatter.write_str(&output)
	}
}

/// A runtime integer CSS value.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CssInteger(i64);

impl CssInteger {
	/// Creates an integer value.
	pub const fn new(value: i64) -> Self {
		Self(value)
	}
}

impl private::Sealed for CssInteger {}

impl StyleValue for CssInteger {
	fn write_css_value(&self, output: &mut String) {
		output.push_str(&self.0.to_string());
	}

	fn numeric_value(&self) -> Option<f64> {
		Some(self.0 as f64)
	}
}

impl fmt::Display for CssInteger {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		write!(formatter, "{}", self.0)
	}
}

/// A parsed hexadecimal or named CSS color.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct CssColor(String);

impl CssColor {
	/// Parses one checked CSS color value.
	pub fn parse(value: &str) -> Result<Self, CssValueError> {
		let normalized = value.to_ascii_lowercase();
		let valid = valid_hex_color(&normalized) || NAMED_COLORS.contains(&normalized.as_str());
		valid
			.then_some(Self(normalized))
			.ok_or_else(|| CssValueError::InvalidColor {
				value: value.to_owned(),
			})
	}
}

impl private::Sealed for CssColor {}

impl StyleValue for CssColor {
	fn write_css_value(&self, output: &mut String) {
		output.push_str(&self.0);
	}

	fn numeric_value(&self) -> Option<f64> {
		None
	}
}

impl fmt::Display for CssColor {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		formatter.write_str(&self.0)
	}
}

fn valid_hex_color(value: &str) -> bool {
	let Some(digits) = value.strip_prefix('#') else {
		return false;
	};
	matches!(digits.len(), 3 | 4 | 6 | 8) && digits.bytes().all(|byte| byte.is_ascii_hexdigit())
}

const NAMED_COLORS: &[&str] = &[
	"aliceblue",
	"antiquewhite",
	"aqua",
	"aquamarine",
	"azure",
	"beige",
	"bisque",
	"black",
	"blanchedalmond",
	"blue",
	"blueviolet",
	"brown",
	"burlywood",
	"cadetblue",
	"chartreuse",
	"chocolate",
	"coral",
	"cornflowerblue",
	"cornsilk",
	"crimson",
	"cyan",
	"darkblue",
	"darkcyan",
	"darkgoldenrod",
	"darkgray",
	"darkgreen",
	"darkgrey",
	"darkkhaki",
	"darkmagenta",
	"darkolivegreen",
	"darkorange",
	"darkorchid",
	"darkred",
	"darksalmon",
	"darkseagreen",
	"darkslateblue",
	"darkslategray",
	"darkslategrey",
	"darkturquoise",
	"darkviolet",
	"deeppink",
	"deepskyblue",
	"dimgray",
	"dimgrey",
	"dodgerblue",
	"firebrick",
	"floralwhite",
	"forestgreen",
	"fuchsia",
	"gainsboro",
	"ghostwhite",
	"gold",
	"goldenrod",
	"gray",
	"green",
	"greenyellow",
	"grey",
	"honeydew",
	"hotpink",
	"indianred",
	"indigo",
	"ivory",
	"khaki",
	"lavender",
	"lavenderblush",
	"lawngreen",
	"lemonchiffon",
	"lightblue",
	"lightcoral",
	"lightcyan",
	"lightgoldenrodyellow",
	"lightgray",
	"lightgreen",
	"lightgrey",
	"lightpink",
	"lightsalmon",
	"lightseagreen",
	"lightskyblue",
	"lightslategray",
	"lightslategrey",
	"lightsteelblue",
	"lightyellow",
	"lime",
	"limegreen",
	"linen",
	"magenta",
	"maroon",
	"mediumaquamarine",
	"mediumblue",
	"mediumorchid",
	"mediumpurple",
	"mediumseagreen",
	"mediumslateblue",
	"mediumspringgreen",
	"mediumturquoise",
	"mediumvioletred",
	"midnightblue",
	"mintcream",
	"mistyrose",
	"moccasin",
	"navajowhite",
	"navy",
	"oldlace",
	"olive",
	"olivedrab",
	"orange",
	"orangered",
	"orchid",
	"palegoldenrod",
	"palegreen",
	"paleturquoise",
	"palevioletred",
	"papayawhip",
	"peachpuff",
	"peru",
	"pink",
	"plum",
	"powderblue",
	"purple",
	"rebeccapurple",
	"red",
	"rosybrown",
	"royalblue",
	"saddlebrown",
	"salmon",
	"sandybrown",
	"seagreen",
	"seashell",
	"sienna",
	"silver",
	"skyblue",
	"slateblue",
	"slategray",
	"slategrey",
	"snow",
	"springgreen",
	"steelblue",
	"tan",
	"teal",
	"thistle",
	"tomato",
	"transparent",
	"turquoise",
	"violet",
	"wheat",
	"white",
	"whitesmoke",
	"yellow",
	"yellowgreen",
	"currentcolor",
];

/// One generated scoped class name.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ClassToken(&'static str);

impl ClassToken {
	/// Creates a generated class token.
	#[doc(hidden)]
	pub const fn new(value: &'static str) -> Self {
		Self(value)
	}

	/// Returns the scoped class name.
	pub const fn as_str(&self) -> &'static str {
		self.0
	}
}

/// An ordered composition of generated and legacy class names.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClassList(String);

impl ClassList {
	/// Returns the composed class attribute value.
	pub fn as_str(&self) -> &str {
		&self.0
	}

	fn push(&mut self, value: &str) {
		if value.is_empty() {
			return;
		}
		if !self.0.is_empty() {
			self.0.push(' ');
		}
		self.0.push_str(value);
	}
}

impl std::ops::Add<ClassToken> for ClassToken {
	type Output = ClassList;

	fn add(self, rhs: ClassToken) -> Self::Output {
		let mut list = ClassList(self.0.to_owned());
		list.push(rhs.0);
		list
	}
}

impl std::ops::Add<&'static str> for ClassToken {
	type Output = ClassList;

	fn add(self, rhs: &'static str) -> Self::Output {
		let mut list = ClassList(self.0.to_owned());
		list.push(rhs);
		list
	}
}

impl std::ops::Add<ClassToken> for ClassList {
	type Output = Self;

	fn add(mut self, rhs: ClassToken) -> Self::Output {
		self.push(rhs.0);
		self
	}
}

impl std::ops::Add<&'static str> for ClassList {
	type Output = Self;

	fn add(mut self, rhs: &'static str) -> Self::Output {
		self.push(rhs);
		self
	}
}

impl From<ClassToken> for Cow<'static, str> {
	fn from(value: ClassToken) -> Self {
		Self::Borrowed(value.0)
	}
}

impl From<ClassList> for Cow<'static, str> {
	fn from(value: ClassList) -> Self {
		Self::Owned(value.0)
	}
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct StyleVarValue {
	name: &'static str,
	value: String,
}

/// Source-ordered runtime overrides for generated component variables.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StyleVars {
	slots: Vec<Option<StyleVarValue>>,
}

impl StyleVars {
	/// Creates the fixed number of generated variable slots.
	#[doc(hidden)]
	pub fn with_slots(len: usize) -> Self {
		Self {
			slots: vec![None; len],
		}
	}

	/// Replaces one generated variable slot with a validated value.
	#[doc(hidden)]
	pub fn set<V: StyleValue>(&mut self, index: usize, name: &'static str, value: V) {
		let mut serialized = String::new();
		value.write_css_value(&mut serialized);
		let slot = self
			.slots
			.get_mut(index)
			.expect("generated style variable index is in bounds");
		*slot = Some(StyleVarValue {
			name,
			value: serialized,
		});
	}

	/// Replaces one generated variable slot after enforcing a nonnegative numeric value.
	#[doc(hidden)]
	pub fn set_non_negative<V: StyleValue>(&mut self, index: usize, name: &'static str, value: V) {
		assert!(
			value.numeric_value().is_some_and(|number| number >= 0.0),
			"generated style variable requires a nonnegative numeric value"
		);
		self.set(index, name, value);
	}

	/// Replaces one generated variable slot after enforcing an inclusive numeric range.
	#[doc(hidden)]
	pub fn set_inclusive_range<V: StyleValue>(
		&mut self,
		index: usize,
		name: &'static str,
		minimum: i16,
		maximum: i16,
		value: V,
	) {
		assert!(
			value.numeric_value().is_some_and(|number| {
				number >= f64::from(minimum) && number <= f64::from(maximum)
			}),
			"generated style variable requires a value in the inclusive range {minimum}..={maximum}"
		);
		self.set(index, name, value);
	}
}

impl From<StyleVars> for Cow<'static, str> {
	fn from(value: StyleVars) -> Self {
		if value.slots.iter().all(Option::is_none) {
			return Self::Borrowed("");
		}

		let mut output = String::new();
		for slot in value.slots.into_iter().flatten() {
			output.push_str(slot.name);
			output.push_str(": ");
			output.push_str(&slot.value);
			output.push(';');
		}
		Self::Owned(output)
	}
}
