use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "projects",
		name: "0001_initial",
		operations: vec![
			Operation::CreateTable {
				name: "projects",
				columns: vec![
					ColumnDefinition {
						name: "created_at",
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "description",
						type_definition: FieldType::VarChar(1000u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "name",
						type_definition: FieldType::VarChar(255u32),
						not_null: false,
						unique: true,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "owner_id",
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "visibility",
						type_definition: FieldType::VarChar(20u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![Constraint::Unique {
					name: "projects_project_name_uniq".to_string(),
					columns: vec!["name".to_string()],
				}],
			},
			Operation::CreateTable {
				name: "project_members",
				columns: vec![
					ColumnDefinition {
						name: "id",
						type_definition: FieldType::Uuid,
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "joined_at",
						type_definition: FieldType::DateTime,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "project_id",
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "role",
						type_definition: FieldType::VarChar(20u32),
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
					ColumnDefinition {
						name: "user_id",
						type_definition: FieldType::Uuid,
						not_null: false,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
					},
				],
				constraints: vec![],
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
