#![cfg(feature = "migrations")]

use reinhardt_commands::{
	ConfirmationReader, SquashMigrationsOptions, SquashMigrationsSummary,
	execute_squashmigrations_with_io,
};
use reinhardt_db::migrations::{
	ColumnDefinition, FieldType, FilesystemRepository, FilesystemSource, Migration,
	MigrationRenderOptions, MigrationSource, Operation,
};
use std::fs;
use std::io;
use tempfile::TempDir;

struct TestConfirmation {
	terminal: bool,
	answer: &'static str,
	read_count: usize,
}

impl TestConfirmation {
	fn terminal(answer: &'static str) -> Self {
		Self {
			terminal: true,
			answer,
			read_count: 0,
		}
	}

	fn non_terminal() -> Self {
		Self {
			terminal: false,
			answer: "",
			read_count: 0,
		}
	}
}

impl ConfirmationReader for TestConfirmation {
	fn is_terminal(&self) -> bool {
		self.terminal
	}

	fn read_line(&mut self, buffer: &mut String) -> io::Result<usize> {
		self.read_count += 1;
		buffer.push_str(self.answer);
		Ok(self.answer.len())
	}
}

fn create_migration_tree() -> (TempDir, std::path::PathBuf) {
	let temporary = TempDir::new().unwrap();
	let root = temporary.path().join("migrations");
	let repository = FilesystemRepository::new(&root);

	let mut first = Migration::new("0001_initial", "polls");
	first.operations.push(Operation::CreateTable {
		name: "entries".to_string(),
		columns: vec![ColumnDefinition::new("id", FieldType::Integer)],
		constraints: vec![],
		without_rowid: None,
		interleave_in_parent: None,
		partition: None,
	});
	let mut second = Migration::new("0002_remove_entries", "polls");
	second.dependencies = vec![("polls".to_string(), "0001_initial".to_string())];
	second.operations.push(Operation::DropTable {
		name: "entries".to_string(),
	});

	for migration in [&first, &second] {
		let source = repository
			.render(
				migration,
				MigrationRenderOptions {
					include_header: true,
				},
			)
			.unwrap();
		repository
			.create_new_source(&migration.app_label, &migration.name, &source)
			.unwrap();
	}

	(temporary, root)
}

fn default_options() -> SquashMigrationsOptions {
	SquashMigrationsOptions {
		app_label: "polls".to_string(),
		start_migration: None,
		migration_name: "0002".to_string(),
		no_optimize: false,
		no_input: false,
		no_header: false,
		squashed_name: None,
	}
}

#[tokio::test]
async fn tty_confirmation_accepts_and_writes_the_exact_summary() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let mut confirmation = TestConfirmation::terminal("yes\n");
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();
	let expected_path = root.join("polls/0001_squashed_0002.rs");

	// Act
	let summary = execute_squashmigrations_with_io(
		&root,
		default_options(),
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap()
	.unwrap();

	// Assert
	assert_eq!(summary.app_label, "polls");
	assert_eq!(summary.start_migration, "0001_initial");
	assert_eq!(summary.end_migration, "0002_remove_entries");
	assert_eq!(summary.squashed_name, "0001_squashed_0002");
	assert_eq!(summary.migration_count, 2);
	assert_eq!(summary.original_operation_count, 2);
	assert_eq!(summary.optimized_operation_count, 0);
	assert_eq!(summary.path, expected_path);
	assert_eq!(confirmation.read_count, 1);
	assert_eq!(
		String::from_utf8(stderr).unwrap(),
		"Squash 2 migrations (2 operations -> 0) into \
		 0001_squashed_0002? [y/N] "
	);
	assert_eq!(
		String::from_utf8(stdout).unwrap(),
		format!(
			"App: polls\nRange: 0001_initial -> 0002_remove_entries\n\
			 Migrations: 2\nOperations: 2 -> 0\nCreated: {}\n",
			expected_path.display()
		)
	);
	assert!(fs::read_to_string(expected_path).unwrap().starts_with(
		"// reinhardt-migration-source: 1\n// Generated by Reinhardt migrations.\n\n"
	));
}

#[tokio::test]
async fn tty_confirmation_declines_without_writing() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let mut confirmation = TestConfirmation::terminal("n\n");
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();

	// Act
	let summary = execute_squashmigrations_with_io(
		&root,
		default_options(),
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap();

	// Assert
	assert_eq!(summary, None);
	assert_eq!(stdout, b"");
	assert_eq!(
		String::from_utf8(stderr).unwrap(),
		"Squash 2 migrations (2 operations -> 0) into \
		 0001_squashed_0002? [y/N] Cancelled.\n"
	);
	assert!(!root.join("polls/0001_squashed_0002.rs").exists());
}

#[tokio::test]
async fn non_terminal_input_is_rejected_without_no_input() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let mut confirmation = TestConfirmation::non_terminal();
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();

	// Act
	let error = execute_squashmigrations_with_io(
		&root,
		default_options(),
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap_err();

	// Assert
	assert_eq!(
		error.to_string(),
		"Invalid arguments: squashmigrations requires terminal input; use --no-input in \
		 non-interactive environments"
	);
	assert_eq!(confirmation.read_count, 0);
	assert_eq!(stdout, b"");
	assert_eq!(stderr, b"");
	assert!(!root.join("polls/0001_squashed_0002.rs").exists());
}

#[tokio::test]
async fn no_input_writes_without_reading_terminal_input() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let mut options = default_options();
	options.no_input = true;
	let mut confirmation = TestConfirmation::non_terminal();
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();

	// Act
	let summary = execute_squashmigrations_with_io(
		&root,
		options,
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap();

	// Assert
	assert!(summary.is_some());
	assert_eq!(confirmation.read_count, 0);
	assert_eq!(stderr, b"");
	assert!(root.join("polls/0001_squashed_0002.rs").exists());
}

#[tokio::test]
async fn validation_errors_happen_before_prompting_and_preserve_existing_files() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let existing = root.join("polls/0001_initial.rs");
	let existing_source = fs::read_to_string(&existing).unwrap();
	let mut options = default_options();
	options.migration_name = "000".to_string();
	let mut confirmation = TestConfirmation::terminal("yes\n");
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();

	// Act
	let error = execute_squashmigrations_with_io(
		&root,
		options,
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap_err();

	// Assert
	assert_eq!(
		error.to_string(),
		"Invalid arguments: Invalid migration: Ambiguous migration prefix '000' for app 'polls'; \
		 candidates: 0001_initial, 0002_remove_entries"
	);
	assert_eq!(confirmation.read_count, 0);
	assert_eq!(fs::read_to_string(existing).unwrap(), existing_source);
	assert!(!root.join("polls/0001_squashed_0002.rs").exists());
}

#[tokio::test]
async fn unsafe_custom_name_is_rejected_before_prompting() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	for unsafe_name in [
		"",
		"../escape",
		"with/slash",
		"with\\slash",
		"with.dot",
		"with space",
		"with\ncontrol",
		"0001_compacted",
	] {
		let mut options = default_options();
		options.squashed_name = Some(unsafe_name.to_string());
		let mut confirmation = TestConfirmation::terminal("yes\n");
		let mut stdout = Vec::new();
		let mut stderr = Vec::new();

		// Act
		let error = execute_squashmigrations_with_io(
			&root,
			options,
			&mut confirmation,
			&mut stdout,
			&mut stderr,
		)
		.await
		.unwrap_err();

		// Assert
		assert_eq!(
			error.to_string(),
			"Invalid arguments: --squashed-name must be a safe ASCII Rust filename suffix"
		);
		assert_eq!(confirmation.read_count, 0);
		assert_eq!(stdout, b"");
		assert_eq!(stderr, b"");
	}
	assert!(!root.parent().unwrap().join("escape.rs").exists());
}

#[tokio::test]
async fn no_optimize_preserves_operation_order_and_no_header_omits_header() {
	// Arrange
	let (_temporary, root) = create_migration_tree();
	let mut options = default_options();
	options.no_input = true;
	options.no_optimize = true;
	options.no_header = true;
	options.squashed_name = Some("compacted".to_string());
	let mut confirmation = TestConfirmation::non_terminal();
	let mut stdout = Vec::new();
	let mut stderr = Vec::new();

	// Act
	let summary = execute_squashmigrations_with_io(
		&root,
		options,
		&mut confirmation,
		&mut stdout,
		&mut stderr,
	)
	.await
	.unwrap()
	.unwrap();

	// Assert
	let path = root.join("polls/0001_compacted.rs");
	let source = fs::read_to_string(&path).unwrap();
	let loaded = FilesystemSource::new(&root)
		.all_migrations()
		.await
		.unwrap()
		.into_iter()
		.find(|migration| migration.name == "0001_compacted")
		.unwrap();
	assert_eq!(
		source.lines().next(),
		Some("// reinhardt-migration-source: 1")
	);
	assert!(!source.contains("Generated by Reinhardt migrations"));
	assert_eq!(
		summary,
		SquashMigrationsSummary {
			app_label: "polls".to_string(),
			start_migration: "0001_initial".to_string(),
			end_migration: "0002_remove_entries".to_string(),
			squashed_name: "0001_compacted".to_string(),
			migration_count: 2,
			original_operation_count: 2,
			optimized_operation_count: 2,
			path,
		}
	);
	assert_eq!(loaded.name, "0001_compacted");
	assert_eq!(
		loaded.operations,
		vec![
			Operation::CreateTable {
				name: "entries".to_string(),
				columns: vec![ColumnDefinition::new("id", FieldType::Integer)],
				constraints: vec![],
				without_rowid: None,
				interleave_in_parent: None,
				partition: None,
			},
			Operation::DropTable {
				name: "entries".to_string(),
			},
		]
	);
}
